### ISSUE TITLE
Add appveyor and travisci testing

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#101]
One example is in https://github.com/qiicr/dcmqi

**Comment by fedorov** [comment]
for the reference - an example of setup of python on appveyor: https://github.com/astropy/conda-builder-affiliated/blob/master/appveyor.yml

**Comment by jcfr** [comment]
Fixed by https://github.com/Radiomics/pyradiomics/commit/f7a7307aa0a4b6ced5624638151d2bf0c3c82c69
