### ISSUE TITLE
Versioning at install

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#168]
Currently, versioning is added to the folder name of the package when it is installed in site-packages. However, this causes it to create new folders for every new commit that is installed. With pip distributions, it regularly uninstalls older versions of a package before installing the new version.

Will this also happen when pyradiomics is published? Is there another way to specify that the version information should not be included in the name of the installed folder? Or that older versions of the package are uninstalled first?

**Comment by jcfr** [comment]
> Will this also happen when pyradiomics is published?

If a new version of the package is published (e.g 2.0), previous version will be uninstalled.

> Is there another way to specify that the version information should not be included in the name of the installed folder?  Or that older versions of the package are uninstalled first?

Do you have a step-by-step scenario allowing to reproduce this ?

**Comment by JoostJM** [comment]
@jcfr, If I install using setup.py, it creates a new folder in site-packages, without first uninstalling the previous version. I don't know how the install from python wheels will work though.

**Comment by JoostJM** [comment]
Versioning not a problem when installing directly from repository or from wheel. Only when trying to install from zip folder of the repository is the version not taken into account
