### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by haarburger** [Radiomics/pyradiomics#178]
Do you see any potential issues for adding python 3 compatibility? As far as I see the dependencies, making pyradiomics compatible with both python 2 and 3 shouldn't be very difficult...

**Comment by JoostJM** [comment]
@Radiomics/developers

**Comment by JoostJM** [comment]
At the moment I don't see any special issues, but we haven't tested it. Is there a special reason you want to have this?

**Comment by fedorov** [comment]
http://python3porting.com/

**Comment by haarburger** [comment]
All my codebase is written in Python 3, so if I want to use your package for a project it is easier to have it in Python 3 as well. I'd be happy to contribute to the project.

**Comment by fedorov** [comment]
@haarburger as one of the initial steps, it might make sense to look at whether the dependencies of pyradiomics are compatible with Python 3. 

Your contributions are welcomed!

**Comment by jcfr** [comment]
Closing this issue. 

As of https://github.com/Radiomics/pyradiomics/commit/84dc7274f4c217be3512af8a17c70bd992fc23bd, Python3 support has been merged.

**Comment by jcfr** [comment]
Tests are running for Python2.7, Python3.4 and Python 3.5
