### ISSUE TITLE
Build around Pandas / DataFrames instead of CSVWriter

### ISSUE THREAD

**Issue by kmader** [Radiomics/pyradiomics#189]
The library would be a lot more flexible if it were built around Pandas and DataFrames since they are better suited for looking at collections of data. They also allow for many more export options like json, html, csv, and have better support for types inside columns extendable to figures and arrays

![image](https://cloud.githubusercontent.com/assets/116120/22780515/4c6e8d6c-eebf-11e6-955a-50ef0499f565.png)

**Comment by JoostJM** [comment]
@kmader, thanks for the suggestion! We've discussed this with the team and we'll start looking how to best implement this into PyRadiomics.

**Comment by JoostJM** [comment]
@kmader, I've added an example of how you can use pandas to process the result of PyRadiomics in PR #228 . It is not needed for data handling inside PyRadiomics and the returned result from the feature extractor can easily be converted to a pandas Series, thereby removing the need to rewrite a lot of source code and have pandas as an additional dependency.

In PR #225 pandas is used much more extensively throughout the PyRadiomics package, but this does not change output or performance, but will need pandas as another dependency, so this PR will most likely be closed and not merged.
