### ISSUE TITLE
six is missing from the import in the "Interactive Use" section of the usage page

### ISSUE THREAD

**Issue by segig** [Radiomics/pyradiomics#208]
Hi everyone,

six is missing from the import in the "Interactive Use" section of the [Usage](http://pyradiomics.readthedocs.io/en/latest/usage.html) page.

Cheers,

Sébastien

**Comment by JoostJM** [comment]
@segig, thanks for the headsup! Will be addressed in #207

**Comment by JoostJM** [comment]
Resolved by #207
