### ISSUE TITLE
Remove non-core dependencies

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#230]
To keep number of requirements down, remove dependencies that are not needed for (regular) use of core functions.

*  [x] Move nose dependencies to requirements-dev
*  [ ] Move Sphinx dependencies to requirements-docs
*  [x] Remove dependency of tqdm

**Comment by jcfr** [comment]
> Move Sphinx dependencies to requirements-docs

For now, I think having them in `requirements-dev.txt` is good enough. I may revisit things while working on the Slicer radiomics  integration.

**Comment by jcfr** [comment]
> Remove dependency of tqdm

For progress reporting, I also like the idea of context manager. 
See http://pocco-click.readthedocs.io/en/latest/utils.html#showing-progress-bars and https://github.com/girder/girder/blob/834cf29acc3538b38ba24e6e7203852924110843/clients/python/girder_client/__init__.py#L823

**Comment by JoostJM** [comment]
> For progress reporting, I also like the idea of context manager.

The problem is not so much that tqdm does not work as we expect, just that it is yet another dependency, but one that is nearly never used (only used in full-python mode for 2 of the 5 feeature classes)

**Comment by JoostJM** [comment]
Removal of `tqdm` dependency addressed by #232

**Comment by JoostJM** [comment]
> For progress reporting, I also like the idea of context manager

I looked at your code, really nice! I will see how to adapt this to PyRadiomics. In the mean time I opened a PR which now exposes a kind of quick-and-dirty fix.

**Comment by JoostJM** [comment]
@jcfr, I took your example with a dummy progress reporter in girder and adapted it to PyRadiomics. I tested it with both `tqdm` (can be used directly) and `click` (used in a simple wrapper class). I also pass the iterable (gray levels) to the progress bar instead of a length and calls to `update`, because this was more similar between `tqdm` and `click`.

**Comment by JoostJM** [comment]
Addressed by #231
