### ISSUE TITLE
the GLCM matrix created by LLL filter coiflet wavelet is too big

### ISSUE THREAD

**Issue by GengboLiu** [Radiomics/pyradiomics#237]
When I was trying to extract GLCM wavelet feature, the memory run out at LLL filter coiflet wavelet on some patients. But the code work for other patients. I think that because the mask size is different, the patient with big size mask may need more space to store GLCM. I am wondering if there are any suggestions to deal with this situation.

**Comment by JoostJM** [comment]
@GengboLiu, can you send the traceback of the error?
What kind of hardware are you using?

When the wavelet is calculated, all derivatives are made before features are calculated (7 images per level + 1 approximation). Aside from that, the GLCM will have size numGraylevels ^ 2 x number of angels (13 in 3D). As LLL is the approximation, the number of gray levels will be similar to those for the original image, so I don't expect the GLCM matrix to be much larger than the matrix for the original image.

**Comment by GengboLiu** [comment]
Thank you very much for the advise. It is able to run now. The time it takes beyond my prospection. The LLL filter just take more time than other filters. Therefore it takes more time to run. My hardware is Macbook i7 processor and 16 GB memory.
