### ISSUE TITLE
Error while running PyRadiomics Example.ipynb for a new .nrrd label file created from Slicer tool

### ISSUE THREAD

**Issue by devareddy** [Radiomics/pyradiomics#239]
While i am trying to generate radiomic features from a lung tumor created from Slicer tool in the form of label .nrrd , am seeing the below error. 
RuntimeError: Exception thrown in SimpleITK LabelShapeStatisticsImageFilter_GetBoundingBox: /tmp/SimpleITK-build/ITK-prefix/include/ITK-4.10/itkLabelMap.hxx:152:
itk::ERROR: LabelMap(0x3761f30): No label object with label 1.

Interestingly,  am able to generate  features from HeterogenetyCAD in Slicer

Can you help me in resolving this?

Thanks in advance
-D

**Comment by JoaoSantinha** [comment]
Hi does your label contain the value 1? pyradiomics by default will analyse the labels with value 1. If that is not your case maybe you can relabel it or change the label value.

Example of where the label 1 is used - http://pyradiomics.readthedocs.io/en/latest/_modules/radiomics/imageoperations.html#cropToTumorMask 

Hope it helps ;)

Joao

**Comment by devareddy** [comment]
Dear Joao,

Thanks for the reply.
Jut verified,featureextarctor.py has label value by default as 1.
I am still wondering why am i getting this error.
Same helloRadiomics.py is working for the examples shipped with software.
Surprisingly,  helloRadiomics.py is not working for the new label .nrrd file i generated using Slicer.
Am i missing something?
Your help is highly appreciated. 

-D

**Comment by fedorov** [comment]
@devareddy not sure why this would be. 

Can you please describe how you create the label, and how you save it?

When you say you can generate features in HeterogenetyCAD in Slicer - can you generate features using SlicerRadiomics module (see https://github.com/radiomics/SlicerRadiomics)? HeterogeneityCAD runs in Slicer, so there is no intermediate step saving the label, perhaps something goes wrong on save.

**Comment by devareddy** [comment]
@fedorov 
I  created  a segmentation as label map using Slicer Editor module and saved it as .nrrd file.
The same file is fed to Pyradiomics as input, giving me an error mentioned above.

-D

**Comment by JoostJM** [comment]
@devareddy, It is true that the `featureextractor.py` uses label '1' as it's default, but is that also the value of the label in your segmentation labelmap. The error you're experiencing states that there is no segmentation with the value you provided in `label` for your loaded labelmap. Most likely, the segmentation is there, but has been assigned a different value. You can find out which label values are present in a label map as follows:

    import SimpleITK as sitk
    lsif = sitk.LabelShapeStatisticsImageFilter()
    lsif.Execute(maskNode)
    labels = lsif.GetLabels()

Here, `maskNode` is the SimpleITK image object you generate from your .nrrd file (using sitk.ReadImage) and labels is a tuple of all unique non-zero values in your labelmap.

**Comment by JoostJM** [comment]
@devareddy, did you manage to fix this error?

**Comment by JoostJM** [comment]
@devareddy I'm closing this issue. If you have further questions or comments, please feel free to reopen it.

**Comment by fedorov** [comment]
Please clarify your question. Are you asking how to segment the image? If so, you should look into 3D Slicer software: https://slicer.org.
