### ISSUE TITLE
SimpleITK fully on PyPi

### ISSUE THREAD

**Issue by blowekamp** [Radiomics/pyradiomics#247]
I just wanted to let this project know that all the available binaries are available on PyPI now. So simply `pip install` will work, or even just using a requirements.txt file works.

Hope this works easier for you and your users.

**Comment by jcfr** [comment]
Well done 👍 

Did you get special exemption to update large distribution on PyPI ?

**Comment by blowekamp** [comment]
The largest wheel is only 38MB now. Previously the MacOSX wheels were about ~80MB, but that was for the universal "intel" architectures. Pip has since learned that the "x86_64" is compatible with a "intel" python runtimes. So the OS X Wheels are now only 35MB, and comfortably fit on PyPI.

**Comment by jcfr** [comment]
Thanks for detailed explanation 👍

**Comment by blowekamp** [comment]
O yeah, so why did I leave this comment? Because it looks like the `installation.rst` file should be updated to remove the old SimpleITK work arounds.
