### ISSUE TITLE
Handling of mismatched size mask is still not working

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#259]
I think the issue is that the resampled mask does not get propagated from here: https://github.com/Radiomics/pyradiomics/blob/master/radiomics/imageoperations.py#L238

`checkMask` returns the bounding box for the resampled mask here: https://github.com/Radiomics/pyradiomics/blob/master/radiomics/featureextractor.py#L326

But `cropToTumorMask` is operating on the original mask before resampling: https://github.com/Radiomics/pyradiomics/blob/master/radiomics/featureextractor.py#L340

Identified by Dev Gude.

**Comment by fedorov** [comment]
@JoostJM I suggest to fix this by having `checkMask` return a tuple of bounding box and an updated mask, if it had to be resampled, and then use that updated mask after the mask check. Do you have objections?

**Comment by JoostJM** [comment]
No objections, saves me the trouble ;-)





-------- Oorspronkelijk bericht --------
Van: Andrey Fedorov <notifications@github.com>
Datum: 25-05-17 20:09 (GMT+01:00)
Aan: Radiomics/pyradiomics <pyradiomics@noreply.github.com>
Cc: Joost van Griethuysen <j.v.griethuysen@nki.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [Radiomics/pyradiomics] Handling of mismatched size mask is still not working (#259)


@JoostJM<https://github.com/joostjm> I suggest to fix this by having checkMask return a tuple of bounding box and an updated mask, if it had to be resampled, and then use that updated mask after the mask check. Do you have objections?

-
