### ISSUE TITLE
Switch PyRadiomics License

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#268]
To have a more clear, but still open license, switch from the 3D slicer license to an open license.

No copyleft license, as this is incompatible with the Slicer license (as needed in SlicerRadiomics).

Alternatives:
- [Apache License 2.0](http://www.tldrlegal.com/license/apache-license-2.0-(apache-2.0))
- [MIT License](https://tldrlegal.com/license/mit-license)

cc @Radiomics/developers

**Comment by JoostJM** [comment]
Also consider adding disclaimer specifying PyRadiomics is not intended for clinical use
 (e.g. print statement in the `__init__.py`)

**Comment by fedorov** [comment]
Differences between the two alternatives, quoted from https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license:

![image](https://user-images.githubusercontent.com/313942/27871158-d7ca4934-6172-11e7-9aca-4cae480596a3.png)

**Comment by JoostJM** [comment]
@haarburger, @jbvimort, @jaasantinha, @blezek, @vnarayan13.
I mentioned you here because you are also listed as contributors on PyRadiomics.

**Comment by blezek** [comment]
+1 for MIT License.  Simple so people don't need to think about it.

**Comment by fedorov** [comment]
Another option is [3-clause BSD](https://opensource.org/licenses/BSD-3-Clause), it is also used quite often in the research software. Very close to MIT, but the difference is this part:

> Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

**Comment by fedorov** [comment]
Some relevant discussions 

* https://lists.opensource.org/pipermail/license-discuss/2008-July/015898.html
* license for XNAT: https://lists.opensource.org/pipermail/license-discuss/2011-April/016997.html (it looks like in the end XNAT people were convinced to go with the 2-clause BSD: https://www.xnat.org/download/)

Few more data points for the popular open source projects that came to my mind:
* [ITK is Apache-2](https://itk.org/gitweb?p=ITK.git;a=blob;f=LICENSE;h=d645695673349e3947e8e5ae42332d0ac3164cd7;hb=HEAD)
* [VTK is 3-clause BSD](https://github.com/Kitware/VTK/blob/master/Copyright.txt). 
* elastix [used to be simplified BSD, but then switched to Apache-2](http://elastix.isi.uu.nl/legal.php)
* [ANTs is 3-clause BSD](https://github.com/stnava/ANTs)
* [cornerstone is MIT](https://github.com/chafey/cornerstone)

I am leaning towards either 3-clause BSD or MIT. Apache-2 is so long!

**Comment by vnarayan13** [comment]
Hi guys, I am fine with the MIT License.

**Comment by JoaoSantinha** [comment]
Hi everyone, I would go for MIT.
Cheers,
Joao

**Comment by jcfr** [comment]
Moving to an OSI approved license is great. I have no problem with MIT or 3-clause BSD  license. :+1:
