### ISSUE TITLE
Missing folder causes download problem in FeatureVisualization.ipynb

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#276]
![image](https://user-images.githubusercontent.com/313942/28280122-b9d06ee0-6af0-11e7-8839-b94826d64ef5.png)

**Comment by JoostJM** [comment]
If I see it correctly, this error is due to the fact that folder `example_data` may not exist. Python is then unable to create the file and the error is thrown.

**Comment by fedorov** [comment]
You are right, I mis-diagnosed the problem.

**Comment by JoostJM** [comment]
@fedorov, not entirely ;-), the url is also invalid, as the urlretrieve method does not download a valid zipfile. If I remember correctly, it is some sort of server error. Anyway, I don't use the feature visualization notebooks in the docker image, but the pyradiomics notebooks that use the example data already present in the pyradiomics repo.

**Comment by JoostJM** [comment]
Feature visualization notebooks have been updated in 8c4313d, 35dbff6 and 8b73d4c, including a fix for the broken download link

**Comment by HripsimeS** [comment]
@JoostJM @fedorov Can you please let me know where/how I can download "Tumorbase.zip", because the URL you mentioned some years ago is not valid anymore. Look forward to hearing from you! Thanks

**Comment by zrggci** [comment]
> @JoostJM Joost, the Tumorbase.zip cannot be donwloaded from http://www.spl.harvard.edu/publications/bitstream/download/5270. Is there any other way of getting this file. I am trying to get more familiar with Radiomics.

you can download tumorbase.zip in this website:https://github.com/AIM-Harvard/pyradiomics/issues/276

**Comment by AartSpilt** [comment]
Yes, thank you!
