### ISSUE TITLE
Default sigma values for LoG

### ISSUE THREAD

**Issue by aydindemircioglu** [Radiomics/pyradiomics#279]
After updating to the latest package, we realized that no LoG filters were extracted, so before we had 1841 (or so) features, and afterwards only 1041. That irritated us slightly, as we expected that enabling all filters and features would result in the 'largest' feature set possible.

But it seems that you have changed this default behaviour, as the getLoGImage class now reads
 sigmaValues = kwargs.get('sigma', [])
(instead of  sigmaValues = kwargs.get('sigma', numpy.arange(5., 0., -.5)) as before).

So is it better to skip these features altogether or to compute still some of these, maybe on a coarser grid?

Also, is this change already in the documentation? index.rst reads:

"On average, Pyradiomics extracts \approx 1300 features per image, which consist of the 16 shape descriptors and features extracted from original and derived images (LoG with 5 sigma levels, 1 level of Wavelet decomposistions yielding 8 derived images and images derived using Square, Square Root, Logarithm and Exponential filters)."

Thanks for all your hard work, we highly appreciate it!

**Comment by fedorov** [comment]
Thanks for reporting this, and for the nice words about pyradiomics! 

I am not sure why the default behavior was changed. We will update the issue once we have a chance to discuss and find the answer!

**Comment by JoostJM** [comment]
@aydindemircioglu, The default setting for sigma was removed, as this default setting was based on a CT example, whereas pyradiomics is intended for multiple modalities. The warning is documented [here](http://pyradiomics.readthedocs.io/en/latest/radiomics.html#radiomics.imageoperations.getLoGImage), but I can make it a bit more explicit (separate warning box).

In #273, some example settings are provided for CT and MR modalities as a starting point. These also include some suggested sigma values.

**Comment by aydindemircioglu** [comment]
thanks, as said, we just moved from an old version to the newer one, so we did not see the documentations at first. as long as you document it and even better have examples for the different modalities, its perfect. i'll close the issue then.

again, thanks!
