### ISSUE TITLE
pyradiomicsbatch multiprocessing

### ISSUE THREAD

**Issue by sohrabtowfighi** [Radiomics/pyradiomics#282]
Can an argument be added (eg 'n_jobs=-1' for all cores) to pyradiomicsbatch which uses multiprocessing to distribute the computations across cores?

**Comment by pieper** [comment]
We've discussed parallelism but generally consider it should be handled at a higher level of abstraction.  For example if you run a big set of jobs on a cluster you would use the job queuing system to manage job allocation.

**Comment by sohrabtowfighi** [comment]
Isn't that the purpose of pyradiomics**batch**

**Comment by fedorov** [comment]
The specific meaning of **batch** that we had in mind is to support processing of multiple datasets in one run, not to distribute that processing across computational resources.

**Comment by JoostJM** [comment]
@pieper, the parallelisation we discussed can indeed be applied in a batch (i.e. one patient, one core). We've been working with a specialised script that does this, but it was optimized for our dataset. I'll see if I can adapt one to be more general.
