### ISSUE TITLE
Multi-nodules feature extraction

### ISSUE THREAD

**Issue by saeedalahmari3** [Radiomics/pyradiomics#293]
I got scans (images) of multi-nodules, each image has at least one nodule, it may have 2 or 3 and so on. I would like to get features for every nodule found in a scan. Is there anyway to do it using pyradiomics?

**Comment by JoostJM** [comment]
Basically, there are 3 scenarios:
1. 1 mask file for each nodule: Extract features by specifying each combination in the input csv file (i.e. same image, different mask, add a column specifying which nodule is represented by the mask file).
2. 1 mask file for all nodules, each nodule different label value: Extract features by specifying the the combination of image and mask multiple times, where you add a column (header: "Label"), where you specify the value of the label for each individual nodule
3. 1 mask file for all nodules, all nodules same label value: Here, you first have to generate unique label values for each nodule. One potential solution to do this is through [SimpleITK:ConnectedComponentImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ConnectedComponentImageFilter.html) class. This will assign a unique label value to each volume (i.e. nodule) in the input mask:

```python
import SimpleITK as sitk

ma_path = r'PATH/TO/MASK'
ma = sitk.ReadImage(ma_path)

ccif = sitk.ConnectedComponentImageFilter()
ccif.SetFullyConnectedOn  # Fully connected (26 neigbours), comment out to use default fully connected off (= vertex connectivity; 6 neighbours)
new_ma = ccif.Execute(ma)

numNodules = ccif.GetObjectCount()  # Number of fully connected components identified

# Write out new mask file, use this file to extract features
sitk.WriteImage(new_ma, r'PATH/TO/NEWMASK.nrrd', True)  # 'True' indicates to save in compressed format (as it is just a mask file, it doesn't have to be stored in uncompressed format)
 ```

**Comment by JoostJM** [comment]
@saeedalahmari3, does this answer your question? If so, then this issue can be closed.

**Comment by mozdag** [comment]
Hello,
I ran the abovementioned code but it still runs the features once, in my case there are 281 nodules. I should see all the feature values 281 times, which means for all of the nodules. How can I print them all?

**Comment by fedorov** [comment]
You need to run the extraction for each of the label values.

**Comment by mozdag** [comment]
Based on the code above, I am running:
featureVector = extractor.execute(imageName, new_ma)
for featureName in featureVector.keys():
  print("Computed %s: %s" % (featureName, featureVector[featureName]))

And this returns features with only one value for each feature. So, can you fix my code please for how to run the extraction for each of the label values?

**Comment by mozdag** [comment]
By the way, my numNodule is 281 (numNodules = ccif.GetObjectCount())

**Comment by JoostJM** [comment]
You need to specify which label to extract for. 

```
Nodules = []
for l in range(1, ccif.GetObjectCount() + 1):
  Nodules.append(extractor.execute(image, newMask, label=l))
```
Note: it is perhaps best to first also load the image, so the image isn't reread from the disk every time, reducing the IO time. The result of `sitk.ReadImage(ImageName)` is a valid input for the `extractor.execute` image parameter.

**Comment by mozdag** [comment]
You mean, first load the new mask image (new_ma)?

**Comment by mozdag** [comment]
Like as follows?
new_ma = ccif.Execute(maskName)

sitk.WriteImage(new_ma, './tests/resource/TCGA-21-5786-01Z-00-DX1_NEWMASK.nrrd', True)
new_ma = sitk.ReadImage('./tests/resource/TCGA-21-5786-01Z-00-DX1_NEWMASK.nrrd', sitk.sitkInt8)

ANOTHER QUESTION: By the way, we generate an .nrrd image for the new mask. However, initially my original and mask images are .png files. Would this affect the feature results I am getting now?

**Comment by JoostJM** [comment]
You don't have to save `newMask`, you can use the SimpleITK object directly as input to the feature extractor. My suggestion was to load the main image (not the mask) outside the loop as well, otherwise it is read from disk by the extractor in every iteration of the components in your mask.

As to storage format, I strongly urge you not to use long format. Besides the fact that this is often stored as a color image (both more space inefficient and more difficult to work with), it also does not contain any geometric information, such as spacing, direction and origin. This information is important when extracting features, especially when extracting shape features. Finally, I think png does not support storing 3D masks, as it's a format for storing 2D images.

**Comment by JoostJM** [comment]
Since you orginal data is already in png, no additional information is lost when storing as either png or nrrd, but the same considerations apply. What type of image are you using? Did you convert it to png from some other format?

**Comment by mozdag** [comment]
Yes, I loaded the main image outside the loop.

And the data (original and mask) is given as .png to me. I didn't convert them. So, I believe they won't have shape-3D features.

But new mask we're generating here is .nrrd

**Comment by jvanlunenburg** [comment]
> This information is important when extracting features, especially when extracting shape features.

On that subject, is there documentation available on what metadata is needed/used _specifically_. E.g. if I have an aggressively anonymized DICOM image and I want to check if the relevant tags (for sitk->pyradiomics) haven't been wiped.

**Comment by fedorov** [comment]
> what metadata is needed/used specifically

pyradiomics needs only the metadata about the geometry of the image. In fact, it is not pyradiomics that needs it, but the [tools that you would use to convert from DICOM into volumetric format](https://pyradiomics.readthedocs.io/en/latest/faq.html?highlight=dicom#what-file-types-are-supported-by-pyradiomics-for-input-image-and-mask) will need it (e.g., dcm2niix): `ImagePositionPatient`, `PixelSpacing` and `ImageOrientationPatient`. There is typically no reason for de-identification tools to touch those attributes.

**Comment by jvanlunenburg** [comment]
> In fact, it is not [only] pyradiomics that needs it, but the tools that you would use to convert [...] will need it.

In my workflow I am trying to avoid file converting by creating a valid sitk object from a loaded dicom object. So I hand-pick the properties that seem relevant to shape, and hope I haven't left any out.

**Comment by fedorov** [comment]
DICOM has so many "gotchas" and cross-vendor peculiarities, that we strongly advice against re-writing the code to reconstruct DICOM volume. I understand your desire to avoid intermediate format, but unfortunately I am not sure there is python library as robust as dcm2niix or plastimatch to use directly from your code.

Note that if you load the original DICOM object, you don't need to hand-pick anything - you will use the attributes to reconstruct the geometry and make a SITK image object with the valid geometry. pyradiomics does not need anything from DICOM once you have that image object.

**Comment by jvanlunenburg** [comment]
So loading a DICOM directly with SITK _might_ work, but maybe not for everyone, which is why you recommend dcm2niix?

> Note that if you load the original DICOM object, you don't need to hand-pick anything - you will use the attributes to reconstruct the geometry and make a SITK image object with the valid geometry.

That's assuming I'm loading with SITK. But in my case I have a MATLAB dicom object I need to cast into a python SITK image object. The pixel array is easy, the metadata is tricky.

**Comment by fedorov** [comment]
I don't have hands-on experience with the MATLAB dicom objects and robustness of MATLAB DICOM reader, so I don't think I can meaningfully comment on this.

**Comment by mozdag** [comment]
> You need to specify which label to extract for.
> 
> ```
> Nodules = []
> for l in range(1, ccif.GetObjectCount() + 1):
>   Nodules.append(extractor.execute(image, newMask, label=l))
> ```
> 
> Note: it is perhaps best to first also load the image, so the image isn't reread from the disk every time, reducing the IO time. The result of `sitk.ReadImage(ImageName)` is a valid input for the `extractor.execute` image parameter.


One more question here please: This code writes the features of cells in some order? What is the default order, and how do I manipulate it? I want to visualize what features belong to what cell. Thank you in advance.
