### ISSUE TITLE
No handlers could be found for logger "pykwalify.core"

### ISSUE THREAD

**Issue by sunhuaiqiang** [Radiomics/pyradiomics#304]
this error happens with version 1.2.0.post82+g0a0eb4f

**Comment by JoostJM** [comment]
@sunhuaiqiang, in what mode did you use PyRadiomics? Interactive in python, from the commandline or via the slicerRadiomics plugin in 3D slicer?

I have tried locally, but was unable to reproduce your error.

**Comment by sunhuaiqiang** [comment]
I used it in command line on data that can be successfully extracted with
form version of PyRadiomics
