### ISSUE TITLE
Json format error

### ISSUE THREAD

**Issue by salimkanoun** [Radiomics/pyradiomics#314]
Hi there, i'm a new user discovering pyradiomics.
I think I picked up one bug.
For my test I get an error in NGTDM calculation (which I didn't investigate yet).

However, the problem is when I ask the results as JSON format and I got this : 
"original_ngtdm_Complexity": 0.0, "original_ngtdm_Contrast": NaN

I have an error when I try to parse this JSON because NaN is a string so it should be **"**NaN**"** (with "") in the JSON file.

Best regards,

Salim

**Comment by JoostJM** [comment]
@salimkanoun In this case, the NaN specifies and out-of-range float value, and is not intended as string. This is indeed not in strict compliance with JSON, but still uses the JavaScript equivalents.

If it is serialized as string, it could still provide difficulties during deserialization. An alternative can be that we add a commandline argument to filter out NaN results.

**Comment by salimkanoun** [comment]
Dear Joost, 

Thank for your answer, your argument sounds good, or maybe filtering it by default and add a message to say that some values have been filtered.
