### ISSUE TITLE
google analytics for readthedocs?

### ISSUE THREAD

**Issue by pieper** [Radiomics/pyradiomics#324]
From what I can tell we should be able to turn on google analytics for our documentation which would make a nice proxy for usage.  It looks like the analytics script is loaded with the page but we don't include the snippet needed to enable it.

Do we already have an ID to use?

**Comment by JoostJM** [comment]
No idea, I don't at least. Can you look into this?

**Comment by pieper** [comment]
@JoostJM I have a google analytics tracking ID and my readthedocs.org account is "pieper" but I believe you need to add me as an owner or admin to the readthedocs pyradiomics project so that I can access the admin page as described here:

http://docs.readthedocs.io/en/latest/guides/google-analytics.html

Or if you prefer I can just email you the tracking code.

**Comment by fedorov** [comment]
I thought there is some google analytics asset already set up for the radiomics.io - we should check with @ahmedhosny - I think it would be better if all radiomics.io assets are tracked under the same organization.

**Comment by pieper** [comment]
Good point - actually here is the code from the radiomics.io page source: UA-53741901-12

However is a maintainer on pyradiomics for readthedocs should paste this into the box in the advanced settings page (and maybe add me as a maintainer while you are at it).

@ahmedhosny maybe you can also invite add us all to the corresponding google analytics project.

**Comment by ahmedhosny** [comment]
yup I have one - it is currently using my personal google analytics account and has been tracking it since early this year.
I did set up a radiomics.io@gmail.com account where the radiomics videos are hosted on [youtube](https://www.youtube.com/channel/UC3ra_-ycAHxvIP7l21J5d0g?&ab_channel=radiomics.io) (yet another credentials we have to keep track of). We can potentially move everything there, unless we can come up with a better solution

**Comment by pieper** [comment]
I think it's fine for it to be "owned" by your gmail account @ahmedhosny since you should be able to add users on a per-ga-account basis.

I wanted to get this set up sooner rather than later as we will want more data when we are working on renewal proposals.

**Comment by ahmedhosny** [comment]
sounds good, I made a new property in my personal account for pyradiomics docs. The ID is UA-53741901-14

We can move properties (with all history) between gmail accounts in the future if needed.

**Comment by JoostJM** [comment]
I added @ahmedhosny's ID to the readthedocs.

**Comment by ahmedhosny** [comment]
Confirming the docs property tracking is working! DM me if you need the data. Radiomics.io is doing well - will need to update it soon. 
Closing this for now.
![screencapture-analytics-google-analytics-web-1513008798283](https://user-images.githubusercontent.com/8398334/33841011-85007862-de64-11e7-8696-2f804be101d2.png)
