### ISSUE TITLE
Center of mass ? 

### ISSUE THREAD

**Issue by salimkanoun** [Radiomics/pyradiomics#325]
Hi there,

In some radiomics publications, some authors tried to quantify tumor distribution in a whole body imaging modality (as PET/CT). (see solidity here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4699494/)

Even if I think we don't have real consensual measurement for this approach, I wonder if pyRadiomics could provide the center of mass of each ROI as in a x/y/z coordinate (for example in a first order or shape feature).

If the output provides the x/y/z coordinate of the center of mass and the voxel size (if available in the image header) it will give to the user all needed raw data to make inter-tumor distance calculations and to explore this approach for whole body tumor distribution quantification.

Best regards,

Salim

**Comment by JoostJM** [comment]
Providing a center of mass shouldn't be too difficult. I'd include it in the `general_info` section though, as for all other feature values only a scalar is returned (and thus easily fed into an analysis pipeline).

As to the x, y, z coordinates of this center of mass, the easiest approach would be to calculate this on the original (non-resampled) mask and return the real-world coordinates. This saves the trouble of having to incorporate voxel size (which is already returned in the `general_info` section as `ImageSpacing`)

**Comment by salimkanoun** [comment]
Sounds perfect ! I forget about the general info, that is a really good idea.

Thank you so much !

**Comment by JoostJM** [comment]
see #420
