### ISSUE TITLE
How can I set the parameters for heterogeneous-dimension MRIs ?

### ISSUE THREAD

**Issue by Daniel-Fei** [Radiomics/pyradiomics#326]
Hi!
I'm trying to use the application PyRadiomics to analyze MR images of brain tumors.

The MRIs were obtained using different scanners over several years. I checked a few of these MRI scans, and found that in-plance dimentions were different (such as 512*512, 256*256, ...), and slice thickness were also different (such as 5mm, 7mm, 3mm, ...).

My plan is to segment the tumors using ITK-SNAP, and then analyse the 3D texture/shape features using PyRadiomics. 

Given the heterogeneous dimensions of these MRI scans, could you please recommend optimal parameters that I can use in PyRadiomics?
(I've checked your example examples\exampleSettings\exampleMR_NoResampling.yaml, but I am not sure if it will work for my case).

Any advice would be appreciated!!

**Comment by JoostJM** [comment]
I posted a [response](https://groups.google.com/forum/#!topic/pyradiomics/dqv4iHkZaBY) on the google groups.
