### ISSUE TITLE
Can we get image and mask filename ?

### ISSUE THREAD

**Issue by salimkanoun** [Radiomics/pyradiomics#328]
Hi there,

In the json output there are the general infos which store several data about the settings used etc (which is really nice).
It also implement mask and image Hash but it doesn't store the original name file of mask and Image used to generate result.

It is possible to add the full path string of original Image/Mask file ? It will be usefull to secure the link data to it's source file.

Happy end of year celebration to  pyRadiomics team & community !

Salim

**Comment by JoostJM** [comment]
Sure, wouldn't take too much effort. I'll add it to the single mode script and not the general info though, as this information is already part of the output when working in batch mode (they are required columns in the input, which is copied to the output).

**Comment by JoostJM** [comment]
Fixed by #347
