### ISSUE TITLE
Making PyRadiomics available on PyPi

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#335]

**Comment by jcfr** [comment]
👍 I will  work on this next week

**Comment by JoostJM** [comment]
@jcfr, did you manage to look at this issue?

**Comment by JoostJM** [comment]
Fixed in #394 and checked in the new 2.0,0 release

**Comment by sdoken** [comment]
What about conda? Or should I open a new issue for that?

**Comment by JoostJM** [comment]
In conda you can also pip install packages

**Comment by sdoken** [comment]
You mean that one can use pip alongside with conda? Sure but that is not the same thing, I don't think?. (If I am understanding you correctly) Thanks for your reply.
