### ISSUE TITLE
Should we include the version of SimpleITK, PyWavelet and Numpy in the output?

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#341]
Currently, the precise PyRadiomics version is included in the output as a general_info feature. Should we also include the versions of the 3rd-party packages that are used in feature calculation to enable user to exactly reproduce the extraction?

**Comment by pieper** [comment]
If people are building their own PyRadiomics versions that may be built against different versions of the dependencies, then yes, it would be good to capture the provenance.  It certainly can't hurt.

**Comment by jcfr** [comment]
> 3rd-party packages that are used in feature calculation to enable user to exactly reproduce the extraction

While writing the exact version of all dependences is helpful, I think encouraging people to use the containerized (e.g docker) PyRadiomics is a reliable approach enabling reproducible results.

In that case, the metadata of the container could be displayed.
