### ISSUE TITLE
error: pyradiomics installation on windows 2008 r2 

### ISSUE THREAD

**Issue by zhenweishi** [Radiomics/pyradiomics#344]
Dear Developers
#330 #
There is an error when I install pyradiomics  on windows 2008 r2. After I run python setup.py install, error below:

running install
running bdist_egg
running egg_info
creating pyradiomics.egg-info
writing requirements to pyradiomics.egg-info\r
writing pyradiomics.egg-info\PKG-INFO
writing top-level names to pyradiomics.egg-inf
writing dependency_links to pyradiomics.egg-in
writing entry points to pyradiomics.egg-info\e
writing manifest file 'pyradiomics.egg-info\SO
reading manifest file 'pyradiomics.egg-info\SO
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CONTRIBUTING
warning: no previously-included files found ma
sv'
warning: no previously-included files found ma
eaturesDiff.csv'
warning: no previously-included files matching
ry '*'
warning: no previously-included files matching
 '*'
writing manifest file 'pyradiomics.egg-info\SO
installing library code to build\bdist.win-amd
running install_lib
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\radiomics
copying radiomics\base.py -> build\lib.win-amd
copying radiomics\featureextractor.py -> build
copying radiomics\firstorder.py -> build\lib.w
copying radiomics\generalinfo.py -> build\lib.
copying radiomics\glcm.py -> build\lib.win-amd
copying radiomics\gldm.py -> build\lib.win-amd
copying radiomics\glrlm.py -> build\lib.win-am
copying radiomics\glszm.py -> build\lib.win-am
copying radiomics\imageoperations.py -> build\
copying radiomics\ngtdm.py -> build\lib.win-am
copying radiomics\shape.py -> build\lib.win-am
copying radiomics\_version.py -> build\lib.win
copying radiomics\__init__.py -> build\lib.win
creating build\lib.win-amd64-2.7\radiomics\scr
copying radiomics\scripts\commandline.py -> bu
ripts
copying radiomics\scripts\commandlinebatch.py
cs\scripts
copying radiomics\scripts\__init__.py -> build
ts
creating build\lib.win-amd64-2.7\radiomics\sch
copying radiomics\schemas\paramSchema.yaml ->
schemas
copying radiomics\schemas\schemaFuncs.py -> bu
hemas
UPDATING build\lib.win-amd64-2.7\radiomics/_ve
set build\lib.win-amd64-2.7\radiomics/_version
running build_ext
building 'radiomics._cmatrices' extension
error: INCLUDE environment variable is empty

**Comment by JoostJM** [comment]
This appears to be a problem during compiling the C Extensions. Do you have a Visual Studio Compiler setup on that machine?

If not, please check out this [FAQ topic](http://pyradiomics.readthedocs.io/en/latest/faq.html#during-setup-python-is-unable-to-compile-the-c-extensions)

**Comment by JoostJM** [comment]
@zhenweishi, did you manage to fix your issue?
