### ISSUE TITLE
GLCM only works for images with at leat 256 bins

### ISSUE THREAD

**Issue by alimid** [Radiomics/pyradiomics#350]
I am trying to use GLCM for 3D-images of tumors. If I have at last 256 bins (8-bit image) everything works. If my images have less bins than this (for example 128, or 64 or 16), the GLCM-features only returns the value 0 or 1 for most of my images. Why is this?

**Comment by JoostJM** [comment]
It is possible your mask shows a flat region. Re-run pyradiomics with a log file and log level set to DEBUG. In the log you can then see how many graylevels are defined for the GLCM.

**Comment by alimid** [comment]
Thank you JoostJM, with the log and DEBUG, I was able to see what was wrong. I had not changed the settings for binwidth, so the automatic binwidth of 25 made my ROI flat.
