### ISSUE TITLE
featureextractor not found

### ISSUE THREAD

**Issue by JoostJM** [Radiomics/pyradiomics#352]
Asked by @CristianIzquierdoLitii in #303 
> Hi,
>
>  I've been trying to run some test.py to check radiomics is working but it keep saying that it cannot import 
>  featureextractor from radiomics. Is there anyone having the same issue?
>
> Thanks in advance

**Comment by JoostJM** [comment]
I readded this comment here as it is most likely unrelated to #303.

I have some questions related to your issue:
- What system (OS) do you use?
- Which version of python?
- Which version of pyradiomics?
- Did you receive any issue/warnings/errors during installation?
- If you go to the folder where pyradiomics is installed, do you see a file `featureextractor.py` there?

To find the location of the imported module `radiomics`, run: 
```
import radiomics
print(radiomics.__file__)
```

**Comment by CristianIzquierdoLitii** [comment]
I'm sorry for posting in the wrong thread.

- Mac OS
- 2.7 
- The last one. Cloned the git repository today.
- No warnings or issues. It worked perfectly and I checked again and again if there was something not installed.
- Yes, the file is in there. Same happens with firstorder.py

That's why I asked, because it seems like a pretty easy issue, but it doesn't work.

Thanks for asking so fast!!

**Comment by CristianIzquierdoLitii** [comment]
I already typed the : 

import radiomics
print(radiomics.__file__)

and the answer is: 

User.../myname.../anaconda2/lib/python2.7/site-package/radiomics/__init__.pyc

**Comment by JoostJM** [comment]
Can you run the following and post the response?

```
import traceback
try:
  import radiomics.featureextractor
except:
  print(traceback.format_exc())
```

**Comment by CristianIzquierdoLitii** [comment]
Yes sure,

Here you are. 

 poblenou-136-114:Desktop cristianizquierdo$ python TestRadiomics2.py
Traceback (most recent call last):
  File "TestRadiomics2.py", line 20, in <module>
      import radiomics.featureextractor
ImportError: No module named featureextractor

poblenou-136-114:Desktop cristianizquierdo$

**Comment by JoostJM** [comment]
I have to say, it's a strange error. It appears that you're able to find the package, but that the package in turn is unable to find the correct module. What is the output of the following? (Lists all the modules it can find in `radiomics`)

```
import pkgutil
import os
import radiomics

print(os.listdir(os.path.dirname(radiomics.__file__)))

for _, mod, _ in pkgutil.iter_modules([os.path.dirname(__file__)]):
  print mod
```

**Comment by CristianIzquierdoLitii** [comment]
I'm sorry for bothering you.
The output is this: 

poblenou-136-114:Desktop cristianizquierdo$ python TestRadiomics2.py
['features.pyc', '__init__.py', 'features.py', '__init__.pyc']

and the list of all the modules in radiomics is: 

poblenou-136-114:~ cristianizquierdo$ cd pyradiomics/
poblenou-136-114:pyradiomics cristianizquierdo$ cd radiomics/
poblenou-136-114:radiomics cristianizquierdo$ ls
__init__.py		firstorder.py		imageoperations.py
_cmatrices.so		generalinfo.py		ngtdm.py
_cshape.so		glcm.py			schemas
_version.py		gldm.py			scripts
base.py			glrlm.py		shape.py
featureextractor.py	glszm.py		src

hope it can help you.

**Comment by JoostJM** [comment]
No problem.
Ah. I assume the `['features.pyc', 'init.py', 'features.py', '__init__.pyc']` is the output from `print(os.listdir(os.path.dirname(radiomics.__file__)))`? It appears that it is finding some other folder/module called radiomics, which has a totally different structure.

The ls you posted under that is the listing in the source package, which is not found by your python interpreter.

To fix this you can check the following:
1) Check if pyradiomics is findable. For that, got to you site-packages folder and check if there is an `easyinstall.pth` file. The location to the radiomics folder in `~/pyradiomics/radiomics` should be in there somewhere.
2) [Most important step] remove the other package `radiomics`, as this prevents the python interpreter from finding your installation of PyRadiomics.

If for some reason you still need the other `radiomics` package, you can install a [virtual environment](http://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv) and install pyradiomics after activating that environment.

**Comment by CristianIzquierdoLitii** [comment]
Ok, I found the `easy-install.pth`, the folder radiomics in the site-package and I did a ls in that folder and it seems there is no featureextractor.py in there:

`poblenou-136-114:site-packages cristianizquierdo$ cd radiomics
poblenou-136-114:radiomics cristianizquierdo$ ls
__init__.py	__init__.pyc	features.py	features.pyc`

Should I delete this folder? Will it work?

**Comment by CristianIzquierdoLitii** [comment]
Ok JoostJM

Fixed!!!

Thank you for your help!!!!

**Comment by wiluber19** [comment]
I have the same problem, but I don't found easyinstall.pth in radiomics folder.



print(os.listdir(os.path.dirname(radiomics.__file__)))
['__pycache__', 'features.py', '__init__.py']

for _, mod, _ in pkgutil.iter_modules([os.path.dirname(radiomics.__file__)]):
  print (mod)
  
features


could you advise me please

**Comment by JoostJM** [comment]
@wiluber19, As you can see from the comments above, this is caused by the fact that you have installed some other package called radiomics. Uninstall (`pip uninstall radiomics`, `pip uninstall pyradiomics`) the other package and reinstall PyRadiomics.

**Comment by wiluber19** [comment]
@JoostJM You’re a lifesaver.

**Comment by aislam388** [comment]
Hi, i am confused which folder to delete fro this problem? I have a clone folder of pyradiomics at my desktop and then in site-packages, i have a folder name radiomics and another named radiomics-0.1.dist-info.
In the radiomics folder of site-packages, I have a folder named__pychache__ and two file named __init__ and features. 
Which folder should i delete?

**Comment by JoostJM** [comment]
@aislam388 Did you copy-paste the pyradiomics folder into site-packages?
Best practice is to use `pip`, the python package manager.
You should have a site-packages without any radiomics, pyradiomics or like-named folders, and then intall pyradiomics by `pip install pyradiomics` or running `python setup.py install` from the clone of the pyradiomics repository (which can be located anywhere on your system).

Clearing all the (py)radiomics folder should preferably be done using `pip uninstall`, but if that fails, you can also manually delete them from the site-packages folder.

**Comment by aislam388** [comment]
@JoostJM  I did not copy-paste the pyradiomics folder into site-packages. And I installed it through pip as well as cloned the folder from github. I was also having error of C  extensions thats why i cloned it.
Now I have removed (py)radiomics folders from sike packages through pip uninstall. and i have run python setup.py install from cloned pyradiomics folder through anaconda prompt, but it says  error: microsoft visual c++ 14.0 is required.

**Comment by JoostJM** [comment]
@aislam388, what was the C error you got that your pip installation did not work?

As to the error you're getting: If you build PyRadiomics from source, you'll need the correct C-compiler setup so Python can find it. See [here](https://pyradiomics.readthedocs.io/en/latest/faq.html#during-setup-python-is-unable-to-compile-the-c-extensions).

**Comment by FaizanJvd** [comment]
I am getting error in importing models of radiomics :
         code =  from radiomics import featureextractor
        error =  cannot import name 'getFeatureClasses' from 'radiomics' (/usr/local/lib/python3.7/dist- 
                              packages/radiomics/__init__.py)
Kindly Guide.
using Colab.
Python version = 3.7.12
Pyradiomics version =  v 3.0.1
Libraray is installed with PIP is  well:
                            ['__pycache__', 'featureextractor.py', 'generalinfo.py', 'schemas', 'imageoperations.py', 'base.py', '_version.py', 'ngtdm.py', 'scripts', 'glrlm.py', '_cmatrices.cpython-37m-x86_64-linux-gnu.so', 'glszm.py', 'firstorder.py', 'gldm.py', '__init__.py', 'shape.py', 'shape2D.py', '_cshape.cpython-37m-x86_64-linux-gnu.so', 'glcm.py']
                            _cmatrices
                            _cshape
                            _version
                            base
                            featureextractor
                            firstorder
                            generalinfo
                            glcm
                            gldm
                            glrlm
                            glszm
                            imageoperations
                            ngtdm
                            scripts
                            shape
                            shape2D

**Comment by JoostJM** [comment]
Can you past a full stack trace (as suggested in my first comment?)
