### ISSUE TITLE
How can I convert DCM to NRRD with SimpleITK?

### ISSUE THREAD

**Issue by QiChen2014** [Radiomics/pyradiomics#361]
Hi everyone!
I'm trying to use the PyRadiomics to extract features from a serious DICOM images(2D), and I have two questions.
1.  As the document says, PyRadiomics can not process the DCM image directly, so I translate my data from DCM to NRRD by simpleITK, code like this:
`
  reader = sitk.ImageSeriesReader() 

    dicomReader = reader.GetGDCMSeriesFileNames(inputPath) #input is the DCM file path 

    reader.SetFileNames(dicomReader) 

    dicoms = reader.Execute() 

    sitk.WriteImage(dicoms, fileName) #fileName like "brain.nrrd"
`
Then,  I input a NRRD file as img, which generated by above codes, and a nii(NIFTI) file as mask, it works! But I'm not sure if this is feasible, what do you think?
2. How to determine the appropriate parameters to extract good features? Do you have any good suggestions?

Thanks a lot.
Qi Chen

**Comment by fedorov** [comment]
The approach you use may not result in geometrically ordered slices. You can use existing tools, such as [dcm2niix](https://github.com/rordenlab/dcm2niix) or [plastimatch](http://plastimatch.org/) to convert a DICOM series into a volume. Prior to running the converter, you will need to ensure the input DICOM folder contains just one series, and that series is a scalar volume.

**Comment by QiChen2014** [comment]
@fedorov Thank you for your reply. Can PyRadiomics process nii directly?

**Comment by fedorov** [comment]
Yes

**Comment by QiChen2014** [comment]
OK，I got it. Thanks again!

**Comment by huawenqing** [comment]
> Yes



> The approach you use may not result in geometrically ordered slices. You can use existing tools, such as [dcm2niix](https://github.com/rordenlab/dcm2niix) or [plastimatch](http://plastimatch.org/) to convert a DICOM series into a volume. Prior to running the converter, you will need to ensure the input DICOM folder contains just one series, and that series is a scalar volume.

After I used dcm2nii to convert a DICOM series into a nii volume, the direction changed and led to mismatch between the image and segmentation. My image is DICOM and segmentation is Nifti, I want to process them in Nii format. Why the problem happened?

**Comment by fedorov** [comment]
The only way to investigate this is to look at the dataset where you observed this issue.

**Comment by zexllin** [comment]
how to use stk-snap to make mask

**Comment by JoostJM** [comment]
@zexllin, I myself use 3D Slicer for segmenting images, so I'm afraid I can't really help you with ITK snap. Still, [here](http://www.itksnap.org/pmwiki/pmwiki.php?n=Train.RSNA2017) is a tutorial for ITK snap that may be able to answer your question.
