### ISSUE TITLE
How can I calculate the features with label whose format  is "txt" 

### ISSUE THREAD

**Issue by shercklo** [Radiomics/pyradiomics#362]
I use the code based on the "helloFeatureClass.pynb",which is the example of pyradiomics
code:
/*
 from radiomics import firstorder, glcm, imageoperations, shape, glrlm, glszm, getTestCase,featureextractor
from __future__ import print_function
from PIL import Image
import six
import sys, os
import radiomics
import SimpleITK as sitk
import pydicom
import numpy as np
import logging
import radiomics

image_origin = sitk.ReadImage("F:\\xk\\BC_SAMPLE\\metastasis\\10422801\\ST0\\A-Mono 40 kev\\IMG62")
image = sitk.GetArrayFromImage(image_origin)
image = image[0,:,:]
mask = np.loadtxt(open('F:\\xk\\BC_SAMPLE\\metastasis\\10422801\\ROItxt\\LN-A-M\\062.txt'),delimiter=",",skiprows=0)  #import the data 

firstOrderFeatures = firstorder.RadiomicsFirstOrder(image_origin,mask)
firstOrderFeatures.enableAllFeatures()  # On the feature class level, all features are disabled by default.
firstOrderFeatures.calculateFeatures()
for (key,val) in six.iteritems(firstOrderFeatures.featureValues):
  print("\t%s: %s" % (key, val))
*/

And the warning is " 'numpy.ndarray' object has no attribute 'GetPixelIDValue'' 
If I don't import txt file as numpy , how can I do with it?
Thanks a lot in advance.

**Comment by JoostJM** [comment]
@shercklo, Why do you not use the feature extractor class? It is possible to use the feature classes directly, but then a lot of checking and preprocessing is skipped.

Second, as stated in the documentation, images and masks in pyradiomics are processed in the `SimpleITK.Image` format, as this class also contains the transformation matrix to real-world coordinates.

try this

```
from radiomics import featureextractor
from __future__ import print_function
from PIL import Image
import six
import sys, os
import radiomics
import SimpleITK as sitk
import pydicom
import numpy as np
import logging
import radiomics

image_origin = sitk.ReadImage("F:\xk\BC_SAMPLE\metastasis\10422801\ST0\A-Mono 40 kev\IMG62")
image = sitk.GetArrayFromImage(image_origin)
mask = np.loadtxt(open('F:\xk\BC_SAMPLE\metastasis\10422801\ROItxt\LN-A-M\062.txt'),delimiter=",",skiprows=0) #import the data

ma_arr = image
ma_arr[0, :, :] = mask

ma = sitk.GetImageFromArray(ma_arr)
ma.CopyInformation(image_origin)

extractor = featureextractor.RadiomicsFeaturesExtractor()

extractor.enableAllFeatures()  # Enables all feature classes
# Alternative: only first order
#extractor.disableAllFeatures  # All features enabled by default
#extractor.enableFeatureClassByName('firstorder')

featureVector = extractor.execute(image_origin, ma)

for (key,val) in six.iteritems(featureVector ):
  print("\t%s: %s" % (key, val))
```

**Comment by shercklo** [comment]
Thanks a lot! 
I'll have a try.

**Comment by shercklo** [comment]
It works! Thank you once again!
I think I shoud have read the docs and examples more carefully :)

**Comment by shercklo** [comment]
It works! Thank you once again!
I think I shoud have read the docs and examples more carefully :)

**Comment by shercklo** [comment]
Oh, I come here again.
I meet another problems. Now I don't want just 2-D Features and want to get  the 3-D Features 
The Image Series directory is  'F:\xk\BC_SAMPLE\metastasis\10422801\ST0\A-Mono 40 kev' , the mask Series directory is 'F:\xk\BC_SAMPLE\metastasis\10422801\ROItxt\LN-A-M\', how can I do this withoud 3-d slicer but just pyradiomics?

**Comment by JoostJM** [comment]
PyRadiomics default is 3D features. To get 2D features, either give a maskfile with only 1 slice masked, or enable forced-2D extraction by setting `force2D = True`.
