### ISSUE TITLE
Error in NGTDM documentation

### ISSUE THREAD

**Issue by Icron1** [Radiomics/pyradiomics#365]
Hi!

Thanks a lot for Pyradiomics software!

Just a message in order to highlight is a small mistake in the NGTDM documentation.
In the example matrix, it's written: 

s3=|3−**14**/5|+|3−18/5|+|3−20/8|+|3−5/3|=**2.63**

Whereas the truth is:

s3=|3−**12**/5|+|3−18/5|+|3−20/8|+|3−5/3|=**3.03**

And so in the corresponding NGTDM.
It's quite nothing but it might be confusing.

Sincerely,
Loïc

**Comment by JoostJM** [comment]
Fixed by ea9a6ce6efd2ebfd4229e8070f72eef382c590bd
