### ISSUE TITLE
Could not load required package "skimage", cannot implement filter LBP 2D

### ISSUE THREAD

**Issue by QiChen2014** [Radiomics/pyradiomics#370]
@JoostJM I have tried to install "skimage", then I got this issue:
` Please install the `scikit-image` package (instead of `skimage`)`
I installed the "scikit-image" instead, but I still get the same warning, can you tell me how to solve this problem?
![qq 20180409140122](https://user-images.githubusercontent.com/9483041/38481696-aad212a6-3bfe-11e8-9119-af15d5d628bb.png)
Thanks for your great work!

**Comment by JoostJM** [comment]
It is possible it's still finding the first installed version of `skimage`, did you uninstall it?

**Comment by QiChen2014** [comment]
yes, when I excute "pip uninstall skimage", then I get "Cannot uninstall requirement skimage, not installed"

**Comment by QiChen2014** [comment]
@JoostJM I can import and trace it, like this:

![qq 20180409163406](https://user-images.githubusercontent.com/9483041/38487815-033e5bce-3c14-11e8-90bf-2000cf1b6111.png)
should I delete the skimage package manually and reinstall scikit-image again?

**Comment by QiChen2014** [comment]
@JoostJM I found the reason, I haven't install "matplotlib", thank you very much.
