### ISSUE TITLE
pep8speaks integration

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#376]
I noticed pydicom is using https://pep8speaks.com/, which is quite nice -- see example in https://github.com/pydicom/pydicom/pull/627#issuecomment-383238169. 

@JoostJM should we add it to pyradiomics as well?

**Comment by jcfr** [comment]
:+1: 

For reference:
* https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.pep8speaks.yml
* https://blog.kitware.com/how-to-improve-software-quality-in-open-source-projects-part-iii-code-coverage-documentation-and-style/

**Comment by jcfr** [comment]
That said, setting up flake8 as a step within CircleCI is also useful. For example, see https://github.com/NeurodataWithoutBorders/pynwb/blob/f749097718cf344f4c95de7771a1ef523f26762f/.circleci/config.yml#L84-L92

**Comment by fedorov** [comment]
The advantage of pep8speaks is that it is basically instantaneous, while CircleCI can take some time to schedule.

**Comment by jcfr** [comment]
> The advantage of pep8speaks is that it is basically instantaneous

Setting up a flake8 job as a part of a CircleCI 2.0 workflow will also report quasi-instantaneous results. For example, in [this project](https://circleci.com/gh/NeurodataWithoutBorders/pynwb/3905) results come back in 23s.


FYI, we are now getting rid of pep8speaks, it is using the less complete tool `pep8` and doesn't accept the same parameter as `flake8`.

**Comment by fedorov** [comment]
> CircleCI 2.0 workflow will also report quasi-instantaneous results

Are you saying it will run this analysis without waiting for the job to start?

**Comment by JoostJM** [comment]
@fedorov, @jcfr,

For the release of 2.0, I updated the CircleCI to use workflows. I did not split-out the flake8 tests, but I did transfer the testing of the notebooks to a separate job. This moves the slowest part of the testing to a moment after all the other tests have run, including flake8. 

The testing which includes flake8 now returns in less than a minute, which is fast enough for me.
