### ISSUE TITLE
extracting 2D ndarray image features

### ISSUE THREAD

**Issue by kdk411** [Radiomics/pyradiomics#377]
Hello,

I am trying to extract 2D image features, but I am getting no outputs at the moment.

I also tried to do the same thing as #316 , but for some reason it does not work for me...

my image data is in the shape of [n_slice, x_dim, y_dim, view] where view is the 3 direction views: axial, sagittal, and coronal. And Yes, it is a 2D images in ndarray at the moment.

Below is my code:

```
train_dir = '/train/'
val_dir = '/val/'

os.chdir(train_dir)
train_img = np.load('train_img.npy')
train_mask = np.load('train_mask.npy')

extractor = featureextractor.RadiomicsFeaturesExtractor()

extractor.disableAllFeatures()

extractor.enableFeatureClassByName('firstorder')

views = ['x','y','z']
n_slice = train_img.shape[0]
data_spacing = [1,1]

for slice_ind in range(n_slice):

	for view_ind in range(len(views)):
		# pick slice and view
		img_slice = train_img[slice_ind,:,:,view_ind]
		mask_slice = train_mask[slice_ind,:,:,view_ind]

		#convert numpy array into sitk

		sitk_img = sitk.GetImageFromArray(img_slice)
                sitk_img = sitk.JoinSeries(sitk_img)
		sitk_img.SetSpacing((float(data_spacing[0]), float(data_spacing[1]) ))
		sitk_mask = sitk.GetImageFromArray(mask_slice)
		sitk_mask = sitk.JoinSeries(sitk_mask)
                sitk_mask.SetSpacing((float(data_spacing[0]), float(data_spacing[1]) ))

		print(extractor.execute(sitk_img, sitk_mask))
```

And the output is something like the following:

```
OrderedDict()
OrderedDict()
OrderedDict()
```
And those OrderedDict() are all empty... Any thoughts?

**Comment by kdk411** [comment]
In fact, I have 3D MRI images in nii files... but I am just trying to extract largest section in 3 views, then compute features.

Maybe,  the better way is to extract/convert 3D nii file into 3 largest section 2D images in the format of sitk... but idk what would be the safest way to do so since idk what RadiomicsFeaturesExtractor looks for in terms of information (pixel spacing is definitely there... but what about other info?)

**Comment by JoostJM** [comment]
@kdk411, i'm not sure your conversion works entirely as you expect. You can test this by inserting `print(sitk_img)` and `print(sitk_mask)`. 
Also, you can try to set the spacing prior to `JoinSeries()`, as after this call, the image has 3 dimensions, and you'd need to specify this 3rd dimension.

However, I still recommend to use the original 3D images, as this also takes the slice thickness into account. PyRadiomics actively uses the spacing (in all 3 dimensions, so including slice thickness) in it's calculation of shape features and when you enable `weightingNorm`, which applies a distance-based normalization on GLCM and GLRLM. 

Additionally, direction is also taken into account when checking the overlap between image and mask (i.e. pyradiomics supports masks in different coordinate systems, in such a case, the mask needs to be resampled to the image coordinate space by enabling `correctMask`).

**Comment by kdk411** [comment]
@JoostJM 
Oh, I did include the thickness in my code, but somehow did not get copied over here properly.

Currently, both the mages and masks are already pre-processed such that they are co-registered and interpolated into 1x1x1 mm. Also the intensities of the images are normalized such that every voxel intensity is subtracted by the mean value of normal region,  then divided by interquartile intensity of normal region... 

I did what you suggested. Set spacing prior to `JoinSeiries()`. Also, I ensured the depth dimension too, yet I am not getting anything out as the result.

I did print out the img and mask:

Print image:
```
In [3]: print(sitk_img)
Image (0x1543510)
  RTTI typeinfo:   itk::Image<double, 3u>
  Reference Count: 1
  Modified Time: 1093
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1085
  UpdateMTime: 1092
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix:
1 0 0
0 1 0
0 0 1

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (0x35deba0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 1090
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 0x35f2240
      Container manages memory: true
      Size: 20164
      Capacity: 20164
```

Print mask:

```
In [10]: print(sitk_mask)
Image (0x1592e10)
  RTTI typeinfo:   itk::Image<double, 3u>
  Reference Count: 1
  Modified Time: 1296
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1288
  UpdateMTime: 1295
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [142, 142, 1]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix:
1 0 0
0 1 0
0 0 1

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (0x35da700)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 1293
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 0x37dcaa0
      Container manages memory: true
      Size: 20164
      Capacity: 20164

```

Any suggestions? Would it be helpful if I share the data?

**Comment by JoostJM** [comment]
@kdk411, your mask has datatype double, which is not allowed by SimpleITK. Run this:
`mask = sitk.Cast(mask, sitk.sitkInt32)`

Additionally, did you enable logging when running this code? If I'm correct, such an error is logged by PyRadiomics.

**Comment by kdk411** [comment]
Awesome! It is working now.

And yes, I should have run the logger to debug. 

Just for the future audience who wants to extract 2D features from ndarray files, this is what I did:

```
# assume 2D images here
img_slice = np.load('img.npy')
mask_slice = np.load('mask.npy')

# assume pixel size is in 1x1 mm. I am gonna assume 3rd dimension which is the depth is also 1 mm so that it is isotropic
data_spacing = [1,1,1]

sitk_img = sitk.GetImageFromArray(img_slice)
sitk_img.SetSpacing((float(data_spacing[0]), float(data_spacing[1]), float(data_spacing[2]) ))
sitk_img = sitk.JoinSeries(sitk_img)

sitk_mask = sitk.GetImageFromArray(mask_slice)
sitk_mask.SetSpacing((float(data_spacing[0]), float(data_spacing[1]), float(data_spacing[2]) ))
sitk_mask = sitk.JoinSeries(sitk_mask)
sitk_mask = sitk.Cast(sitk_mask, sitk.sitkInt32) # MAKE SURE IT IS CASTED IN INT

# prepare the settings and load
params = 'settings.yaml'
extractor = featureextractor.RadiomicsFeaturesExtractor(params)

#extract 
features = {}
features = extractor.execute(sitk_img, sitk_mask)
```
