### ISSUE TITLE
Does this method include the image registration, and how should I set the parameter.

### ISSUE THREAD

**Issue by liyiming5956** [Radiomics/pyradiomics#380]
First of all, thank you very much for providing us so wonderful algorithm. I have a question about the method.
    When I use this method, I found that the tumor volume I calculated may be wrong in some circumstances. Since the volume of big tumor is less than a small tumor estimated by naked eyes. I wonder that whether this method calculate absolute tumor volume or relative tumor volume.
    If this method calculate absolute tumor volume, the phenomenon I found should not be exist.
    If this method calculate relative tumor volume, I suppose that I should register a batch of images together and how can I register them through the settings?
    If this method calculate relative tumor volume, then the volume between batches can not be compared together. 
    I hope you could give me some instructions, thank you very much!!

**Comment by JoostJM** [comment]
PyRadiomics does not include any registration algorithm, but does use the real-world values in certain cases, among them, volume. Volume is calculated as the number of voxels * the size a single voxel in mm3.

It is possible that something went wrong in the conversion, causing the spacing to be incorrect. you can verify this by reading the image using SimpleITK and printing the details:  `print(sitk.ReadImage('path/to/image.nrrd')`

**Comment by liyiming5956** [comment]
Thank you very much for your answer. 
    I have another question.
    If I have many patients, and I would divide them into training and validation cohorts. Should I divide them into two batches first and then extract radiomic features from each batch, or regard them as one batch and extract radiomic features?
    Because there is a dilemma: If I regard all patients as one  batch, and I choose the normalization being 'TRUE', then the validation cohort is not so independent, since the data in the validation cohort have participated in the normalization and influenced the training cohort. If I regard the patients as two batches, then can I just simply compare the features between the two batches, or I need use some method (e.g. batch normalization algorithm in gene analysis) the get rid of the batch effect. I wonder which strategy would you choose.
    Thank you very much!

**Comment by JoostJM** [comment]
@liyiming5956 Normalization is done on a per-volume basis, so you're strategy doesn't matter. Furthermore, splitting in validation and test cohorts is necessary for your analysis, but not for the feature extraction (no matter what model you make, it will be based on the same features, so you need to use the same configuration for extraction in both the training and validation cohort).
