### ISSUE TITLE
install wrong C Matrices

### ISSUE THREAD

**Issue by Sophile** [Radiomics/pyradiomics#384]
what should I do:
C Matrices not loaded correctly, cannot calculate matrices in C
For computational reasons, this feature is only implemented in C. Enable C extensions to calculate this feature.
For computational reasons, this feature is only implemented in C. Enable C extensions to calculate this feature.
For computational reasons, this feature is only implemented in C. Enable C extensions to calculate this feature.
For computational reasons, this feature is only implemented in C. Enable C extensions to calculate this feature.
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

Thanks a  million

**Comment by JoostJM** [comment]
How do you run PyRadiomics? Did installation work without errors?

This issue is that it can find/load the C compiled extensions. These are built during installation.

**Comment by JoostJM** [comment]
Linked to #385
