### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Sophile** [Radiomics/pyradiomics#385]
Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
 I have downloaded visual Studio 2017,so what to do next?

**Comment by JoostJM** [comment]
you can add the following in your path variables (redirects the request for VS 14.0 to your VS 15.0)

`VS140COMNTOOLS = %VS150COMNTOOLS%`

For this, check if there is a path entry called VS150COMNTOOLS and that it points to your VS 15.0 installation.

alternatively, you can also try to install the visual studio 14.0 redistributable (contains build tools, free to install). You can find this [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by Sophile** [comment]
thank you, I have installed  the visual studio 14.0，but it still shows that  "Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools" is there any steps after install the VS 14.0?

**Comment by Sophile** [comment]
@JoostJM thank you, I have installed the visual studio 14.0，but it still shows that "Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools" is there any steps after install the VS 14.0?

**Comment by JoostJM** [comment]
It should show up in your environment variables (otherwise Python can't find it). Is there an entry called `VS140COMNTOOLS`?

**Comment by Sophile** [comment]
@JoostJM no,how to add it?

**Comment by JoostJM** [comment]
You can add an environment variable manually. I myself use Visual Studio 2015, and in my case this variable points to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`, In your case, first check if you have such a folder.

If that does not work you can also try to see if pointing it to your VS 15.0 works (This works by setting the value to `%VS150COMNTOOLS%`, effectively redirecting it), or by googling it, maybe there are more people with the same problem (quite likely, as this is not a PyRadiomics-specific error, but rather linked to getting Python to be able to compile extensions, which is needed to install PyRadiomics).

**Comment by Sophile** [comment]
@JoostJM thank you.  it shows nothing, I have intalled the VS 14.0 ,but it has  nothing changed, seems that I did not install it..

**Comment by Sophile** [comment]
hello，does pyradiomics has a .whl file which can solve the problem of installing VS 14.0? there is a similar question ,https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat，there is a answer that uses .whl deal with VS 14.0 is required. @JoostJM

**Comment by jcfr** [comment]
Hi Sophile,

As soon the integration of scikit-build is done, we will publish wheel.
This should happen in the next week or two.

Thanks
Jc

**Comment by JoostJM** [comment]
@jcfr, the integration of scikit-build cannot happen before the next release (which includes [a fix](https://github.com/scikit-build/scikit-build/pull/287) for the inclusion of package data). Do you have an ETA for the new scikit-build release?

**Comment by Sophile** [comment]
@jcfr really？How can we know when it is published？

**Comment by JoostJM** [comment]
@Sophile, I just made the 2.0.0 release. PyRadiomics is now pip installable (and doesn't need compiling for python 2.7, 3.4, 3.5 and 3.6).

If you have such a python version, run:

`python -m pip install pyradiomics`

**Comment by darkmanAmazigh** [comment]
This problem still exist on python 3.7.1,
i have added %VS140COMNTOOLS% to path variable

**Comment by JoostJM** [comment]
@darkmanAmazigh, Correct, PyRadiomics is currently pre-built for Python 2.7, 3.4, 3.5 and 3.6. Other versions just download the source code and attempt to compile locally, which requires your compiler to be setup correctly
