### ISSUE TITLE
trimesh package in docker container for LBP3D filter

### ISSUE THREAD

**Issue by cpwardell** [Radiomics/pyradiomics#388]
First; thanks for writing this software, it's excellent and much appreciated.

If you attempt to use the LBP3D filter in the docker image downloaded using:
`docker pull radiomics/pyradiomics`

You get the following error:
`Could not load required package "scipy" or "trimesh", cannot implement filter LBP 3D`

I solved it by installing the trimesh package using pip. 
`pip install trimesh`

Please update your dockerfile/dockerhub.

**Comment by JoostJM** [comment]
@cpwardell, thanks for the tip! I'll update the dockerfile to fix this issue.

**Comment by jonasharad** [comment]
I would be grateful for quick feedback on whether the solution above: "I solved it by installing the trimesh package using pip.
pip install trimesh" also refers to pyradiomics integrated into 3D Slicer? Cheers, Marko

Please update your dockerfile/dockerhub.
