### ISSUE TITLE
Cannot open shared notebook on github

### ISSUE THREAD

**Issue by kimrants** [Radiomics/pyradiomics#396]
I have issues opening your notebooks here on github. It always says "oops, something went wrong. Reload?". 

I don't have this issue with other notebooks so unsure why the problem exists.

**Comment by fedorov** [comment]
Probably there are some constraints on how big notebooks can be to be rendered on github.

You should try checking out the repository, and opening the notebook directly instead.

**Comment by jcfr** [comment]
Instead, consider using nbviewer. For example:

http://nbviewer.jupyter.org/github/Radiomics/pyradiomics/blob/master/notebooks/FeatureVisualization.ipynb
