### ISSUE TITLE
Using bincounts gives an exception: "setting an array element with a sequence"?

### ISSUE THREAD

**Issue by aydindemircioglu** [Radiomics/pyradiomics#399]
maybe i'm doing something utterly wrong here-- but if i use bincount instead of binwidth, i get an error. it seems to stem from numpy, the code in imageoperations.py reads:

```
    binEdges = numpy.histogram(parameterMatrix[parameterMatrixCoordinates], bincount)
    [...]
    parameterMatrix[parameterMatrixCoordinates] = numpy.digitize(parameterMatrix[parameterMatrixCoordinates], binEdges)
```

but at least in the latest numpy lib numpy.histogram gives back a tuple with the transformed values and the binedges-- so i get an error of the form "setting an array element with a sequence."
when modifying the above line to 
```_, binEdges = numpy.histogram(parameterMatrix[parameterMatrixCoordinates], bincount)```
the code seems to run without an error (and hopefully work as intended).

is it just my peculiar setup or is this a bug?

**Comment by andbiz** [comment]
Hi!
I get this error, too.
I confirm that the proposed fix is working.

pyradiomics=2.0.0
numpy=1.14.5

**Comment by fedorov** [comment]
Thanks for pointing this out! I committed a fix, let us know if you continue experiencing problems.
