### ISSUE TITLE
Normalization & Resampling

### ISSUE THREAD

**Issue by wenlongming** [Radiomics/pyradiomics#401]
Hi!
There are three questions i want to ask about the setting section in Parameters File.
(1) What is the difference between normalizeScale: 100 and normalizeScale: 1 during normalization?
and How does normalizeScale relate to bin width (in Image discretization) ?

(2) I have a MRI dataset which the slice thickness is in the range of (0.9mm, 3.2mm), most are 2.0mm and 2.2mm. And the image spacing of each sample is most like (0.78125mm, 0.78125mm, 3.0mm), (0.5859mm, 0.5859mm, 2.0mm) and many other different values, which the x, y are always same but z in not. 
So may you please tell me how to set resampledPixelSpacing ?  Can I set it as [0.7, 0.7, 2] or should I ensure x, y and z have the same value, set it like [0.5, 0.5, 0.5] or [1.0, 1.0, 1.0] ?

Thanks !

**Comment by JoostJM** [comment]
> (1) What is the difference between normalizeScale: 100 and normalizeScale: 1 during normalization?
and How does normalizeScale relate to bin width (in Image discretization) ?

During normalization, each voxel intensity is shifted by subtracting the mean, and then divided by the standard deviation. Generally, this yields and image with intensities approximately in the range [-3, 3] (the actual range in the ROI is a contained herein, this represents the range in the whole image). This resultant value is then multiplied by the `normalizeScale`, e.g. a value of 100 here will result in an approximate range of [-300, 300].
The relation to binWidth is a close one, as these resultant values after the normalization are those used during gray value discretization. So for example, if you use a binwidth of 10 or so, and a normalize scale of 1, you're likely to end up with only flat regions (little or no ROI will have a larger range than 10).
Generally, I advise to look at what kind of ranges are present in your dataset, and choose a binwidth accordingly (and stick with it). In case of normalizeScale 100, a bin width of 5 showed some good results in our work.

> (2) I have a MRI dataset which the slice thickness is in the range of (0.9mm, 3.2mm), most are 2.0mm and 2.2mm. And the image spacing of each sample is most like (0.78125mm, 0.78125mm, 3.0mm), (0.5859mm, 0.5859mm, 2.0mm) and many other different values, which the x, y are always same but z in not.
So may you please tell me how to set resampledPixelSpacing ? Can I set it as [0.7, 0.7, 2] or should I ensure x, y and z have the same value, set it like [0.5, 0.5, 0.5] or [1.0, 1.0, 1.0] ?

This depends a bit on your approach to the feature extraction. Regardless, I think it is a good idea to perform at least some form of resampling, as the voxel size does influence the resultant feature value. (by forcing all to a comon size, you remove this effect). As to the precise settings, I generally advise to keep the size isotropic in the dimensions you're analysing, i.e. if only 2D (in-plane), ensure isotropic spacing in-plane, if 3D, ensure isotropic spacing both in- and out-of-plane. This has to do with the definition of "neighboring" voxels, which is assumed to be the same for all angles (as seen in infinity norm).

As to the values, I think it best to have a sort of compromise, i.e. choose a value where not too much information is lost, and not too much information is interpolated. in your case: don't go below 1.0 mm out-of-plane, a resampling of [2, 2, 2] or even [3, 3, 3] is not bad. Remember that larger voxels are not necessarily bad, it just means you're looking a more coarse texture... too small voxels can be accompanied by a lot of noise. However, too large voxels may also pose a problem in small lesions, as then the number of voxels can be quite low and one might wonder how valid texture features are when they are based on just 3 or so voxels...

**Comment by wenlongming** [comment]
I'm very appreciate for your patience and enthusiasm!

(1) For Q1: The original_firstorder_Range of my dataset is (192,2438), with the mean of 663. So I set the binWidth of 20 and nomalizeScale of 100 to analyze. But for the derived images, they have different ranges, for example the log-sigma-2-0-mm-3D_firstorder_Range is (110,1447), with the mean of 393, and the log-sigma-3-0-mm-3D_firstorder_Range is (102,1353), with the mean of 330. 
So, do I need to reset the binWidth every time for original and derived images? Or should I only need to set a fixed binWidth for my dataset just according to the original_firstorder_Range.

(2) For Q2: Thank you very much for your advice. I'm about to take a resampling of [2, 2, 2] with the sigma of [2.0, 2.5, 3.0, 4.0, 5.0] and a resampling of [3, 3, 3] with the sigma of [3.0, 4.0, 5.0].

Thanks!

**Comment by JoostJM** [comment]
> So, do I need to reset the binWidth every time for original and derived images? Or should I only need to set a fixed binWidth for my dataset just according to the original_firstorder_Range.

I do not know, you can try to set 1 bin width and see if it works in your analysis. If not, you can specify custom binwidths for each filter. See [here](http://pyradiomics.readthedocs.io/en/latest/customization.html#parameter-file) for more info.
