### ISSUE TITLE
use of GetSpacing in extraction of shape features

### ISSUE THREAD

**Issue by epapavas** [Radiomics/pyradiomics#403]
I was looking at the definition of the class _RadiomicsShape_ and concerning the use of simpleITK's GetSpacing I noticed the following:

_self.pixelSpacing = numpy.array(self.inputImage.GetSpacing()[::-1])_

Doesn't  GetSpacing return a vector in the format x,y,z? So when reversing it we should get
 _z, y, x=self.pixelSpacing_
However, in the code we have:
_z, x, y = self.pixelSpacing_

Thank you in advance for the feedback

**Comment by fedorov** [comment]
I think you are right. I am going to fix this, but note that this has no effect on the calculations - the only place where those variables are used is calculation of the volume, thus the inconsistency is inconsequential.

Thanks for reporting this anyway!
