### ISSUE TITLE
conda channel?

### ISSUE THREAD

**Issue by mlewis1973** [Radiomics/pyradiomics#412]
anyone know of a conda channel with pyRadiomics? I don't like to mix pip and conda

**Comment by JoostJM** [comment]
To my knowledge, PyRadiomics builds are currently not published to Anaconda.
We only recently integrated automatic uploading to PyPi and have not yet investigated also uploading to Anaconda, but it is certainly an interesting idea.

As to the current version on PyPi (2.0), please not it contains a bug preventing the fixed bin count option from working. I will try to make a new release shortly that includes the fix already present in the current master.

**Comment by helderc** [comment]
I'm looking forward for this too...

**Comment by JoostJM** [comment]
@helderc, as you can see in the referenced PR (#422), PyRadiomics is now available on anaconda. However, we've been experiencing some difficulties with the build for several distributions (mainly Linux, some Windows).

You can find the channel [here](https://anaconda.org/Radiomics/pyradiomics).
In the meantime, it is possible to pip-install PyRadiomics in anaconda.

**Comment by helderc** [comment]
@JoostJM thank you.

Just to reference for others, I have installed pyradiomics (in Windows 10) via pip but all other dependencies (except pykwalify) were installed via conda...

Another thing is, the latest pyradiomics version use Python 3.6, if someone want to use it with Python 3.7 will need to install C++ compiler to build it from the source.
