### ISSUE TITLE
Extract features from 3D images which only have one slice got segmented(2D ROI).

### ISSUE THREAD

**Issue by Williamongh** [Radiomics/pyradiomics#415]
Hi, thank you for your work, it has helps me a lot.
Here is a question.
Now I want to extract features from 3D images which only have one slice got segmented. That‘s to say, both the original image and the mask image are 3D nrrd files, but the ROI is 2D, lying on one of the slices.
I am not sure how should I set the `param.yaml`. 
Should I set `force2D `with `True`? I got confused because of the comment of `force2D`:
`If input ROI is already a 2D ROI, features are automatically extracted in 2D.`
What's the difference between the feature values if I set the `force2D` or not?
Thank you!

**Comment by JoostJM** [comment]
You don't have to do anything specific for that case, features are automatically calculated in 2D (as only one slice is available). Setting "force2D" has no effect in this case.

**Comment by JoostJM** [comment]
Ah yes, I'm sorry. If you enable force2D, Wavelet filter only filters in 2D, Which means that only 4 (LL, HL, LH and HH) are generated, whereas in 3D (LLL, LLH, LHL, LHH, HLL, HLH, HHL, HHH) = 8 images are derived. It is up to you to decide if you want to enable wavelet filtering in 2D or 3D, as both cases are in general valid, even with just your single slice segmentation.

**Comment by Williamongh** [comment]
Thank you. I understand it now.
