### ISSUE TITLE
Pyradiomics

### ISSUE THREAD

**Issue by Franci051088** [Radiomics/pyradiomics#429]
How can I compile and install pyradiomics in a home folder?

**Comment by JoostJM** [comment]
Detailed instruction for installing and compiling pyradiomics are provided in the [documentation](https://pyradiomics.readthedocs.io/en/latest/installation.html).

**Comment by Franci051088** [comment]
I have write this instruction:
pyton setup.py install  --install-base '/home/admin01/Documents/pyradiomics-master/mypyrad'

But is gives:
Unknown distribution option: :'long_description_content_type'
and errore: install-base or install-platbase supplied, but installation scheme is incomplete.

**Comment by JoostJM** [comment]
The unknown distribution you can ignore. Why do you want to install pyradiomics to that specific folder? If you want to work within the repository, but need the extensions, try `python setup.py develop`. Or, if you just want to build the extensions `python setup.py build_ext`
