### ISSUE TITLE
BUG: complex eigenvalues

### ISSUE THREAD

**Issue by aydindemircioglu** [Radiomics/pyradiomics#432]
after having suffered from the memory bug, i updated to the latest version.
now i get (actually very often) an error in the new MCC routine:

FAILED: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/radiomics/base.py", line 289, in _calculateFeatures
    yield True, feature, getattr(self, 'get%sFeatureValue' % feature)()
  File "/usr/local/lib/python3.6/dist-packages/radiomics/glcm.py", line 645, in getMCCFeatureValue
    return float(numpy.mean(MCC))  # 2nd highest eigenvalue
  File "/usr/lib/python3.6/warnings.py", line 101, in _showwarnmsg
    _showwarnmsg_impl(msg)
  File "/usr/lib/python3.6/warnings.py", line 28, in _showwarnmsg_impl
    text = _formatwarnmsg(msg)
  File "/usr/lib/python3.6/warnings.py", line 116, in _formatwarnmsg
    msg.filename, msg.lineno, line=msg.line)
TypeError: itkFormatWarning() got an unexpected keyword argument 'line'

please ignore the itk warning, itk somehow converts the error into a simple warning
(which is good for my purposes).

the error stems from "complex" eigenvalues like this:

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
[0.83068385+0.j 0.84445242+0.j 0.82106292+0.j 0.85131019+0.j
 0.88005621+0.j 0.84830903+0.j 0.82005425+0.j 0.83611365+0.j
 0.81718384+0.j 0.89172707+0.j 0.91807285+0.j 0.88467971+0.j
 0.93459838+0.j]

**Comment by JoostJM** [comment]
@aydindemircioglu, which specific version of PyRadiomics are you using? On what OS and which version of Python?

in e15f169 I added a force cast to float (to retain only the real part) to try to prevent this error. I will update if to your fix if necessary.

**Comment by aydindemircioglu** [comment]
i downloaded the latest version this morning, so its 2.1.0.
the fix with float is there 

maybe this is what happens:
your implicit convert-to-float issues a warning (when i use it directly on an ipython shell) like this:

/usr/local/bin/ipython3:1: ComplexWarning: Casting complex values to real discards the imaginary part

i think my itk-whatever-setup reacts harshly to such warnings, and it might raise an exception.
so i think, if you are pretty sure the matrix should be real and the complex parts are numeric
instabilities/errors, then you should cast it explicitly to real and not implicitly to float. 
at least it did fix my errors.

**Comment by JoostJM** [comment]
@aydindemircioglu, That's correct, I've seen SimpleITK complaining about warnings more often, though I haven't figured out why.

As to the warning, I was able to reproduce, and will update PyRadiomics to implement your fix.

**Comment by JoostJM** [comment]
Fixed in 6542181

**Comment by MeldaYeghia** [comment]
I'm getting complex numbers returned from the following 5 shape features: Elongation, Flatness, MinorAxisLength, MajorAxisLength, and LeastAxisLength. No negative eigenvalues warning so it should be complex eigenvalues. I'm retaining the real part for analysis.

Same values retrieved using pyradiomics v 3.0.1, 3.0 and 2.2.0

**Comment by Zhack47** [comment]
The same error is occuring for me, ubuntu 24.04, pyradiomics v3.0.1

**Comment by panos1998** [comment]
I have also one error regarding getMCC


`  File "/home/p/petridisp/anaconda3/envs/pyradio-env/lib/python3.9/site-packages/radiomics/base.py", line 238, in _calculateFeatures
    yield True, feature, getattr(self, 'get%sFeatureValue' % feature)()
  File "/home/p/petridisp/anaconda3/envs/pyradio-env/lib/python3.9/site-packages/radiomics/glcm.py", line 648, in getMCCFeatureValue
    Q_eigenValue = numpy.linalg.eigvals(Q.transpose((0, 3, 1, 2)))
  File "<__array_function__ internals>", line 200, in eigvals
  File "/home/p/petridisp/anaconda3/envs/pyradio-env/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1043, in eigvals
    _assert_finite(a)
  File "/home/p/petridisp/anaconda3/envs/pyradio-env/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 195, in _assert_finite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.LinAlgError: Array must not contain infs or NaNs`
