### ISSUE TITLE
[improvement?] MCC memory issue?

### ISSUE THREAD

**Issue by aydindemircioglu** [Radiomics/pyradiomics#436]
i often have multiple series for a patient and do compute the features in parallel.
the machine has 24 cores and 256gb of memory installed.
yet, i had to go back to 1 core because i get this error message when i have too many threads in parallel
(even 4 seems to be too much in my case)

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
FAILED: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/radiomics/base.py", line 289, in _calculateFeatures
    yield True, feature, getattr(self, 'get%sFeatureValue' % feature)()
  File "/usr/local/lib/python3.6/dist-packages/radiomics/glcm.py", line 633, in getMCCFeatureValue
    Q = numpy.sum((self.P_glcm[:, None, :, :] * self.P_glcm[None, :, :, :]) /  # slice: i, j, k, d
MemoryError

i think i have too many bins, using no normalization and binWidth = 10. 
yet, i dont recall having such memory problems with lower binWidth values in the past,
but maybe thats a wrong impression on my side.

am i right to guess that the matrix multiplication is too heavy on the memory side in this case,
as the glcm matrix seems to be simply too large?
if so, is there any trick to make the matrix multiplication less memory-intensive? 

and anyone else seeing this kind of problem?

**Comment by JoostJM** [comment]
@aydindemircioglu, This is due to the MCC feature in GLCM that was recently implemented. If you disable that feature by specifying the other GLCM features. 

I will investigate this further.

**Comment by aydindemircioglu** [comment]
ok, thanks for investigating! 

i just see that it even crashes with just one cpu, so it takes more than 256gb. 
should be more reasonable with my parameters :/

**Comment by JoostJM** [comment]
I implemented a fix in 167888b (part of the current master), which computes the intermediary matrix Q in a for loop. This is a slightly slower computation, but much less memory intensive.

**Comment by JoostJM** [comment]
@aydindemircioglu, If it still crashes, try to check how large the GLCMs are that are created (visible when logging with DEBUG level). It is possible that your chosen binwidth results in Ng that is too large (seeing as GLCM shape is Ng x Ng x Na, with Na usually being 13 in 3D).

**Comment by aydindemircioglu** [comment]
cool, thanks for the really quick fix, i will try it out, but probably only on monday.

**Comment by aydindemircioglu** [comment]
thanks again, it helps!
(though i then get the error "Number of elements in GLCM would overflow index variable! Increase bin width or decrease number of angles to prevent this error.", as said, the binwidth chosen is overkill)

**Comment by JoostJM** [comment]
@aydindemircioglu If you get that error, your binwidth is much too small. This error occurs only when Ng x Ng x Na exceeds the int32 max (2147483647). If this is the case, the probabilities in your GLCM will be most likely close to 0, causing unstable features.

**Comment by ylmzkaan** [comment]
I have a 3D image with dimensions [491 341 258] (After cropping). I set the binwidth to different values from 25 (166 bins) to 500 (10 bins) but I still get "RuntimeError: Number of elements in GLCM would overflow index variable! Increase bin width or decrease number of angles to prevent this error."

I make my calculations for distances = [[1]]. It looks like it results in 13 different angles by default. Although I need only 3 orthogonal angles along z,y and x axes, I couldn't find a way to set them using the generateAngles().

Any ideas about the Runtime error and the angles?
