### ISSUE TITLE
How to specify angles?

### ISSUE THREAD

**Issue by lishen** [Radiomics/pyradiomics#438]
GLCM and GLRLM features require the specification of angles. Although they are mentioned in the documentation but I don't see how to specify the angles through arguments. Can anyone clarify?

BTW, is there any way to specify run length in terms of the number of pixels?

**Comment by JoostJM** [comment]
@lishen, angles required for the computation of GLCM, GLRLM and the other texture classes are generated automatically inside the C extension (using functions [`get_angle_count()`](https://github.com/Radiomics/pyradiomics/blob/master/radiomics/src/cmatrices.c#L513) and [`build_angles()`](https://github.com/Radiomics/pyradiomics/blob/master/radiomics/src/cmatrices.c#L557).

For the case of GLCM and GLRLM they are then also returned from the C extension, as the are potentially needed for the matrix weighting.

However, it is not possible to set these angles manually. What would be your usecase? Some papers use features calculated from the GLCM for a specific angle. However, this is not rotation-invariant and therefore not implemented in PyRadiomics.

Finally, if you want to use PyRadiomics to generate angles for you, you can invoke `generate_angles()` (it is also used [here](https://github.com/Radiomics/pyradiomics/blob/master/radiomics/base.py#L129)).

As to the question regarding the run length. What do you mean? The j-axis of the GLRLM specifies the length of the run in number of pixels.

For several feature classes, including GLCM and NGTDM, it is possible to consider neighbours at larger distances, using `distances` parameter. However, for GLRLM, only distance 1 is considered, as distance 2 would yield a 'downsampled' version of the same matrix (i.e. odd run lengths are rounded down to the nearest even run length).

**Comment by lishen** [comment]
@JoostJM, maybe because I'm from a different field, I found it a bit odd that the angles are automatically determined. Some package, such as skimage, allows us to specify a list of angles in [greycomatrix](http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.greycomatrix). 

For run length, I'm just wondering if the length of the run can be restricted to a certain number, such as 11.

**Comment by JoostJM** [comment]
@lishen No, the runs go on as long as they can. Limiting them to a specific number would be counter intuitive, as then no distinction can be made between images with runs of 11 and images with runs longer than 11 (where the latter is more homogeneous than the former, and a distinction is important).

**Comment by alabamagan** [comment]
Sorry for digging up an old issue, I get that pyradiomics tries to stick to rotational invariant features and therefore restrict these setting for GLCM  and also use 'uniform' mode for LBP for robustness. But then I can't understand the rational behind wavelet transform filter banks because they are essentially directional wavelets. So my question is whether there are more documentations regarding how pyradiomics uses pywavelet to ensures/improve the directional consistency of the wavelet's features?

**Comment by dsantiago** [comment]
It can be numpy outdated. Try `pip install -U numpy`.
