### ISSUE TITLE
A big problem about dcm files!

### ISSUE THREAD

**Issue by lisherlock** [Radiomics/pyradiomics#439]
Hi,
    Now i have one 16 bit dcm file as data. At the same time, i have one 8 bit dcm file as mask. The mask range is 0 and 255. But when i run the batchprogress, it has error!  I wanna know why! Thanks!

Here is the error log:
    (ROIBounds, imageNode.GetSize()))
ValueError: Bounding box of ROI is larger than image space:
        ROI bounds (x, y, z image coordinate space) ((434.02968808817445, 679.1564771258519, 83.925), (448.50783004240776, 694.9508138031973, 84.925))
        Image Size (512, 512, 1)

Thanks!

**Comment by KirklandSignatur3** [comment]
I have this same issue, were you able to find a fix?
