### ISSUE TITLE
Mesh Volume is in voxels not mm^3

### ISSUE THREAD

**Issue by isabellafw** [Radiomics/pyradiomics#455]
Hi. According to the documentation, the Mesh Volume should be in mm^3. However, when calculating the Mesh Volume it has similar values to the Voxel Volume, so is not in mm^3 -- how can we get the volume in mm^3?

Thanks for any help.

**Comment by JoostJM** [comment]
Both Mesh Volume and Voxel Volume yield a value in mm^3. The difference is in how the volume is approximated: Voxel Volume calculates the volume by multiplying the volume of a voxel (x * y * z spacing) with the number of voxels in the ROI, whereas Mesh Volume approximates the Volume by calculating the volume contained by the surface mesh (generated using marching cubes).

**Comment by isabellafw** [comment]
Thanks for that, would like to double check because I have also calculated volume in the software Lifex which calculates both in cm^3 and voxels -- that's how I noticed the volumes from pyradiomics were most similar to Lifex's volume in voxels (even after unit conversion), which is quite different from Lifex's volume in cm^3.

**Comment by JoostJM** [comment]
If you're interested in the number of voxels in the ROI, check feature VoxelNum (part of the diagnostic features)

**Comment by isabellafw** [comment]
Those values are very similar to mesh/voxel volume - is this usual?

**Comment by JoostJM** [comment]
@isabellafw, can you also share the values for `diagnostics_Mask-resegmented_PixelSpacing`?

And to be sure, which version of PyRadiomics are you using?

**Comment by JoostJM** [comment]
@isabellafw, I checked the code for a potential bug, but everything looks fine. I suspect your pixel spacing is 1x1x1 mm (thereby causing the volume of a voxel to be 1 mm^3 and the value of voxel volume to be equal to the number of voxels in the ROI).

If your dataset is not supposed to have a spacing of 1x1x1, please describe any steps of converting the data, as well as the settings passed to PyRadiomics. It is possible that there was some error there, causing the spacing to be ignored (e.g. as often in the case of non-equidistant slices) or in case the image was generated from a numpy array, and no geometry info was provided (spacing is the 1x1x1 by default).

**Comment by isabellafw** [comment]
@JoostJM Thank you - yes the spacing was not set when getting the image from a numpy array, now the problem is solved and the values make more sense. Very much appreciate your help to find the problem!
