### ISSUE TITLE
Creating a mask for specific region of interest inside an image

### ISSUE THREAD

**Issue by abhinandanbatra** [Radiomics/pyradiomics#460]
Hi, 
I have some images of legs where I have drawn ROI around specific muscles. Is there a way that I can create a mask of that specific region using  pyradiomics. Will appreciate help.

Thank you very much
Abhi

**Comment by JoostJM** [comment]
@abhinandanbatra, PyRadiomics is not intended for the creation of ROIs, only analyzing regions defined using masks. If you want to create segmentations, you can checkout [3D Slicer](www.slicer.org) or similar programs (3D Slicer also has a radiomics module that allows applying PyRadiomics directly from Slicer)
