### ISSUE TITLE
Feature Category

### ISSUE THREAD

**Issue by MonishSannathi** [Radiomics/pyradiomics#462]
Hi
Im trying to understand,under which radiomic feature class, does diagnostics_Image-original_Mean and diagnostics_Image-original_Maximum comes?

**Comment by JoostJM** [comment]
@MonishSannathi None, these are diagnostic 'features', which are generated in the `generalinfo.py` module. They are intended to provide additional information regarding the extraction process, which may be helpful when debugging or reproducing extractions.
