### ISSUE TITLE
Bin width for normalized image

### ISSUE THREAD

**Issue by GSEL9** [Radiomics/pyradiomics#464]
Hi.

If a choose to both normalize and discretize my image with a fixed bin width, do I need to calculate the bin width from the normalized version of my image, or will my bin width (from the original image) be transformed to the corresponding width of a normalized image inside PyRadiomics?

Thanks for great software!

Best,
Severin

**Comment by JoostJM** [comment]
@GSEL9 you need to adjust the bin width to the intensities you expect after normalization, it is not transformed automatically, as this would mean it is transformed slightly different for each image, defeating the purpose of using a fixed bin width (i.e. ensuring the contrast represented by the discretized image is the same).
