### ISSUE TITLE
Graphically visualize filtered images (2D case)

### ISSUE THREAD

**Issue by tommydino93** [Radiomics/pyradiomics#468]
Hi again @JoostJM !

I have another question. Is there a way to visualize my wavelet-filtered and exponential-filtered images or bounding box? (preferably with matplotlib, but also with sitk would be fine). Something like:

```
for decompositionImage, decompositionName, inputKwargs in imageoperations.getWaveletImage(cropped_image, cropped_mask):
      plt.subplot(221), plt.imshow(waveletLL)
      plt.subplot(222), plt.imshow(waveletLH)
      plt.subplot(223), plt.imshow(waveletHL)
      plt.subplot(224), plt.imshow(waveletHH)

for expImage, expName, inputKwargs in imageoperations.getExponentialImage(cropped_image, cropped_mask):
      plt.imshow(expImage)
```

Ideally, I would like to have a subplot with the original image first, then the wavelets (HL, HH, LH, LL) images and then the exponential one.

Thank you again very much in advance :)
Tommaso

**Comment by JoostJM** [comment]
Hi @tommydino93, it should relatively easy to do so. Your start is there, though I think you'd need to convert to arrays before showing. Check out the notebooks, the featureVisualisation one contains code on viewing an image (though not the filtered one in that case, but that shouldn't matter).

**Comment by tommydino93** [comment]
Thanks a lot @JoostJM !!
In the end, I managed to find a way this morning. We can use the `sitk.Show` function. In this way sitk invokes ImageJ that opens up the images. Like this:

```
... # some code before

cropped_image, cropped_mask = imageoperations.cropToTumorMask(image, mask, bb)  # compute cropped image with bounding box

sitk.Show(cropped_image, title="cropped original")  # title sets the title to the ImageJ window

for decompositionImage, decompositionName, inputKwargs in Wavelet_Image.getWaveletImage_modified(cropped_image, cropped_mask):
      sitk.Show(decompositionImage, title=decompositionName)  # title sets the title to the ImageJ window

for expImage, expName, inputKwargs in imageoperations.getExponentialImage(cropped_image, cropped_mask):
      sitk.Show(expImage, title=expName)
```

**Comment by JoostJM** [comment]
@tommydino93 Indeed, that is the other option ;-) I did not mention it as you said preferably with matplotlib
