### ISSUE TITLE
How to visualize the radiomics features?

### ISSUE THREAD

**Issue by huawenqing** [Radiomics/pyradiomics#470]
![default](https://user-images.githubusercontent.com/28468626/53473330-15b97000-3aa5-11e9-8377-7c00352b677f.PNG)
Like this.

**Comment by huawenqing** [comment]
> I'm afraid I don't understand your question, can you please elaborate?

I want to make a schematic diagram of radiomics features like the these three pictures, but I don't know how to do, is there some softwares can transform features into pictures.

**Comment by JoostJM** [comment]
@huawenqing, If you extract segment based features, you only get a scalar value per feature/ROI. The examples you show are schematic images depicting the process of calculation and do not represent feature values. If you want to graphically visualize your extraced features for a dataset, consider using a heatmap.

If you extract features voxelwise, you can use 3D slicer to visualize them (I'd recommend using np.nan as `initValue`, as these are treated as "transparent" by 3D Slicer
