### ISSUE TITLE
Does the new version in the github still cant't be installed by pip?

### ISSUE THREAD

**Issue by johnyanchen** [Radiomics/pyradiomics#471]
The new version of the source code in the current github  support 2 dimensional shape feature,but we install the version of pyradiomics  installed by pip is sitll 2.1.2 which doesn't support 2 dimensional shape feature.If the only method to install the latest vertsion is install by source?Thanks

**Comment by johnyanchen** [comment]
The 2d shape feature can't be found in the document,by in the source code ,there is Shape2d.py

**Comment by JoostJM** [comment]
@johnyanchen, that is correct. On pip, only the official releases of PyRadiomics can be installed, and the shape2D features were only added after that last release (next release is coming soon though).

**Comment by JoostJM** [comment]
documentation for the shape2D features have now also been added to the online documentation
