### ISSUE TITLE
How can I set the parameters to get only the wavelet-LLH or wavelet-HLL features?

### ISSUE THREAD

**Issue by JianJuly** [Radiomics/pyradiomics#473]
In the case i do not need all the eight decompositions.
now i have my code as:
```
extractor.disableAllImageTypes()
extractor.enableImageTypeByName('Wavelet', customArgs={'binWidth': 10})
```

**Comment by JoostJM** [comment]
Currently, this is not possible in PyRadiomics. For each level, all decompositions are returned, the approximation is only returned for the last level.
