### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument

### ISSUE THREAD

**Issue by Saffron123456789** [Radiomics/pyradiomics#474]
I can run the example, helloRadiomicsWithSetting.py, in a new project, but when I put it in Django frame, it stuck in "featureVector = extractor.execute(imageName, maskName)", and return "libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument".
And I check the imageName and maskName which are right.
I debug it, and I found it will be break at this [line](https://github.com/Radiomics/pyradiomics/blob/8df119073d648add9ecd28be68d63d2564599523/radiomics/imageoperations.py#L399)
Could you give me any suggestion about that? Thanks!

**Comment by JoostJM** [comment]
We've had similar issues earlier, hence the fact that it is in a try-except construction.
However, in your case, it seems to fail with a different error.
Can you try to update the code on [these lines](https://github.com/Radiomics/pyradiomics/blob/8df119073d648add9ecd28be68d63d2564599523/radiomics/imageoperations.py#L392-L393)

to
```
  ijkMinBounds = tuple(numpy.maximum(ijkMinBounds, 0))
  ijkMaxBounds = tuple(numpy.maximum(ijkMaxBounds, 0))
```

**Comment by Saffron123456789** [comment]
Thanks, I had updated the code, but it didn't work, and still returned "libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument". Do you have any suggestion about that?

**Comment by JoostJM** [comment]
@Saffron123456789, Can you also try 

```
  ijkMinBounds = numpy.maximum(ijkMinBounds, 0).tolist()
  ijkMaxBounds = numpy.maximum(ijkMaxBounds, 0).tolist()
```

If that doesn't work, you can try (in an interactive python session) to play around with
`cif = sitk.CropImageFilter()`, and try setting different types of sequences (e.g. list, array, tuple) for the function `SetLowerBoundaryCropSize` and `SetLowerBoundaryCropSize`.
