### ISSUE TITLE
Bug in firstorder.py line 290

### ISSUE THREAD

**Issue by CaB15** [Radiomics/pyradiomics#475]
I am very new to Pyradiomics and Pyton, so somewhat to my surprise I seem to have spotted a small bug in firstorder.py line 290. The example files do not run for the feature RobustMeanAbsoluteDeviation
The two lines related to problem are the following:
percentileArray[percentileArray - prcnt10[:, None] < 0] = numpy.nan
percentileArray[index2=percentileArray - prcnt90[:, None] > 0] = numpy.nan
The problem is that the second line will not evaluate, due to the nan values added in the first line. If the two lines are replaced with the following four lines the code is running for all first order features without errors
index1=percentileArray - prcnt10[:, None] < 0
index2=percentileArray - prcnt90[:, None] > 0
percentileArray[index1] = numpy.nan
percentileArray[index2] = numpy.nan

I have a hard time believing that I should be the first one to spot his error. Please tell me if I presumably have made a wrong download. The current version on my computer is indicated to be 2.1.2
Best,
Carsten

**Comment by JoostJM** [comment]
@CaB15, It is not really an error, though it does raise a `RuntimeWarning`

Still, it is a very nice fix and I'll implement it in the master (a7bed1d).
