### ISSUE TITLE
JSON output for batch processing is not a valid JSON

### ISSUE THREAD

**Issue by fedorov** [Radiomics/pyradiomics#483]
Currently, when `pyradiomics` script is used in the batch mode, and the input is more than one combination of image/mask, the output is a list of dictionaries, which is not a valid JSON document:
```JSON
{
  "Image": "image1",
  "Mask": "mask1",
  ...
}
{
  "Image": "image2",
  "Mask": "mask2",
  ...
}
```

Should we revise this and instead output something like
```JSON
{
  {
    "Image": "image1",
    "Mask": "mask1",
    ...
  },
  {
    "Image": "image2",
    "Mask": "mask2",
    ...
  }
}
```

@JoostJM what do you think?

**Comment by JoostJM** [comment]
@fedorov, I agree,

While investigating this, I also discovered that JSON does not serialize numpy arrays by default. Therefore, I also added a custom serializer to deal with this (by converting to python list).

This is part of PR #481, commit 7f9e67c
