### ISSUE TITLE
Export the texture matrix

### ISSUE THREAD

**Issue by salan668** [Radiomics/pyradiomics#487]
To extract the texture features, the image was converted to the texture matrix frist , such as GLCM matrix. Now the pyradiomics supports to export the texture feature maps. Is it possible to export the texture matrix in different directions as nrrd, nii, or npy format? 

Thanks!

**Comment by JoostJM** [comment]
Storing the feature classes as a result is not implemented in PyRadiomics. However, you can access them if you want

The texture matrices are stored as P_<classname> numpy arrays in the feature class instances, you can access them there (this does require you to use the feature classes directly, and skips part of the preprocessing, as that is called from the feature extractor). 

Alternatively, you can calculate the matrices yourself using the C-extensions. Take a look at the `_calculateMatrix` function in the texture feature classes to see how.

**Comment by salan668** [comment]
Thank you, JoostJM. It's very clear for me. :)
