### ISSUE TITLE
RuntimeError: Number of elements in GLCM would overflow index variable!

### ISSUE THREAD

**Issue by ylmzkaan** [Radiomics/pyradiomics#489]
I know this has been discussed in #436  but the proposed solution did not solve the problem.

I have a 3D image (stack of 2D dicoms) with dimensions [491 341 258] (After cropping). I set the binwidth to different values from 25 (166 bins) to 500 (10 bins) but I still get "RuntimeError: Number of elements in GLCM would overflow index variable! Increase bin width or decrease number of angles to prevent this error."

I make my calculations for distances = [[1]]. It looks like it results in 13 different angles by default. Although I need only 3 orthogonal angles along z,y and x axes, I couldn't find a way to set them using the generateAngles().

Any ideas about the Runtime error and the angles?

**Comment by JoostJM** [comment]
@ylmzkaan, sorry for the late reply.

The error message simply means that the size of your GLCM would exceed 2^32! Decreasing the bin width should fix this, and the number of bins does not seem to be too much. However, I cannot reproduce your error as I don't have access to your data.

Can you share an example image/mask + parameter file for debugging?

**Comment by ylmzkaan** [comment]
@JoostJM thank you very much for your reply, no problems.

Here is the function that I use to calculate joint entropy and inverse difference moment of a 3d array dicomSlices with its mask. The link below has the dicomSlices.npy and mask.npy that I use and for you to reproduce the error.

https://www.dropbox.com/sh/6awoo221l25ttnk/AABzjRxL25RXfqYJepCcWN32a?dl=0

```
def _calcGLCMOfAllSlices(dicomSlices, masks, voiEdge=15, params={}):

    params["voxelBased"] = True
    params["kernelRadius"] = 7
    params["maskedKernel"] = True
    params["binWidth"] = 25

    glcm = RadiomicsFeatureExtractor(**params)
    radiomics.setVerbosity(10)
    
    glcm.disableAllFeatures()
    enabledFeatures = {}
    enabledFeatures["glcm"] = ["JointEntropy", "Idm"]
    glcm.enableFeaturesByName(**enabledFeatures) 

    dicomSlicesITK = sitk.GetImageFromArray(dicomSlices)
    masksITK = sitk.GetImageFromArray(masks)
    output = glcm.execute(dicomSlicesITK, masksITK, voxelBased=True)

    featureMap = sitk.GetArrayFromImage(output)

    return featureMap
```

**Comment by JoostJM** [comment]
@ylmzkaan, You can decrease param `voxelBatch` (default 10000). Set it to something like 100 or so, that should fix your problem (though the extraction may take a little longer...

**Comment by JoostJM** [comment]
i.e. add `params["voxelBatch"] = 100`

**Comment by ylmzkaan** [comment]
Thank you for the fix! Is it possible to store the GLCM index in an INT64? Would you plan to change that in a future version?

**Comment by JoostJM** [comment]
Yes, I'm currently working on making the range of the index variables larger.

**Comment by JoostJM** [comment]
@ylmzkaan, Looking at your script, there are some small notes I'd like to point out

1. you pass your image and mask as arrays, then get an image from that array. However, this does NOT take spacing into account, so be aware that this just assumes your dicom slices have spacing [1, 1, 1]!
1. you are using feature classes directly, which skips a lot of checking and preprocessing done by PyRadiomics. You can use this part of PyRadiomics by using the `featureextractor`. Checkout the helloVoxel.py (folder examples) on how to do this with voxel-based extraction
1. You are putting the output of the execution directly to SimpleITK.GetArrayFromImage. Does this throw an error? The output is a dict, with values being the images and the keys being the feature names.

**Comment by bsherkhane** [comment]
Hi Joost,

I am trying to extract radiomics features from PET images. 
What i do is , i convert the image and mask to nrrd using plastimatch. 

settings used:
bin width : 25.0
Sigma values =  1   2   3
Pixel resampling =  2   2   2

i am getting the following error.

![image](https://user-images.githubusercontent.com/38763758/118758447-afd77f80-b88c-11eb-8be4-04502b6a35c2.png)




can you please help me out in this regard.

**Comment by ianstath** [comment]
> 
> 
> Hi Joost,
> 
> I am trying to extract radiomics features from PET images.
> What i do is , i convert the image and mask to nrrd using plastimatch.
> 
> settings used:
> bin width : 25.0
> Sigma values = 1 2 3
> Pixel resampling = 2 2 2
> 
> i am getting the following error.
> 
> ![image](https://user-images.githubusercontent.com/38763758/118758447-afd77f80-b88c-11eb-8be4-04502b6a35c2.png)
> 
> can you please help me out in this regard.

Same here
```
params = {}
params["voxelBased"] = True
params["kernelRadius"] = 7
params["maskedKernel"] = True
params["binWidth"] = 25    
params["voxelBatch"] = 100    

rr = glcm.RadiomicsGLCM(flair, gt ,**params )
results = rr.execute()
```

```
 File "C:\Users\gstathop\Miniconda3\envs\tf-env\lib\site-packages\radiomics\glcm.py", line 139, in _calculateMatrix
    P_glcm, angles = cMatrices.calculate_glcm(*matrix_args)
MemoryError

```
