### ISSUE TITLE
Question about GLCM in pyradiomics

### ISSUE THREAD

**Issue by destinybuilt** [Radiomics/pyradiomics#490]
When I use pyradiomics to extract features, I get the following warning:
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
Should I pay attention to this warning and find a way to solve it?

**Comment by JoostJM** [comment]
No, it is just a warning to alert you of the fact that the in this case, joint average and sum average are 100% correlated. So no error, just a notification.

**Comment by omaghsoudi** [comment]
This warning is useful to know what happens; however, is there anyway to turn it off? 
Printing this warning slows down the code!

Thank you!

**Comment by fedorov** [comment]
@omaghsoudi you should be able to control that using the following arguments to the command-line extractor. The message you mention is a warning. By reducing the level of verbosity you should be able to disable printing of the warnings to the console.

```
$ pyradiomics --help
[...]
Logging:
  Controls the (amount of) logging output to the console and the (optional) log-file.

  --logging-level LEVEL
                        Set capture level for logging
  --log-file FILE       File to append logger output to
  --verbosity [{1,2,3,4,5}], -v [{1,2,3,4,5}]
                        Regulate output to stderr. By default [3], level
                        WARNING and up are printed. By specifying this
                        argument without a value, level INFO [4] is assumed.
                        A higher value results in more verbose output.
```

**Comment by omaghsoudi** [comment]
Is there any way that I can turn it off when I load the pyradiomics feature extractors?

I use it as follow:
from radiomics import firstorder, glcm, ngtdm, gldm, glrlm, glszm

I need to turn off verbose for these features families.

**Comment by fedorov** [comment]
If you use pyradiomics programmatically, you should be able to do something like this (see comments in https://github.com/Radiomics/pyradiomics/blob/master/radiomics/base.py#L22-L23):

```python
import logging
# set level for all classes
logger = logging.getLogger("radiomics")
logger.setLevel(logging.ERROR)
# ... or set level for specific class
logger = logging.getLogger("radiomics.glcm")
logger.setLevel(logging.ERROR)
```

I have not tested this, but I think something like this should work.

**Comment by omaghsoudi** [comment]
As you said, it resolved the issue.

Thank you!

**Comment by JoostJM** [comment]
Alternatively, you can selectively filter out warnings of a certain type (in this case, `DeprecationWarning`):

```
import warnings
warnings.simplefilter('ignore', DeprecationWarning)
```

**Comment by s-hood** [comment]
Hi, this solution isn't working for me. I've also tried:
`
from radiomics import setVerbosity
setVerbosity(60)
`
As described here: https://pyradiomics.readthedocs.io/en/latest/_modules/radiomics.html

However I still get the relentless
"GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated" log.

Please help!

**Comment by AnkushJamthikar** [comment]
I am still getting the messages printed on consol. Is there a way, which prevent the messages to be printed on the consol.  

![image](https://user-images.githubusercontent.com/67118930/209996200-3d358bb2-a408-499c-897a-fa592b1d4f56.png)

**Comment by robertoshea** [comment]
I have found the following code helpful

`logger = radiomics.logging.getLogger("radiomics")
logger.setLevel(radiomics.logging.ERROR)`
