### ISSUE TITLE
 complex pixel types currently are not supported

### ISSUE THREAD

**Issue by abhinandanbatra** [Radiomics/pyradiomics#494]
Hey I am trying to use fat water maps to generate textures, Bbut when I try to get an array from image. I am getting an error "complex pixel type are currently not supported". Will appreciate help?

**Comment by JoostJM** [comment]
Apparently, your images have a complex pixel type (i.e `x+iy`), what images are you trying to get an array from? SimpleITK should be able to load them. You can then get the Real component using SimpleITK's [ComplexToRealImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ComplexToRealImageFilter.html). The resultant image should be accepted by PyRadiomics.

**Comment by abhinandanbatra** [comment]
Hi @JoostJM , I am using water and fat maps to get array from. I think you are right I can use complex to real image filter. I will let you know if I have any issues. Thank you very much
