### ISSUE TITLE
Pyramiomics problem based on anaconda

### ISSUE THREAD

**Issue by destinybuilt** [Radiomics/pyradiomics#497]
I installed anaconda 5.2.0 (python version 3.6.5), then run "python -m pip install pyradiomics==2.1.2" code in Anaconda Prompt, then I put brain1_image.nrrd and brain_1label.nrrd In the sample code, the result of running the error is reported... How to solve it? (Before I installed Anaconda4.2.0, the python is 3.5.2 version number, and this problem does not occur)
The following is the error message:
TypeError Traceback (most recent call last)
<ipython-input-1-c8a2b3159cb8> in <module>()
      15 results=[]
      16 if im_vect.GetNumberOfComponentsPerPixel()==1:
---> 17 results.append(extractor.execute(im_vect,ma_path,label_channel=0))
      18 else:
      19 selector=sitk.VectorIndexSelectionCastImageFilter()

TypeError: execute() got an unexpected keyword argument 'label_channel

**Comment by JoostJM** [comment]
This feature has only been added in version 2.2.0 (see [release](https://github.com/Radiomics/pyradiomics/releases). It has been added in PR #445.

If you install the latest release it should work.

Moreover, looking at your code you can also remove `label_channel=0`, as it has no effect (mask ensured to be scalar by your if function).
