### ISSUE TITLE
Question about mask file input

### ISSUE THREAD

**Issue by Vir-Mittal** [Radiomics/pyradiomics#504]
Is it possible to directly input the newly generated mask file into the pyradiomics extractor, instead of providing a path to the mask file?

I know it works with SimpleITK objects, but I have a nifti (.nii) file and I get an error (Error reading mask Filepath or SimpleITK object) when providing the nii file directly to the extractor.

**Comment by JoostJM** [comment]
A niftii file is a file format and not an image object in python. Conversely, SimpleITK image object are not a file format but a representation of an image loaded in the RAM. 

As to supplying a mask to PyRadiomics, it can either be provided by a string pointing to a file (e.g. a niftii file) that can be loaded by SimpleITK as an image, or it is already a SimpleITK image object. Have you tried to load your mask in an interactive python session using SimpleITK? ( `import SimpleITK as sitk; im = sitk.ReadImage(r'<path\to\image.nii>')` )

**Comment by Vir-Mittal** [comment]
Thank you for the help, using a SimpleITK object to load the mask works
