### ISSUE TITLE
How can i calculate the specific ROI（region of interest）？

### ISSUE THREAD

**Issue by bbbbb12345** [Radiomics/pyradiomics#505]
I need get the features about normal tissues(such as rectum bladder etc). I had calculated features by 3D slicer. The results only have GTV1 and GTV2(only the ROI which  has been defined as target).
Any suggestions could be grateful.

**Comment by fedorov** [comment]
You can use Slicer SegmentEditor module to define any number of ROIs. Radiomics module will extract features for all regions of the Segmentation node that you specify in the interface.

**Comment by bbbbb12345** [comment]
Your answer is very helpful! Thx!

> You can use Slicer SegmentEditor module to define any number of ROIs. Radiomics module will extract features for all regions of the Segmentation node that you specify in the interface.
