### ISSUE TITLE
How to image preprocess the MR sequence medical image?

### ISSUE THREAD

**Issue by destinybuilt** [Radiomics/pyradiomics#509]
Can pyradiomics implement image preprocessing for MR? And is there a literature on the basis for the introduction of image preprocessing and the preprocessing method?

**Comment by fedorov** [comment]
There are various options you can change to control preprocessing of the image prior to feature extraction, such as normalization, which are documented here: https://pyradiomics.readthedocs.io/en/latest/customization.html#settings.

You can see an example parameter file for MR images here: https://github.com/Radiomics/pyradiomics/tree/master/examples/exampleSettings.

One introductory resource for image processing you can consider is the ITK guide: https://itk.org/ITKSoftwareGuide/html/.
