### ISSUE TITLE
Question about "No label object with label 1."

### ISSUE THREAD

**Issue by destinybuilt** [Radiomics/pyradiomics#510]
When I run pyradiomics for feature extraction, I always report an error----"No label object with label 1". How should I check if the mask is wrong? And what software and functions should be used to fix this mask?

**Comment by destinybuilt** [comment]
This is a image:
[https://drive.google.com/file/d/12sHa_m0HXQgVeL0FvK31rmrjj-mmIA8v/view?usp=sharing](url)

This is a mask:
[https://drive.google.com/file/d/188n-gB09e3Cxal6EQ_b-3cdhTVFQO8As/view?usp=sharing](url)

**Comment by fedorov** [comment]
You can use 3D Slicer (https://slicer.org) to visualize the label and confirm it is in the right place, and what is the label value.

Once you know what is the pixel value for the label, you don't need to fix it to be 1. Instead you can use the parameter settings file to specify the label value: https://github.com/Radiomics/pyradiomics/blob/master/examples/exampleSettings/Params.yaml#L22

You can also use the Slicer Radiomics extension to calculate features for all labels, independent of values, in your mask: https://github.com/Radiomics/SlicerRadiomics.

**Comment by JoostJM** [comment]
@destinybuilt, for some reason, the segmented voxels in your mask file have a value of 0.00392.

You can fix this in python:

```
import SimpleITK as sitk

ma = sitk.ReadImage('mask.nii')
ma_arr = sitk.GetArrayFromImage(ma)
ma_arr[ma_arr != 0] = 1

ma_new = sitk.GetImageFromArray(ma_arr)
ma_new.CopyInformation(ma)
sitk.WriteImage(ma_new, 'mask_corr.nii', True)
```
