### ISSUE TITLE
 RuntimeWarning: Mean of empty slice when using radiomics.shape.RadiomicsShape

### ISSUE THREAD

**Issue by raluca-san** [Radiomics/pyradiomics#520]
**EDIT** i think the volume calculated might be zero. Which is weird because I have a segmentation mask which I can see with the naked eye.
```
    return self.SurfaceArea / self.Volume
ZeroDivisionError: float division by zero
```
I want to use the `radiomics.shape.RadiomicsShape` to extract the minimum and maximum diameters (from all the slices) of a ROI object. My ROI object is a binary segmentation mask.

I read both the `inputImage` and the ` maskImage` with `SimpleITK` and resample to the same size and spacing (since the segmentation mask is a ROI).
`feat = radiomics.shape.RadiomicsShape(inputImage, maskImage)`
 However I always get the error: 

> RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)

> RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)

What's wrong? 

This is the inputImage contents after print
`Image (0000022882F6CC70)
  RTTI typeinfo:   class itk::Image<int,3>
  Reference Count: 1
  Modified Time: 9992
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 9981
  UpdateMTime: 9991
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  Spacing: [0.716797, 0.716797, 1]
  Origin: [-125.142, -401.642, 454.6]
  Direction: 
1 0 0
0 1 0
0 0 1
  IndexToPointMatrix: 
0.716797 0 0
0 0.716797 0
0 0 1
  PointToIndexMatrix: 
1.3951 0 0
0 1.3951 0
0 0 1
  Inverse Direction: 
1 0 0
0 1 0
0 0 1
  PixelContainer: 
    ImportImageContainer (00000228FC97F4A0)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,int>
      Reference Count: 1
      Modified Time: 9989
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0000022891047040
      Container manages memory: true
      Size: 61079552
      Capacity: 61079552`

THe mask contents after print:

`Image (0000022882F6D4B0)
  RTTI typeinfo:   class itk::Image<int,3>
  Reference Count: 1
  Modified Time: 10074
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 10061
  UpdateMTime: 10073
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 233]
  Spacing: [0.716797, 0.716797, 1]
  Origin: [-125.142, -401.642, 454.6]
  Direction: 
1 0 0
0 1 0
0 0 1
  IndexToPointMatrix: 
0.716797 0 0
0 0.716797 0
0 0 1
  PointToIndexMatrix: 
1.3951 0 0
0 1.3951 0
0 0 1
  Inverse Direction: 
1 0 0
0 1 0
0 0 1
  PixelContainer: 
    ImportImageContainer (0000022882DE7D90)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,int>
      Reference Count: 1
      Modified Time: 10071
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 00000228B945D040
      Container manages memory: true
      Size: 61079552
      Capacity: 61079552`

**Comment by JoostJM** [comment]
@raluca-san, If you use the feature extractor module, instead of the feature classes directly, PyRadiomics will provide more meaningful feedback. Using the feature classes directly skips a large number of steps and preprocessing, including checking if your mask is valid (i.e. contains at least 1 voxel with the value specified in your "label" parameter).

Can you re-run using the feature extractor?

**Comment by raluca-san** [comment]
@JoostJM I ran the feature extractor module. My issue was very simple, I didn't specify the label value in the settings.

this is the code as follows:
```
settings = {'label': 255}

extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(additionalInfo=True, **settings)
result = extractor.execute(inputImage, mask_resampled)
for key, val in six.iteritems(result):
    print("\t%s: %s" %(key, val))
```
