### ISSUE TITLE
TypeError: can only be called with ndarray object

### ISSUE THREAD

**Issue by TonyTnT** [Radiomics/pyradiomics#521]
When I want to compute glcm features, it always gets this.
The input is the path of the jpeg, and I want to compute the glcm of the 2D image. I have already read question #242 and do the following job, but I can't understand where this bug come from.
Even I run the code from your examples 'helloFeatureClass.py', it still get this error.
```
im_arr = sitk.GetArrayFromImage(im)
im_arr = np.expand_dims(im_arr, axis=0)
im3d = sitk.GetImageFromArray(im_arr)
```

**Comment by JoostJM** [comment]
@TonyTnT, since #242, PyRadiomics has changed and now supports 2D-feature extraction from 2D images. However, I think your issue is in the fact that your jpeg image represents a color figure (i.e. RGB, 3 values per voxel), whereas  PyRadiomics requires scalar volumes (i.e. gray-scale, only 1 value per voxel).

You can select a specific color channel from an SimpleITK image using `VectorIndexSelectionCastImageFilter`:

```
import SimpleITK as sitk
color_channel = 0
im = sitk.ReadImage(r'path/to/image.jpg')
selector = sitk.VectorIndexSelectionCastImageFilter()
selector.SetIndex(color_channel)
im = selector.Execute(im)
```

**Comment by TonyTnT** [comment]
But it doesn't make sense that when I run the examples 'helloFeatureClass.py', it still get the same error.

**Comment by JoostJM** [comment]
`helloFeatureClass.py` reflects how to use the featureclasses directly, which is not intended as default operating mode for PyRadiomics. The featureextractor module (as in helloRadiomics.py) implements additional checks and preprocessing. I'd advise not to run PyRadiomics using featureclasses directly, unless your interested in development and want to dive deep into the inner works of PyRadiomics.

**Comment by JoostJM** [comment]
@TonyTnT, can you provide a more extensive log, so that I may see where this error is thrown?

**Comment by TonyTnT** [comment]
Thank you a lot for being so kind to help me solve this problem, it's embarrassing that I reinstall the numpy and the problem has gone away. Maybe something wrong with my numpy installation. 
But I tried the way that you mentioned above to extract 2D features, it don't work.

```
    image = cv2.imread(imgpath)
    mask = cv2.imread(maskpath)
    imggray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    maskgray=cv2.cvtColor(mask,cv2.COLOR_BGR2GRAY)
    imggraysitk=sitk.GetImageFromArray(imggray)
    maskgraysitk=sitk.GetImageFromArray(maskgray)

    extractor = featureextractor.RadiomicsFeatureExtractor()
    extractor.disableAllFeatures()
    extractor.enableFeatureClassByName('shape')
    extractor.execute(imggraysitk, maskgraysitk, label)

```
There is no error when I run the code above, and no shape features either. And here are the results:
```
Shape features are only available 3D input (for 2D input, use shape2D). Found 2D input
Out[11]: 
OrderedDict([('diagnostics_Versions_PyRadiomics', '2.2.0'),
             ('diagnostics_Versions_Numpy', '1.17.1'),
             ('diagnostics_Versions_SimpleITK', '1.2.0'),
             ('diagnostics_Versions_PyWavelet', '1.0.0'),
             ('diagnostics_Versions_Python', '3.7.1'),
             ('diagnostics_Configuration_Settings',
              {'minimumROIDimensions': 2,
               'minimumROISize': None,
               'normalize': False,
               'normalizeScale': 1,
               'removeOutliers': None,
               'resampledPixelSpacing': None,
               'interpolator': 'sitkBSpline',
               'preCrop': False,
               'padDistance': 5,
               'distances': [1],
               'force2D': False,
               'force2Ddimension': 0,
               'resegmentRange': None,
               'label': 29,
               'additionalInfo': True}),
             ('diagnostics_Configuration_EnabledImageTypes', {'Original': {}}),
             ('diagnostics_Image-original_Hash',
              '9c43dfe1fd348cfc3e0c96c6bd58bc22e1415e3e'),
             ('diagnostics_Image-original_Dimensionality', '2D'),
             ('diagnostics_Image-original_Spacing', (1.0, 1.0)),
             ('diagnostics_Image-original_Size', (569, 521)),
             ('diagnostics_Image-original_Mean', 84.70471143434453),
             ('diagnostics_Image-original_Minimum', 0.0),
             ('diagnostics_Image-original_Maximum', 255.0),
             ('diagnostics_Mask-original_Hash',
              '45b5fdcb55680ec39c275128b4e077c8054eb07d'),
             ('diagnostics_Mask-original_Spacing', (1.0, 1.0)),
             ('diagnostics_Mask-original_Size', (569, 521)),
             ('diagnostics_Mask-original_BoundingBox', (0, 10, 312, 223)),
             ('diagnostics_Mask-original_VoxelNum', 58486),
             ('diagnostics_Mask-original_VolumeNum', 2),
             ('diagnostics_Mask-original_CenterOfMassIndex',
              (143.22008685839347, 119.4066272270287)),
             ('diagnostics_Mask-original_CenterOfMass',
              (143.22008685839347, 119.4066272270287))])
```

**Comment by JoostJM** [comment]
can you add the following?

```
import logging
import radiomics
radiomics.setVerbosity(logging.INFO)
```

This should make the extraction more verbose (optionally, using `loggin.DEBUG` for even more feedback).

Furthermore, PyRadiomics tells you why it is not extracting shape features: 
> `Shape features are only available 3D input (for 2D input, use shape2D). Found 2D input`. 

Therefore, enable `shape2D` instead of `shape`:
`extractor.enableFeatureClassByName('shape2D')`

**Comment by TonyTnT** [comment]
Emm, my problem solved, maybe I'm getting blind and stupid because of my studies recently.
Thank you very much.
