### ISSUE TITLE
A question of voxel-based specific settings

### ISSUE THREAD

**Issue by shenghaishxt** [Radiomics/pyradiomics#522]
Hello, I'm trying to get a feature map and I have two question of voxel-based specific settings. The following are my settings:

    imageType:
      Wavelet: {}

    featureClass:
      glcm:
        - JointEntropy

    setting:
      binWidth: 25
      force2D: false
      label: 1

    voxelSetting:
      kernelRadius: 1
      maskedKernel: false

Now I can only calculate voxel-wise feature in ROI area. I want to calculate in a rectangular box, ROI in this rectangular box is also calculated, and ROI can be outlined.  I tried some voxel settings but failed.

Thank you for your kind help!

**Comment by JoostJM** [comment]
@shenghaishxt, When you calculated voxel-wise, the ROI you provide determines for which voxels features are calculated. If you want them calculated in a rectangular box, you should create a rectangular ROI and use that.

Moreover, the ROI can be used to mask the kernel (i.e. the region used to calculated features for a voxel only contains voxels that are also part of the ROI), or full kernel calculation can be used, where the ROI is only used to determine for which voxels features should be calculated. The regions actually used are not changed by the ROI.

**Comment by shenghaishxt** [comment]
@JoostJM OK, thanks a lot. I will try to create a rectangular ROI and use that.
