### ISSUE TITLE
pyradiomics with two roi in one mask

### ISSUE THREAD

**Issue by nataschadam** [Radiomics/pyradiomics#532]
Hello! I need to extract features with pyradiomics from two different roi in one mask ( two adiacent but distinctive tumour areas). Both have label 1.
I prepared three lable masks, the first with lesion a, the second with lesion b and a third with both a and b.
I would like to compare the features I get with the single segmentations and with both.
Pyradiomics works fine with the single rois but gives me this error using the mask with both roi: Bounding box of ROI is larger than image space:
ROI bounds (x, y, z image coordinate space) ((529.9200000000001, 550.4000000000001, 88.16666666666669), (608.7680000000001, 653.8240000000002, 95.83333333333336))
Image Size (512, 512, 127)

What is the problem? Is it related to a mask problem or is the problem that I have two roi?

thank you for your help!!

nat

**Version (please complete the following information):**
 - OS: windows 
 - Python version: 3.6

**Comment by JoostJM** [comment]
@nataschadam, For some reason, your geometric information (origin, direction, spacing) is different between the ROI files. I suspect the error is for sure in origin (but possibly more of those parameters).

To explain this: PyRadiomics views images as arrays of pixel data representing a volume in real-world space. In addition to the values of the pixels, it also uses information on the distance between pixels (i.e. spacing), how the volume is rotated compared to a reference axis in real-world (direction) and where it is located (offset between origin of reference axis and first voxel of the volume: origin)

As you can read in the error message, the bounding box surrounding your ROI (note that this is not the bounding box of the mask file *containing* your ROI, but the *actual region of interest*, identified by your label parameter) is completely outside the image, i.e. there is no overlap (in x coordinates starts at 530 until 609, image is only 512 and in y starts at 550 until 653, image is only 512).

What may have happened is that during your conversion, you did not copy over the geometric information, causing it the revert to defaults (origin 0, 0, 0; spacing 1, 1, 1 and direction no rotation), which is different from your image. 

If you have an original ROI (check alignment in e.g. 3D slicer), you can use SimpleITK.ConnectedComponentImageFilter to get a single output ROI, with geometric information, and where each island of connected voxels (i.e. your 2 ROIs) has a unique label value.

This same effect can also be achieved using 3D slicers' Islands effect (segment editor)
N.B. PyRadiomics is able to directly read Slicer's segmentation format (which is different from legacy label maps and supports overlapping structures), but the you need to select the Segement by specifying `label_channel`, which is 0 for the first channel (top segment in Slicer), 1 for the second, etc.

**Comment by nataschadam** [comment]
dear @JoostJM thank you for your help. now that I was sure that the problem was related to the mask origin and not the fact that I had two roi in one mask I reopened the  mask with 3D Slicer and used the same lable value for both roi. (lable=1) . ( I ckecked the images origin of the original image and the mask and it's the same)
![example of image with two roi](https://user-images.githubusercontent.com/56153865/66304254-151b6e80-e8fd-11e9-98f4-003caced48ea.JPG)

I would like to obtain with pyradiomics a "mean" value of the features I would have with the two roi separately. Unfortunately it seems there are still some mistakes because the features I get are for example the following: 

    original_shape_SurfaceArea       original_shape_MinorAxisLength
roi a: 0.387348       0.666974
roi b: 0.168932      0.618507
roi a+b ( like in the attached image): 0.182484       0.560478

While I expected to be the surface area of a+b the sum of the two previous values. 

do you know what I am doing wrong?

**Comment by JoostJM** [comment]
@nataschadam, Can you also add the diagnostic information (especially the voxelNum s and volumeNum s), as well as Volume (both VoxelVolume and MeshVolume)?

**Comment by JoostJM** [comment]
Moreover, you can also extract features directly in Slicer using SlicerRadiomics extension.

My suggestion would be to also try to import your labelmap (from your image) into a segmentation and then use the islands effect. Finally, use the resulting segmentation (with different segments for your ROIs) to calculate features.

**Comment by nataschadam** [comment]
Hello @JoostJM yes of course: 

roi | diagnostics_Mask-original_VoxelNum | diagnostics_Mask-original_VolumeNum | original_shape_MeshVolume | original_shape_VoxelVolume
--| -- | -- | -- |--
a| 1 | (308.50086281276964, 305.07506471095775, 69.19413287316652) |21.79618 |-254
b| 1 | (304.1511879049676, 358.80829373650107, 75.90741540676746)|55.00987|-56
c(a+b)|2 | (304.4233728369733, 355.4458872121588, 75.48732554058796)|57.70983|-73

ok I will try to extract features from 3D slicer and compare the results. 

A question, when you say different segments for my ROIs what do you exactly mean ? That I have different label for both ROIs?

**Comment by JoostJM** [comment]
@nataschadam, How exactly do you compute your results? And how do you view them? This output looks misaligned to me (the entries at voxelNum seem to be volumeNum, and volumeNum a center point, or origin)

**Comment by nataschadam** [comment]
@JoostJM these are my results, The last row corresponds to the segmentation with the two ROIs..[ProvaFeaturesConfrontoA_B_C.txt](https://github.com/Radiomics/pyradiomics/files/3697411/ProvaFeaturesConfrontoA_B_C.txt)


Thank you very much for your help!!!

**Comment by JoostJM** [comment]
@nataschadam,your results are misaligned by 1. If you shift all 3 rows by 1 to the right, then everything matches up, and both volume and surface area of the 2 rois combined matches the results of the first ROI added with the results of the 2 ROI.

The cause of this misalignment is that you have a column 'patient' at the start, but which contains no data.

**Comment by nataschadam** [comment]
@JoostJM thank you very much... I feel so stupid !!! thanks again for your help and time!bye bye
