### ISSUE TITLE
About（'Label (%g) not present in mask. Choose from %s', 1）

### ISSUE THREAD

**Issue by GJjason** [Radiomics/pyradiomics#537]
After use plastimatch, the RTstruct image have this problem, so I want to use resample. But it still has this problem. The image does not match the template. How can I do next step?

**Comment by JoostJM** [comment]
Resampling will not fix this error, as it is due to the fact that the label (1) is not present in your mask. It is possible the mask is empty. My advise would be to visually check the result of the conversion, e.g. by using Slicer.
