### ISSUE TITLE
A Typo in Documentations' Usage Example: Should be RadiomicsFeatureExtractor

### ISSUE THREAD

**Issue by IAmAWildCard** [Radiomics/pyradiomics#538]
The sample code on [pyradiomics docs](https://pyradiomics.readthedocs.io/en/stable/usage.html) does not work:
`extractor = featureextractor.RadiomicsFeaturesExtractor(params)`
It is actually RadiomicsFeatureExtractor. Thanks.

**Comment by fedorov** [comment]
Thank you, this should be fixed now.
