### ISSUE TITLE
What do I need to do to use the module directly?

### ISSUE THREAD

**Issue by acseckin** [Radiomics/pyradiomics#540]
I want to extract a feature from an image or patch **without Simpleitk** library; but all examples route me to the use of Simpleitk. I'm developing applications with OpenCV and I don't want to use simpleitk (if it is possible). What is the aim of mask?  scikit-image librery doesnt need any mask (https://scikit-image.org/docs/dev/auto_examples/features_detection/plot_glcm.html). **Can you share an example with OpenCV  or Numpy?**

**Comment by JoostJM** [comment]
SimpleITK is used, as this also contains the geometric data, such as spacing, origin and direction. Furthermore, much of the preprocessing (e.g. resampling, normalization) is also done using SimpleITK.

The mask identifies the region in the image for which the texture should be calculated. In the example you shared, you have to extract this region yourself (`patch`). Furthermore, by identifying the region using the mask, non-regular patches are also supported.

**Comment by JoostJM** [comment]
Inside the feature classes, the images are converted to numpy arrays prior to feature calculation. These arrays serve as input to the C-extensions that calculate the texture matrices, and it's result is used for feature calculation.

So if you want to use PyRadiomics code, you'd have to make a copy of a feature class module, and rewrite the initialization function to accept numpy input. This will not be supported in the official PyRadiomics library, as it supports feature extraction from medical imaging, where the geometric information is important and should not be ignored.
