### ISSUE TITLE
A fixed minimum value in getBinEdges to follow IBSI recommendations

### ISSUE THREAD

**Issue by AngieDavey** [Radiomics/pyradiomics#542]
Hello,

I was wondering if it could be possible to implement an alternative option in the 'getBinEdges' function that will allow a fixed minimum value to be set (as the default calculates the minimum from segmented voxels). 

This would allow for a consistent minimum value across multiple data-sets without needing to define a re-segmentation minimum that is greater than or equal to the largest minimum across the patient cohort.  

I am unsure of the impact of having initial empty bins for some data-sets, but I hope this would provide an option to follow the IBSI recommendation that the same value be used for the first bin in fixed bin size discretisation (without having to sacrifice information with re-segmentation). 

Thank you,
Angela.

**Comment by JoostJM** [comment]
See #498

**Comment by JoostJM** [comment]
This will require to use re-segmentation (as otherwise, one cannot guarantee that there are no 'invalid' grayvalues (i.e. values that would be < 1 after discretization)

**Comment by AngieDavey** [comment]
Thank you for your response. The option in your function IBSI_binning to force the lower bound to the min value of the re-segmentation range (when defined) is exactly what I had in mind, query solved.
