### ISSUE TITLE
How to extract 3D features

### ISSUE THREAD

**Issue by LiJiaqi96** [Radiomics/pyradiomics#549]
Hi,

I have used the PyRadiomics package for 2D problems and thanks for your contributions! Now I am dealing with 3D radiomic features and encountered some problems.

I used the class "featureextractor.RadiomicsFeaturesExtractor" with:

`extractor = featureextractor.RadiomicsFeaturesExtractor()`
`radio_result = extractor.execute(img, label)`

where **img** is 3D numpy array of image slices and **label** is 3D numpy array of label slices. label is in the same size of img.

But when I executed the code, I got the error:

> Error reading image Filepath or SimpleITK object

Could you please tell me how can I extract the 3D radiomic features given the image and label both in 3D form? Thanks!

**Comment by jw-fu** [comment]
Radiomics's input need SimpleITK object.You input numpy object.So you need use SimpleITK.ReadImage

**Comment by JoostJM** [comment]
More specifically, `SimpleITK.GetImageFromArray`. Be aware that this uses a default pixel spacing of (1, 1, 1).
