### ISSUE TITLE
How can i get wavelet images when using parameter file to extract features?

### ISSUE THREAD

**Issue by yuwon-shin** [Radiomics/pyradiomics#551]
HI,

I'm extracting features from MRI images(nii.gz).
Could you please tell me how can I show only the wavelet-LLL images.

Here's my codes.
> extractor = featureextractor.RadiomicsFeatureExtractor(paramsFile)

> for case_id in patient_id :
       image = sitk.ReadImage(path + case_id+"/"+"T2.nii.gz")
       label = sitk.ReadImage(path + case_id+"/"+"T2_v4.nii.gz")
       features[case_id] = extractor.execute(image,label)

Thanks!

**Comment by fedorov** [comment]
Did you look at this function: https://github.com/Radiomics/pyradiomics/blob/master/radiomics/imageoperations.py#L772?

**Comment by yuwon-shin** [comment]
Hi Fedorov,

Yes i’v seen that function!
But i don’t know exactly how to use that function when collectively extract features by parameter file. Some other image setting like Resampling/ normalize are contained in the file, so that function is not work at same condition, simply.

**Comment by JoostJM** [comment]
@yuwon-shin, check out the section on the parameter file (under customizing the extraction). There you can find details on how the paramter file is build. Bascially, you have 3 sections: Setting, ImageType and FeatureClass. These respectively customize the settings (e.g. resampling/normalization), the filters to apply to the image (e.g. Wavelet) and which features to extract (e.g. GLCM).

**Comment by dvpalomino** [comment]
@JoostJM The function getWaveletImage(inputImage, inputMask, **kwargs) applies a wavelet filter to the input image and returns both the decompositions and the approximation. So, we shouldn't expect this function to output a reconstructed image, correct? Does this mean that radiomic feature extraction is performed on the non-reconstructed image? My understanding is that radiomic feature extraction should be done on the filtered and reconstructed version of the original image, to enhance certain high/low frequency patterns. It feels unintuitive to extract radiomic features directly from a wavelet-transformed image.
