### ISSUE TITLE
How to extraction 3D feature.And what's voxel-based 

### ISSUE THREAD

**Issue by jw-fu** [Radiomics/pyradiomics#553]
I input 2D image,radiomics can extraction features.But I input .nddr,radiomics also extraction features.This is 2d or 3d features.And I don't know what's voxel-based,is 3d feature?

**Comment by jw-fu** [comment]
I input 2D image,radiomics can extraction features.But I input .nddr,radiomics also extraction features.This is 2d or 3d features.And I don't know what's voxel-based,is 3d feature?

**Comment by fedorov** [comment]
You can read about 2D vs 3D features here: https://pyradiomics.readthedocs.io/en/latest/faq.html#what-modalities-does-pyradiomics-support-2d-3d-color

Voxel-based feature extraction calculates feature value for each voxel in the image, see here: https://pyradiomics.readthedocs.io/en/latest/usage.html#voxel-based-radiomics

**Comment by jw-fu** [comment]
> 你可以在这里阅读2D VS 3D特征：[http://PycRealth.Read Decs.IO/En/NeX/FAQ.html](https://pyradiomics.readthedocs.io/en/latest/faq.html#what-modalities-does-pyradiomics-support-2d-3d-color)
> 
> 基于体素的特征提取计算图像中每个体素的特征值，参见：[http://PycRealth.Read Decs.IO/En/最新/用法.html基于体素的放射物理学](https://pyradiomics.readthedocs.io/en/latest/usage.html#voxel-based-radiomics)

**Comment by jw-fu** [comment]
Thank you very much.I read this docs.I don't understand that if I input 2D image, it will extract 2D features. If I input 3D image, it will extract 3D features. Is that right? The voxel-based ==3D features?The doce is not details.

**Comment by fedorov** [comment]
Voxel-based feature extraction calculates feature value for each voxel in the image.

**Comment by GiulioBen** [comment]
In practice the software do the following procedure:
-pick one voxel
-define a kernel in the neighbourhood of the pixel (e.g. a 5x5x5 cube with center in the voxel)
-calculate the features in this kernerl (i.e. only considering the voxels lying inside the 5x5x5 cube)
-report the calculated value as the new pixel of a new image.

My question now is: why a cubic kernel and not a spherical one? I mean, texture features are mostly isotropic... and a sphere is too... i'd suggest to implement a spherical kernel!

**Comment by fedorov** [comment]
> why a cubic kernel and not a spherical one? I mean, texture features are mostly isotropic... and a sphere is too... i'd suggest to implement a spherical kernel!

@GiulioBen I believe the main reason is because image voxels are cubic and not spherical, and implementing spherical kernel would require a lot of effort with unknown benefit. Can you point to studies that utilize spherical kernel and demonstrate its advantages in radiomics studies?

Your contributions to pyradiomics implementing new features are always welcomed, if you would like to implement and evaluate it yourself.

**Comment by GiulioBen** [comment]
> Can you point to studies that utilize spherical kernel and demonstrate its advantages in radiomics studies?

No, I can't. 

At the moment I don't feel expert enough to modify your code. I'm only used to make my own scripts/code. Thank you for sharing your experience.
