### ISSUE TITLE
Entropy is always -3.2034265e-16 for all my datasets

### ISSUE THREAD

**Issue by 3omarkamal** [Radiomics/pyradiomics#555]
I use Pyradiomics for First Order Statistics. I have a dataset of 120 imaging studies, a simpleITK mask is drawn for each. All of the calculated parameters are okay except for the entropy which comes with the same value of -3.2034265e-16. some thing is definitely wrong which I can't understand.

Could someone help with that?
**PyRadiomics configuration**
Default Configuration is used

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**
from radiomics import firstorder, glcm
import SimpleITK as sitk
import pandas as pd
import os

inputImage = '/maps/ADC600.nii'
label = '/ROI.nii.gz'

img = sitk.ReadImage(inputImage)
label = sitk.ReadImage(label)

extractor = firstorder.RadiomicsFirstOrder(img, label)
result = extractor.execute()

print(result)

{'10Percentile': array(0.7959345), '90Percentile': array(1.39250703), 'Energy': array(3542.78813808), 'Entropy': array(-3.2034265e-16), 'InterquartileRange': array(0.29801807), 'Kurtosis': array(6.4032361), 'Maximum': array(2.7256342), 'MeanAbsoluteDeviation': array(0.20562959), 'Mean': array(1.08870987), 'Median': array(1.06011275), 'Minimum': array(0.00100029), 'Range': array(2.72463391), 'RobustMeanAbsoluteDeviation': array(0.12463539), 'RootMeanSquared': array(1.12625601), 'Skewness': array(1.09484081), 'TotalEnergy': array(3542.78813808), 'Uniformity': array(1.), 'Variance': array(0.08316343)}

**Version (please complete the following information):**
 - OS: [MacOS]
 - Python version: 3.6
 - PyRadiomics version  2.2.0

**Comment by fedorov** [comment]
You probably need to experiment with `binWidth`/`binCount` parameters - see related discussion here: https://github.com/Radiomics/pyradiomics/issues/552.

**Comment by 3omarkamal** [comment]
Thanks a lot, that works like magic :)
