### ISSUE TITLE
Clarification in documentation

### ISSUE THREAD

**Issue by rcuocolo** [Radiomics/pyradiomics#557]
I had some issues while performing 2D feature extraction on MR images due to my misunderstanding of the documentation. However, some editing could avoid similar issues for other users. In particular, these passages in the Customizing the Extraction page:

resampledPixelSpacing [None]: List of 3 floats (>= 0), sets the size of the voxel in (x, y, z) plane when resampling. A value of 0 is replaced with the spacing for that dimension as it is in the original (non-resampled) mask, thereby enabling only in-plane resampling, for example.

force2Ddimension [0]: int, range 0-2. Specifies the ‘slice’ dimension for a by-slice feature extraction. Value 0 identifies the ‘z’ dimension (axial plane feature extraction), and features will be extracted from the xy plane. Similarly, 1 identifies the y dimension (coronal plane) and 2 the x dimension (saggital plane). if force2Dextraction is set to False, this parameter has no effect.

It is not immediately clear that x, y, and z planes are relative to the scan plane, almost always axial on CT but variable in orientation for MRI, and not "absolute" (e.g. aligned to the axial, sagittal and coronal planes of the patient). So x and y always refer to the in-plane dimensions, independently of acquisition plane, while z to the depth. This can seem obvious in retrospect but could be more explicitly stated.

**Comment by pieper** [comment]
Thanks for your help in clarifying the documentation 👍 

Would you be able to provide this in the form of a [github pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)?  It's not very difficult, even if you aren't familiar with git.  You just fork the repository, and then you can edit the text in your browser to propose the change.

This way your edits would be appropriately credited and you could propose the exact wording you think would be most helpful.  Plus if we get in a habit of doing this then it's easier to have more people contribute to make the code better.

**Comment by rcuocolo** [comment]
I added a 2D example parameter file with some comments on the relative settings. I think this should also be better explained on the online documentation outside of github.

**Comment by rcuocolo** [comment]
Edited as presented in issue #558

**Comment by fedorov** [comment]
Resolved by #558 - thank you @rcuocolo!
