### ISSUE TITLE
Keep dimensions of image/mask in feature map[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by cameronsevern** [Radiomics/pyradiomics#560]
I am wondering if there is a way to change the behavior of voxelBased feature extraction to output an image with the same dimensions as the original image/mask. It appears that the simple ITK image is cropped. Alternatively, is there a way to know the coordinates of the cropped image in relationship to the original? I am working on a visualization that overlays the feature map on top of the original image and a custom alignment for each image is not feasible. 

Thanks!

**Comment by fedorov** [comment]
> Alternatively, is there a way to know the coordinates of the cropped image in relationship to the original? 

Yes, the output cropped image is in the same physical space as the input image. The visualization you are working on is already possible to do in 3D Slicer (https://slicer.org). You can confirm you can see the overlap iof the feature map on top of the image if you load the voxel-based feature image and source image in Slicer, and select those as background and foreground layers. Let us know if you need pointers to get started with Slicer!

**Comment by erin5116** [comment]
> I am wondering if there is a way to change the behavior of voxelBased feature extraction to output an image with the same dimensions as the original image/mask. It appears that the simple ITK image is cropped. Alternatively, is there a way to know the coordinates of the cropped image in relationship to the original? I am working on a visualization that overlays the feature map on top of the original image and a custom alignment for each image is not feasible.
> 
> Thanks!

I was looking for something similar, as I'm not that familiar on how to work with the output if they're not the same dimension.
It seems like there's currently no setting to keep the dimention of output feature maps same as input, but we can resample it back with sitk.Resample (reference the input image and use identity transform, nearest neighbour interpolator, and stick with the feature map pixel type):

sitk.Resample(feature_map , original_image , sitk.Transform() , sitk.sitkNearestNeighbor , 0 , feature_map.GetPixelID() )

**Comment by JoostJM** [comment]
You're indeed quite close. If you don't resample your input, output feature maps maybe shifted, but otherwise align with the same grid, so nearest neighbor is the best interpolator to use then. When you do resample, also consider using other interpolators. As to the code:

```
import SimpleITK as sitk
rif =sitk.ResampleImageFilter()
rif.SetReferenceImage(image)
rif.SetOutputPixelType(map.GetPixelID())
rif.SetInterpolator(sitk.sitkNearestNeighbor)
map = rif.Execute(map)
```
