### ISSUE TITLE
[QUESTION] Enable shape features in pipeline module

### ISSUE THREAD

**Issue by mattmagic149** [Radiomics/pyradiomics#562]
Hey all,

I am trying to enable shape features in the pipeline module.
For all the other feature classes the pipeline works as expected.
I tried enabling the classes as a whole.

`
feature_extractor = RadiomicsFeaturesExtractor()
feature_extractor.enableFeatureClassByName('shape', True)
feature_extractor.enableFeatureClassByName('glcm', True)
radiomic_features = feature_extractor.computeFeatures(image_itk, mask_itk, prefix)
`

As well as enabling features by name.

`
feature_extractor = RadiomicsFeaturesExtractor()
feature_extractor.enableFeaturesByName(shape=['Compactness1'], glcm=['Autocorrelation'])
radiomic_features = feature_extractor.computeFeatures(image_itk, mask_itk, prefix)
`

None of the above options returns the shape features. Is there something wrong with my configuration?

Cheers,

Matt

**Version (please complete the following information):**
 - OS: [macOS Catalina 10.15.3]
 - Python version: [3.6.4]
 - PyRadiomics version [3.0]

**Comment by fedorov** [comment]
I am unable to reproduce the issue you are reporting.

I modified [this example file](https://github.com/Radiomics/pyradiomics/blob/master/examples/helloRadiomics.py) to enable shape features with the following:

```
extractor.enableFeatureClassByName('shape')
```

ran it as follows with the latest version of code:

```
$ python examples/helloRadiomics.py
```

and the output clearly includes shape features:

```
Computed original_shape_Elongation: 0.5621171627174117
Computed original_shape_Flatness: 0.46105975346582595
Computed original_shape_LeastAxisLength: 28.58442318537648
Computed original_shape_MajorAxisLength: 61.99722046980875
Computed original_shape_Maximum2DDiameterColumn: 49.490854979101925
Computed original_shape_Maximum2DDiameterRow: 65.88905951721043
Computed original_shape_Maximum2DDiameterSlice: 53.59397776919529
Computed original_shape_Maximum3DDiameter: 69.60099030590368
Computed original_shape_MeshVolume: 16147.51180013021
Computed original_shape_MinorAxisLength: 34.849701666854735
Computed original_shape_Sphericity: 0.4798234536231475
Computed original_shape_SurfaceArea: 6438.821603779402
Computed original_shape_SurfaceVolumeRatio: 0.3987500788652454
```

Perhaps something is wrong with your mask?

**Comment by mattmagic149** [comment]
I already have the image and the mask in memory and therefore use the "computeFeatures" method rather than "execute".
Apparently, I need to call "computeShape" as an additional step, since shape features are skipped in "computeFeatures".

`
# Handle calculation of shape features separately
if featureClassName.startswith('shape'):
    continue
`

**Comment by JoostJM** [comment]
@mattmagic149, what you're looking for is the function `execute` on feature_extractor, this also handles shape feature calculation. function `computeFeatures` and `computeShape` are both called from `execute`. This also ensures the filters are applied if enabled.

**Comment by JoostJM** [comment]
@mattmagic149, did you manage to make your pipeline work?
