### ISSUE TITLE
Runtime error issue

### ISSUE THREAD

**Issue by AT3432984** [Radiomics/pyradiomics#564]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by AT3432984** [comment]
When trying to run the code, I am getting the following error:

RuntimeError: Excpetion thrown in SimpleITK LabelStatisticsImageFilter_Execute: Code\BasicFilters\SRC\sitkLabelStatisticsImageFilter.cxx:134: sitk::ERROR: Both images for LabelStatisticsImageFilter don't match type or dimension! 

During handling of the above exveption, another exception occurred:

ValueError: Image/Mask datatype or size mismatch. Potential fix: enable correctMask

I have changed Force2D to True and correctMask to true but it still isn't working. Any ideas on what I should do next?

**Comment by fedorov** [comment]
What are the errors when you enable correctMask setting?
