### ISSUE TITLE
[nrrd] nrrdLoad: trouble reading 

### ISSUE THREAD

**Issue by michaleologist** [Radiomics/pyradiomics#565]
Hello
My English is not good. I try to make my question clear.

My window version 1909. I use anaconda to learn this pyradiomics.
I have finished git pyradiomics.
However, when I run THE EXAMPLE "helloRadiomics.py", something error happens. 

THANKS.

C:\Users\Administrator\radiomics\examples>helloFeatureClass.py
Traceback (most recent call last):
  File "C:\Users\Administrator\radiomics\examples\helloFeatureClass.py", line 24, in <module>
    image = sitk.ReadImage(imageName)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\SimpleITK\SimpleITK.py", line 8876, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: D:\a\1\sitk-build\ITK\Modules\IO\NRRD\src\itkNrrdImageIO.cxx:749:
itk::ERROR: NrrdImageIO(0000024D02CF4E30): Read: Error reading C:\Users\ADMINI~1\AppData\Local\Temp\pyradiomics\data\brain1_image.nrrd:
[nrrd] nrrdLoad: trouble reading "C:\Users\ADMINI~1\AppData\Local\Temp\pyradiomics\data\brain1_image.nrrd"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read:
[nrrd] _nrrdEncodingGzip_read: expected 3276800 bytes but received 3027933

**Comment by fedorov** [comment]
Are you able to load the image and the mask using [3D Slicer](https://slicer.org)?

**Comment by michaleologist** [comment]
Thanks for your message.
caus the image was damaged.
I redownload the image and It runs.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrey Fedorov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 凌晨2:19
收件人:&nbsp;"Radiomics/pyradiomics"<pyradiomics@noreply.github.com&gt;;
抄送:&nbsp;"叫我庄先生"<568908401@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Radiomics/pyradiomics] [nrrd] nrrdLoad: trouble reading  (#565)




Are you able to load the image and the mask using 3D Slicer?

**Comment by jbnjvc10000** [comment]
I have also met this problem, and try to modify some code
`imagePath, maskPath = radiomics.getTestCase('brain1',dataDirectory='./data')`
This should work↑
PS. The problem may be because `getTestCase` can't download full image
