### ISSUE TITLE
dcmqi cannot find SEG dcm [BUG]

### ISSUE THREAD

**Issue by kingaber** [Radiomics/pyradiomics#566]
**Describe the bug**
issue when running segimage2itkimage with my dicom SEG file. I can open and visualize my file in Slicer and I checked many times that the path I pass is correct.. This is the error I get
Error: MYPATH\000000.dcm not found!
dcmqi repository URL: git@github.com:QIICR/dcmqi.git revision: 9c0c7bf tag: latest-7-g9c0c7bf

I tried to run similar with legacy.dcm shared in one of the tutorials and I get the same error

**To Reproduce**
docker run qiicr/dcmqi segimage2itkimage  --inputDICOM "MYPATH\000000.dcm" --outputDirectory "MYPATH\OUTPUT" --prefix PatientID

**Expected behavior**
convert SEG dicom file to NRRD. I'd like it to be in same geometry as reference CT, but ther is no argument to pass (e.g. plastimatch has -referenced-ct)

**Version (please complete the following information):**
 - OS: Windowss 10 Pro
 - Python version: 3.7
 - PyRadiomics version 2.2.0

**Additional context**

**Comment by fedorov** [comment]
You need to make sure the directory with the data is shared with the docker, as discussed in the dcmqi instructions here: https://qiicr.gitbooks.io/dcmqi-guide/opening/installation/docker.html#shared-directory-between-docker-container-and-host.

Going forward, please post dcmqi issues on dcmqi issue tracker: https://github.com/QIICR/dcmqi.

> I'd like it to be in same geometry as reference CT, but ther is no argument to pass (e.g. plastimatch has -referenced-ct)

dcmqi does not have this feature. You will need to resample the output image using SimpleITK or other tools. Also note that for pyradiomics you don't need to have the mask in the same geometry as input image, see here: https://pyradiomics.readthedocs.io/en/latest/faq.html#geometry-mismatch-between-image-and-mask.

**Comment by kingaber** [comment]
Oh, you are right, I missed the docker sharing part before. Thank you, all works well now!
