### ISSUE TITLE
radiomic features order on csv output

### ISSUE THREAD

**Issue by Mikeaie** [Radiomics/pyradiomics#569]
Hi,  
when running pyradiomics on different mask-image pairs (no batch mode), I'm getting a different columns order for each resulting csv file (i.e. I can find the same feature at column 15 for the first csv, and at columns 8  for the second, and so on)
Therefore, I'm unable to do a direct comparison among different csv without a prior ordering.  Is there a way to constrain the columns order of the csv output?
Thank you for the support

**Comment by JoostJM** [comment]
@Mikeaie, at the moment, no. Features are returned as a python dictionary, which is unordered.

That said, you can compare easy if you load them using e.g. `pandas`, or if you use the python `csv.DictReader` class, which loads each row in your CSV as a dictionary, where the keys can be determined by the first row.

**Comment by giemmecci** [comment]
Hi,
Any plan on changing this behavior? I'm using pyradiomics in batch mode, and it would be ideal to have a consistent order for the columns in the output file.

Thanks!
