### ISSUE TITLE
How to extract features from multi ROIs in one scan slice?

### ISSUE THREAD

**Issue by Gonglixin** [Radiomics/pyradiomics#570]
I'm trying to use pyradiomics to extract features from CT. However there are multi ROIs in one scan slice for some cases while others involving 1 ROI. How should I do? Thanks for your attention!

**Comment by Gonglixin** [comment]
Sorry not make it clear. I want to extract features from multi ROIs and regard them as a whole  ROI.

**Comment by JoostJM** [comment]
This is not supported in PyRadiomics, only 1 segment/ROI/label can be selected at one time. 
You could fix this using a simple pre-processing step:

```
import SimpleITK as sitk
ma = sitk.ReadImage('path/to/mask.nrrd')
ma = ma != 0
```

This assumes mask is a 3D volume with the different ROIs identified by different values (i.e. "labels"). For segmentation objects it'll be a bit different.

You can store the result using `sitk.WriteImage(ma, 'path/to/output.nrrd', True)`, or use the `ma` object directly by passing it as the mask argument to `RadiomicsFeatureExtractor.execute()`.

**Comment by Gonglixin** [comment]
Thanks for your reply! If I understand correctly, for the 2D volume, the feature extraction process for ROIs identified by 1 label is the same as that of 1 ROI, eventhough they are disconnected or do not overlap. Is that right?

**Comment by Gonglixin** [comment]
Note that some features may make little sense in above cases. What I can confirm is that the shape feature is one of them. Do you think there are other features that are meaningless?

**Comment by JoostJM** [comment]
1. Yes, what happens inside PyRadiomics is that the mask gets converted to a boolean mask: all voxels with label value equal to `label` are set to `True`, the rest `False`. Optionally, when a 4D segment mask is provided, `label_channel` can be used to select the index of the pixel vector to use. Further calculation is done using only those voxels from the image that are marked `True` in the mask, regardless of where they are.
2. This certainly means that many features will make little sense, especially the shape features. I my opinion, this (to a lesser extent) applies to ALL features, as the whole goal is to try describe a texture, which is probably unique to each lesion and therefore should also be considered separate for each lesion.

If you want to make sure you don't have separate volumes, try to use SimpleITK's ConnectedComponentImageFilter, which can split your connected ROI's. As a final check, PyRadiomics puts out the diagnostic feature `Diagnostics_Mask-original_VolumeNum`, which uses the same ConnectedComponentImageFilter to detect how many connected ROI's are identified by the provided `label`/`label_channel`.

**Comment by Gonglixin** [comment]
Got it! Thanks for your time and detailed reply! It helps me a lot!
