### ISSUE TITLE
Labels greater than 255 lead to inaccurate exception message[BUG]

### ISSUE THREAD

**Issue by MaximilianSchnabel** [Radiomics/pyradiomics#571]
Hey,
the following Code:

// loading 2D .png image
sitkImage = sitk.ReadImage(imagePath, sitk.sitkInt32)
sitkImage.SetSpacing((1.0, 1.0))

// loading 2D .png mask 
sitkMask = sitk.ReadImage(maskPath, sitk.sitkUInt32)
sitkMask.SetSpacing((1.0, 1.0))

label = int(numpy.unique(mask)[-1])
extractor = featureextractor.RadiomicsFeatureExtractor(additionalInfo=True, label=label)
data = extractor.execute(sitkImage, sitkMask, label=label)

in my case throws the following exception:
ValueError: Label (485) not present in mask. Choose from [  1   4   5   7   8   9  10  12  16  17  21  26  27  28  32  38  41  42
  43  44  46  50  53  54  57  63  66  69  71  73  75  78  82  89  92  93
  94  95 102 104 105 106 108 111 112 113 114 115 116 121 122 126 133 134
 136 142 151 160 161 162 164 165 166 167 172 173 174 175 187 188 189 191
 193 194 200 220 222 223 228 231 237 ***255***]

whereas the actual labels used within the mask are:
[  0   1   4   5   7   8   9  10  12  16  17  21  26  27  28  32  38  41,  42  43  44  46  50  53  54  57  63  66  69  71  73  75  78  82  89  92,  93  94  95 102 104 105 106 108 111 112 113 114 115 116 121 122 126 133, 134 136 142 151 160 161 162 164 165 166 167 172 173 174 175 187 188 189, 191 193 194 200 220 222 223 228 231 237 ***256*** 258 261 ... some more ... 485]

I'd like to suggest to either accept label values greater than 255 or throw an exception that describes the actual issue more accurately. While the options to choose from do represent the options I got, the statement "Label (485) not present in mask." is misleading and in this case not true.

Just wanted to let you know, have a nice day

**Comment by pieper** [comment]
Are you using a a 16bit png?  Most png files are only 8 bit, so they only have values up to 255.

**Comment by MaximilianSchnabel** [comment]
You were right, the clipping was due to the png file. I'm sorry, really should have checked that one first. Thanks!
