### ISSUE TITLE
Set absolute bound on HU number

### ISSUE THREAD

**Issue by codecrazer** [Radiomics/pyradiomics#573]
Dear all, due to some of CT will have maximum Housefield units value more than 3000. Is it possible for me to absolutely bound HU before binwidth resampling in pyradiomics batch parameter file? Thanks for your help!

**Comment by pieper** [comment]
Hi - good question, I don't think that's a high-level option right now but it could be done using numpy, skimage, or simpleitk to pre-process the images.

By the way, for general discussions let's use the discourse forum and then file issues here when they become more concrete. https://discourse.slicer.org/c/community/radiomics

Thanks

**Comment by JoostJM** [comment]
Addressed [here](https://discourse.slicer.org/t/how-can-i-set-absolute-bound/11263/2'
