### ISSUE TITLE
If you are confused, please calm down and read examples carefully, especially for layman like me.

### ISSUE THREAD

**Issue by ctwangtz** [Radiomics/pyradiomics#577]
How to get more feature using filter?
There is no instructions to teach it.

**Comment by fedorov** [comment]
Did you look at the example settings file here: https://github.com/Radiomics/pyradiomics/tree/master/examples/exampleSettings ?

**Comment by ctwangtz** [comment]
> Did you look at the example settings file here: https://github.com/Radiomics/pyradiomics/tree/master/examples/exampleSettings ?

you know, the instruction is not easy to understand.

**Comment by JoostJM** [comment]
@ctwangtz, what exactly is the part you find difficult to understand? 

Filters are detailed in the online documentation. The can be enabled by specifying them in the parameters file as shown in the examples. Features are extracted from all enabled "image types", which are either the original image, or results from filters applied to the original image.

**Comment by ctwangtz** [comment]
> @ctwangtz, what exactly is the part you find difficult to understand?
> 
> Filters are detailed in the online documentation. The can be enabled by specifying them in the parameters file as shown in the examples. Features are extracted from all enabled "image types", which are either the original image, or results from filters applied to the original image.

Thank for your reply,  unknown always caused a difficute feeling, especially for a machine learning beginner. 
I searched all the examples you list and there was not a keyword like pywavelet.

**Comment by ctwangtz** [comment]
> what exactly is the part you find difficult to understand?
> 
> Filters are detailed in the online documentation. The can be enabled by specifying them in the parameters file as shown in the examples. Features are extracted from all enabled "image types", which are either the original image, or results from filters applied to the original image.

OMG, I found it.

THX

 : )

**Comment by ctwangtz** [comment]
> @ctwangtz, what exactly is the part you find difficult to understand?
> 
> Filters are detailed in the online documentation. The can be enabled by specifying them in the parameters file as shown in the examples. Features are extracted from all enabled "image types", which are either the original image, or results from filters applied to the original image.

How to use **enableAllFeatures**?
Could you give me a example about it?
thx

**Comment by ctwangtz** [comment]
> @ctwangtz, what exactly is the part you find difficult to understand?
> 
> Filters are detailed in the online documentation. The can be enabled by specifying them in the parameters file as shown in the examples. Features are extracted from all enabled "image types", which are either the original image, or results from filters applied to the original image.

Can you give me a code that how to enable all filters? I studied it for a long time and was confused.
