### ISSUE TITLE
[FEAT EXTRACTION] Is this a right way?

### ISSUE THREAD

**Issue by nightandweather** [Radiomics/pyradiomics#578]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

hello,
I'm interested in pyradiomics to classify my groundglassopacity dataset,
for example 

https://drive.google.com/open?id=1iwBYh9WJBHYn4odlSTJdLWv6A-E-ppeL

this folder contains image, mask file 

I downloaded your folder, looked at the feature extraction in the notebook folder, and followed it.
result was this

OrderedDict([('diagnostics_Versions_PyRadiomics', 'v3.0'),
             ('diagnostics_Versions_Numpy', '1.18.1'),
             ('diagnostics_Versions_SimpleITK', '1.2.4'),
             ('diagnostics_Versions_PyWavelet', '1.0.0'),
             ('diagnostics_Versions_Python', '3.6.10'),
             ('diagnostics_Configuration_Settings',
              {'minimumROIDimensions': 2,
               'minimumROISize': None,
               'normalize': False,
               'normalizeScale': 1,
               'removeOutliers': None,
               'resampledPixelSpacing': None,
               'interpolator': 'sitkBSpline',
               'preCrop': False,
               'padDistance': 5,
               'distances': [1],
               'force2D': False,
               'force2Ddimension': 0,
               'resegmentRange': None,
               'label': 1,
               'additionalInfo': True,
               'binWidth': 25,
               'weightingNorm': None}),
             ('diagnostics_Configuration_EnabledImageTypes', {'Original': {}}),
             ('diagnostics_Image-original_Hash',
              'd16d7883f7f2c4e150708586cdc331f4c9dd672a'),
             ('diagnostics_Image-original_Dimensionality',###  **_'3D'),_**
             ('diagnostics_Image-original_Spacing', (1.0, 1.0, 1.0)),
             ('diagnostics_Image-original_Size', (4, 512, 512)),
             ('diagnostics_Image-original_Mean', 0.40504967433983774),
             ('diagnostics_Image-original_Minimum', 0.0),
             ('diagnostics_Image-original_Maximum', 1.0),
             ('diagnostics_Mask-original_Hash',
              '89659c19e852e769108b6ce99f9830a744599cb4'),
             ('diagnostics_Mask-original_Spacing', (1.0, 1.0, 1.0)),
             ('diagnostics_Mask-original_Size', _### **(4, 512, 512)),**_
             ### **_('diagnostics_Mask-original_BoundingBox', (0, 0, 0, 4, 512, 512)),_**
             ('diagnostics_Mask-original_VoxelNum', 262867),
             ('diagnostics_Mask-original_VolumeNum', 1),
            ###  **_('diagnostics_Mask-original_CenterOfMassIndex',
              (2.9944991193265036, 255.23273366379195, 255.4783217368479)),
             ('diagnostics_Mask-original_CenterOfMass',
              (2.9944991193265036, 255.23273366379195, 255.4783217368479)),_**
             ('original_firstorder_10Percentile', array(1.)),
             ('original_firstorder_90Percentile', array(1.)),
             ('original_firstorder_Energy', array(262154.5004389)),
             ('original_firstorder_Entropy', array(-3.2034265e-16)),
             ('original_firstorder_InterquartileRange', array(0.)),
             ('original_firstorder_Kurtosis', array(362.87269985)),
             ('original_firstorder_Maximum', array(1.)),
             ('original_firstorder_MeanAbsoluteDeviation', array(0.00484099)),
             ('original_firstorder_Mean', array(0.99757283)),
             ('original_firstorder_Median', array(1.)),
             ('original_firstorder_Minimum', array(0.08627451)),
             ('original_firstorder_Range', array(0.91372549)),
             ('original_firstorder_RobustMeanAbsoluteDeviation', array(0.)),
             ('original_firstorder_RootMeanSquared', array(0.99864383)),
             ('original_firstorder_Skewness', array(-19.01465529)),
             ('original_firstorder_TotalEnergy', array(262154.5004389)),
             ('original_firstorder_Uniformity', array(1.)),
             ('original_firstorder_Variance', array(0.00213796)),
             ('original_glcm_Autocorrelation', array(1.)),
             ('original_glcm_JointAverage', array(1.)),
             ('original_glcm_ClusterProminence', array(0.)),
             ('original_glcm_ClusterShade', array(0.)),
             ('original_glcm_ClusterTendency', array(0.)),
             ('original_glcm_Contrast', array(0.)),
             ('original_glcm_Correlation', array(1.)),
             ('original_glcm_DifferenceAverage', array(0.)),
             ('original_glcm_DifferenceEntropy', array(-3.2034265e-16)),
             ('original_glcm_DifferenceVariance', array(0.)),
             ('original_glcm_JointEnergy', array(1.)),
             ('original_glcm_JointEntropy', array(-3.2034265e-16)),
             ('original_glcm_Imc1', array(0.)),
             ('original_glcm_Imc2', array(0.)),
             ('original_glcm_Idm', array(1.)),
             ('original_glcm_Idmn', array(1.)),
             ('original_glcm_Id', array(1.)),
             ('original_glcm_Idn', array(1.)),
             ('original_glcm_InverseVariance', array(0.)),
             ('original_glcm_MaximumProbability', array(1.)),
             ('original_glcm_SumEntropy', array(-3.2034265e-16)),
             ('original_glcm_SumSquares', array(0.)),
             ('original_glrlm_GrayLevelNonUniformity', array(181866.92307692)),
             ('original_glrlm_GrayLevelNonUniformityNormalized', array(1.)),
             ('original_glrlm_GrayLevelVariance', array(0.)),
             ('original_glrlm_HighGrayLevelRunEmphasis', array(1.)),
             ('original_glrlm_LongRunEmphasis', array(40904.75677668)),
             ('original_glrlm_LongRunHighGrayLevelEmphasis',
              array(40904.75677668)),
             ('original_glrlm_LongRunLowGrayLevelEmphasis',
              array(40904.75677668)),
             ('original_glrlm_LowGrayLevelRunEmphasis', array(1.)),
             ('original_glrlm_RunEntropy', array(1.54233326)),
             ('original_glrlm_RunLengthNonUniformity', array(181248.36855739)),
             ('original_glrlm_RunLengthNonUniformityNormalized',
              array(0.7793951)),
             ('original_glrlm_RunPercentage', array(0.69185909)),
             ('original_glrlm_RunVariance', array(11815.63029311)),
             ('original_glrlm_ShortRunEmphasis', array(0.7241835)),
             ('original_glrlm_ShortRunHighGrayLevelEmphasis',
              array(0.7241835)),
             ('original_glrlm_ShortRunLowGrayLevelEmphasis', array(0.7241835)),
             ('original_glszm_GrayLevelNonUniformity', array(1.)),
             ('original_glszm_GrayLevelNonUniformityNormalized', array(1.)),
             ('original_glszm_GrayLevelVariance', array(0.)),
             ('original_glszm_HighGrayLevelZoneEmphasis', array(1.)),
             ('original_glszm_LargeAreaEmphasis', array(6.90990597e+10)),
             ('original_glszm_LargeAreaHighGrayLevelEmphasis',
              array(6.90990597e+10)),
             ('original_glszm_LargeAreaLowGrayLevelEmphasis',
              array(6.90990597e+10)),
             ('original_glszm_LowGrayLevelZoneEmphasis', array(1.)),
             ('original_glszm_SizeZoneNonUniformity', array(1.)),
             ('original_glszm_SizeZoneNonUniformityNormalized', array(1.)),
             ('original_glszm_SmallAreaEmphasis', array(1.4471977e-11)),
             ('original_glszm_SmallAreaHighGrayLevelEmphasis',
              array(1.4471977e-11)),
             ('original_glszm_SmallAreaLowGrayLevelEmphasis',
              array(1.4471977e-11)),
             ('original_glszm_ZoneEntropy', array(-3.2034265e-16)),
             ('original_glszm_ZonePercentage', array(3.80420517e-06)),
             ('original_glszm_ZoneVariance', array(0.)),
             ('original_gldm_DependenceEntropy', array(0.12455702)),
             ('original_gldm_DependenceNonUniformity', array(256437.66397836)),
             ('original_gldm_DependenceNonUniformityNormalized',
              array(0.97554149)),
             ('original_gldm_DependenceVariance', array(0.50879053)),
             ('original_gldm_GrayLevelNonUniformity', array(262867.)),
             ('original_gldm_GrayLevelVariance', array(0.)),
             ('original_gldm_HighGrayLevelEmphasis', array(1.)),
             ('original_gldm_LargeDependenceEmphasis', array(81.71887304)),
             ('original_gldm_LargeDependenceHighGrayLevelEmphasis',
              array(81.71887304)),
             ('original_gldm_LargeDependenceLowGrayLevelEmphasis',
              array(81.71887304)),
             ('original_gldm_LowGrayLevelEmphasis', array(1.)),
             ('original_gldm_SmallDependenceEmphasis', array(0.01244445)),
             ('original_gldm_SmallDependenceHighGrayLevelEmphasis',
              array(0.01244445)),
             ('original_gldm_SmallDependenceLowGrayLevelEmphasis',
              array(0.01244445))])

The thick part is the part I don't understand..
can you tell me how to set up the mask file?

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

**Comment by nightandweather** [comment]
ps. I don't understand why there are zero array values when I read radiomics.io...
is there well-explained paper?..

**Comment by nightandweather** [comment]
ps++ this url http://www.spl.harvard.edu/publications/bitstream/download/5270 (in notebook/FeatureVisualization.ipynb) dosen't work. can you upload another dataset?..

**Comment by fedorov** [comment]
Based on the output you provided, the intensities range in the region you are analyzing is 0.91372549, and the binWidth setting is 25. You should adjust binWith according to the intensity range in your data.

**Comment by fedorov** [comment]
> ps++ this url http://www.spl.harvard.edu/publications/bitstream/download/5270 (in notebook/FeatureVisualization.ipynb) dosen't work. can you upload another dataset?..

Thank you for reporting this. I am trying to figure out what happened and why this is broken.

**Comment by nightandweather** [comment]
thank you for your help
I misunderstood the feature extraction
i'll closed this issue

**Comment by Lee1025-cpu** [comment]
Hello, it's everything ok in your city? All the best to you guys!
And i just encounter this data problem https://github.com/AIM-Harvard/pyradiomics/issues/578#issuecomment-631503916. I think I will appreciate it if you can just upload the data on line.

**Comment by Lee1025-cpu** [comment]
Hello, it's everything ok in your city? All the best to you guys!
And i just encounter this data problem https://github.com/AIM-Harvard/pyradiomics/issues/578#issuecomment-631271928 . I think I will appreciate it if you can just upload the data on line.
