### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by nightandweather** [Radiomics/pyradiomics#581]
**Describe the bug**
A clear and concise question regarding your extraction. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your question has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log related to your question. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**
Add any other context about your question here.

![{5A028B15-FE0E-4A39-A75F-70348308ADB1} png](https://user-images.githubusercontent.com/48376964/82992048-1e715c80-9fee-11ea-81f8-4c6ef6f21132.jpg)

image array i,      (i = j),a=0                                      
p(i,j) = pixel value i in image, delta = 1,  
 j,j,j
 j,i,j   it means p(i,j)= 2?
 j,j,j                                                              

if am i wrong, ..
how can i calculate grey level dependence matrix?

Am I right to understand?

**Comment by JoostJM** [comment]
I'm afraid I don't really understand your explanation.

Reasoning from the gldm matrix, of size (I, j): the (I, j)th element indicates the number of voxels that occur in the image with gray value I and dependence size j (= the number of neighbors with gray value differing less than delta from the center voxel)

E.g. i=5, j=3, P(i,j)=2, delta=1: there are 2 voxels with gray value 1 having 3 neighboring voxels that have a gray value >= 4 and <= 6.
