### ISSUE TITLE
Runtime error: label not present in mask

### ISSUE THREAD

**Issue by AT3432984** [Radiomics/pyradiomics#583]
I have just tried to run the pyradiomics software with an original image and a mask generated using BET in the FSL software and I am getting the following error:

    raise ValueError('Label (%g) not present in mask. Choose from %s' % (label, labels[labels != 0]))
ValueError: Label (1) not present in mask. Choose from [  31   32   33 ... 4113 4147 4219]

Any ideas on how I can fix this?

**Comment by fedorov** [comment]
From what I recall, BET zeroes out voxels outside of the brain region, but does not change intensities within the brain. You need to threshold your image to assign consistent label to the voxels within the region, and pass the value of that assigned label to pyradiomics.

You may find it helpful to visualize the image and mask before using pyradiomics for feature extraction. We recommend [3D Slicer](https://slicer.org) for such visualizations.
