### ISSUE TITLE
Running batch mode from the command line, column heading error

### ISSUE THREAD

**Issue by AT3432984** [Radiomics/pyradiomics#584]
Hello,

I am trying to run Pyradiomics using the batch mode in the command line. I have typed in the following:

pyradiomics <path/to/image> <path/to/output>

I am getting the following error:
E: radiomics.script: Required column "Image" not present in input, unable to extract features...

My input file is a csv file which contains 2 columns; the image and the mask. The first cell of each column contains the headings "Image" and "Mask", and the rest of the rows below contain the paths to the files.

Has anyone else had this problem? 

Thanks

**Comment by JoostJM** [comment]
What is the list separator character used? PyRadiomics expects this to be `,`. You can visualize this by opening the file using a simple text editor (e.g. notepad). Be aware that PyRadiomics is also case-sensitive for the column headers.

**Comment by AT3432984** [comment]
The separator that is used is a comma. These are the first 2 lines in my csv file:

Image,Mask
C:\Users\atamb\Desktop\MRIs\T1_mask\T1Images\ACC_T1.nrrd,C:\Users\atamb\Desktop\MRIs\T1_mask\T1Masks\ACC_T1_brain_mask.nrrd

**Comment by JoostJM** [comment]
Did you specify the `-o` parameter before the path to output? This is required when running PyRadiomics, otherwise it might be confused with running in single case extraction mode.

**Comment by AT3432984** [comment]
Yes, the syntax I used is:

pyradiomics C:\Users\atamb\Desktop\MRIs\t1_batch.csv -o results.csv -f csv

where t1_batch.csv is my input file

I got this from https://pyradiomics.readthedocs.io/en/latest/usage.html, am I doing something wrong here?

**Comment by JoostJM** [comment]
Yes that is correct. What version of PyRadiomics and Python are you using?
If I copy the line you posted, I am unable to reproduce the error. Can you share the actual csv file you use? I don't need the image/mask files themselves.

**Comment by JoostJM** [comment]
What happens if you try the `testCases.csv` file included in the repository (under `examples`)?

**Comment by AT3432984** [comment]
I couldn't attach a csv file so I have converted it to a tab delimited txt file:

[t1_batch.txt](https://github.com/Radiomics/pyradiomics/files/4739792/t1_batch.txt)

I tried the testCases.csv example and it works perfectly, so there is definitely just something wrong with my input file I think.

I'm wondering if maybe there's something wrong with how I have specified the paths (I have specified the full path)

**Comment by JoostJM** [comment]
Can you replace the following in `radiomics/scripts/__init__.py`? (L163-169)

original:
```
        # Check if required Image and Mask columns are present
        if 'Image' not in cr.fieldnames:
          self.logger.error('Required column "Image" not present in input, unable to extract features...')
          return None
        if 'Mask' not in cr.fieldnames:
          self.logger.error('Required column "Mask" not present in input, unable to extract features...')
          return None
```
replacement:
```
        # Check if required Image and Mask columns are present
        if 'Image' not in cr.fieldnames:
          self.logger.error('Required column "Image" not present in input (found %s), unable to extract features...', cr.fieldnames)
          return None
        if 'Mask' not in cr.fieldnames:
          self.logger.error('Required column "Mask" not present in input (found %s), unable to extract features...', cr.fieldnames)
          return None
```

This will at least print out what columns it *did* find in your CSV. I am starting to have an idea where it may be going wrong.

**Comment by JoostJM** [comment]
This is your file, comma delimited. Can you try it after changing the extension back to `.csv`?
[t1_batch.txt](https://github.com/Radiomics/pyradiomics/files/4739804/t1_batch.txt)

**Comment by AT3432984** [comment]
I changed the __init__.py file in this directory:

C:\Users\atamb\Anaconda3\Lib\site-packages\radiomics\scripts

and it didn't make a difference to the error. It is still saying:

(base) C:\Users\atamb\Desktop\MRIs>pyradiomics C:\Users\atamb\Desktop\MRIs\t1_batch.csv -o results.csv -f csv
[2020-06-06 20:11:42] E: radiomics.script: Required column "Image" not present in input, unable to extract features...

Maybe I am changing the wrong thing?

I also tried the file that you resent and it isn't working either. I might need to uninstall and reinstall pyradiomics and re-try it. I'm just not sure about this as it works fine when I run it for only one MRI

**Comment by JoostJM** [comment]
@AT3432984, Somehow it is reading your CSV file wrong. I don't really know where the error is located, as I'm unable to reproduce the error. My advice would be indeed to re-install pyradiomics and re-test. If that doesn't work, you could try to download the repository and run `python setup.py develop`, which installs pyradiomics to run form that repository, allowing you to debug more easily.

**Comment by AT3432984** [comment]
No worries, thank you so much for your help

**Comment by ZEGUK** [comment]
I have met the same problem when batch processing, and the one approach to solve it might be to **save the input csv file with UTF-8 code instead of  UTF-8 BOM.** (becasue I created the csv file by Excel ) It could be modified by save as in Notepad.  Hope Helpful!

**Comment by sam-mc1** [comment]
I had the same issue, I was saving the excel file as the wrong type of .csv file. Make sure to save it as "CSV (comma delimited) (*.csv)". There are a number of CSV types availble on Excel.

**Comment by saimasafdar2021** [comment]
I want to run pyradiomics using terminal for batch processing. any help?
