### ISSUE TITLE
[FEAT EXTRACTION] ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by NH333** [Radiomics/pyradiomics#589]
**Describe the bug**
When run the **firstorder.RadiomicsFirstOrder()** for some data Get **ValueError:** min() arg is an empty sequence.

**PyRadiomics configuration**
 settings = {'binWidth': 1,
            # 'interpolator': sitk.sitkBSpline,
            # 'resampledPixelSpacing': None
            }
firstorder_features = firstorder.RadiomicsFirstOrder(img,mask,**settings)
3D img(512*512*N) and 3D mask(512*512*N). 

**Version (please complete the following information):**
 - OS: win10
 - Python version: 3.7.7
 - PyRadiomics version v2.1.2

**Additional context**
PET data

**Comment by fedorov** [comment]
You are using a rather old version of pyradiomics - can you upgrade and try again? The latest version is v3.0.

**Comment by NH333** [comment]
I update the version to v3.0, It doesn't work, same error. 
I download the .zip file of pyradiomics from github, and use this three commands
(1. cd pyradiomics 2.python -m pip install -r requirements.txt 3.python setup.py install
in my anaconda environment) to install pyradiomics v3.0.

**Comment by NH333** [comment]
Maybe there's something unmatched wrong with my PET data.

**Comment by fedorov** [comment]
It could be, but still I don't understand why this error would come up for this specific feature.

Definitely it would be good to open the image and segmentation for a case that is failing, and look at the statistics inside that region. You can do this with [3D Slicer](https://slicer.org) Label statistics module.

**Comment by JoostJM** [comment]
@NH333, you implement the first order feature class directly, which skips a lot of checks. What do you get when you run this case using the feature extractor? This can be done easily via the PyRadiomics cmd line.

**Comment by JoostJM** [comment]
Stale

**Comment by noornk** [comment]
I'm having the same error, and I can't use the feature extractor directly, since my images are in Dicom and before feeding them into the extractor I need to turn them into NumPy.
