### ISSUE TITLE
How do we extract the features for each independent object in the image?

### ISSUE THREAD

**Issue by mozdag** [Radiomics/pyradiomics#591]
I have a tissue image and there are around 100 cells in it. I also have the corresponding mask image which includes those 100 cells. How do I calculate the radiomics features for each cell?

**Comment by fedorov** [comment]
You will need to make sure that each cell segmentation in your mask is assigned a unique label, and extract features for each label value separately.

**Comment by mozdag** [comment]
> You will need to make sure that each cell segmentation in your mask is assigned a unique label, and extract features for each label value separately.

Thank you  for your response. Could you please guide me through that process? For example, I am using the example code here: pyradiomics/examples/helloRadiomics.py

Where and what function should I update to assign a unique label to each cell segmentation in my mask?

**Comment by fedorov** [comment]
It's not a function of pyradimics, you need to do this before passing the mask to radiomics. 

I suggest you look into using this filter from SimpleITK: https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1RelabelComponentImageFilter.html.

It will be a good time investment to get familiar with the basics of SimpleITK here: https://simpleitk.readthedocs.io/en/master/.
