### ISSUE TITLE
[FEAT EXTRACTION] Ignoring empty mask files

### ISSUE THREAD

**Issue by FrankTN** [Radiomics/pyradiomics#596]
I have a CT dataset with masks. I am trying to produce 20 x 20 patches by sampling parts of the original masks. This is done to ensure consistent ROI size across all images (as also mentioned in #568). In some cases, I am unable to find a suitable patch. In this case, the resulting mask will be empty. When extracting features, the empty mask gives me the following exception ```ValueError: No labels found in this mask (i.e. nothing is segmented)!``` from ```imageoperations.py```. I could not find a setting to ignore this and continue with the other files. 

How can I deal with an empty mask in the series? Is there a setting to ignore empty masks (or could this be implemented?). Or do you suggest I do my own preprocessing first, to exclude the empty masks using `numpy.unique()`?

**Comment by jvanlunenburg** [comment]
So you're using a python script. You have some unknown process A that produces a set of masks, some of which may be empty. You don't remove those empty masks before attempting to iterate over your images/masks, expecting pyradiomics will give blank output for an invalid input? But it doesn't silently fail; it errors. This seems desirable behavior to me.  

As for a solution: have you considered putting the execute statement in your loop inside a try/catch block? This would allow you to complete processing the entire set, assuming that is the only source of error.

**Comment by FrankTN** [comment]
If you put it like this, it seems logical that it fails with an error. I was wondering whether it would make sense to add a setting to ignore empty masks, if this is a common occurrence/use case. I did not find any earlier issues about this, so I suppose it isn't. For now I will simply handle the empty masks using a try/catch or by filtering out the empty ones before.

**Comment by zacheidex** [comment]
I had the same issue running pyradiomics in the terminal. Adding the argument --skip-nans was an easy fix
