### ISSUE TITLE
[FEAT EXTRACTION] How do we verify/visualize for what feature values belong to which object in an image?

### ISSUE THREAD

**Issue by mozdag** [Radiomics/pyradiomics#605]
With the following code, when I have the feature values for each cell/object in the image, how can I verify and visualize for what feature values belong to which object in an image?

Nodules = []
for l in range(1, ccif.GetObjectCount() + 1):
  Nodules.append(extractor.execute(image, newMask, label=l))

**Comment by jvanlunenburg** [comment]
I don't think this is really related to pyradiomics? Have you looked at the matplotlib package for python?

**Comment by mozdag** [comment]
Hello, thank you for your answer. I visualized them with Fiji and mass center.
?? I have another question: ??
 do we need to specify to transform to grayscale first to calculate the features or Radiomics does it automatically?

**Comment by JoostJM** [comment]
@mozdag, sorry for the late reply. PyRadiomics requires the input image to be grayscale. The mask is allowed to have multiple channels, as this representations is used for segmentations (I.e  overlapping regions of interest).
