### ISSUE TITLE
[FEAT EXTRACTION]?DO we need to specify to transform to grayscale first to calculate the features or Radiomics does it automatically?

### ISSUE THREAD

**Issue by mozdag** [Radiomics/pyradiomics#606]
My images are color medical images with around 400 cells in it. Do we need to specify to transform to grayscale first to calculate the features or Radiomics does it automatically?

This is how I load them:
# Load original image
imageName = sitk.ReadImage('./tests/resource/TCGA-21-5786-01Z-00-DX1.png', sitk.sitkInt8)

# Load cell label
maskName = sitk.ReadImage('./tests/resource/TCGA-21-5786-01Z-00-DX1_bin_mask.png', sitk.sitkInt8)

**Comment by jvanlunenburg** [comment]
I think you should get an error when you try to execute the extraction. The documentation says:

>PyRadiomics currently does not provide extraction from color images or images with complex values. In those cases, each pixel/voxel has multiple values and PyRadiomics does not know how you’d want to combine those.

**Comment by mozdag** [comment]
> I think you should get an error when you try to execute the extraction. The documentation says:
> 
> > PyRadiomics currently does not provide extraction from color images or images with complex values. In those cases, each pixel/voxel has multiple values and PyRadiomics does not know how you’d want to combine those.

I do not get an error actually, my input images are color images (H&E stained).

**Comment by fedorov** [comment]
Yes, you need to first convert your H&E image into a single channel image, see https://pyradiomics.readthedocs.io/en/latest/faq.html?highlight=complex#what-modalities-does-pyradiomics-support-2d-3d-color.
