### ISSUE TITLE
Voxel based feature extraction question

### ISSUE THREAD

**Issue by AT3432984** [Radiomics/pyradiomics#609]
Hi,

I am relatively new to this and have very little programming experience. I have been extracting 2D features from the commandline in Anaconda. I wanted to try and extract some 3D features, but I can't seem to do so. I have tried typing:
pyradiomics mri.nrrd segmentation.nrrd --mode voxel
as well as:
pyradiomics mri.nrrd segmentation.nrrd -o results.csv -f csv --mode voxel

Neither of these seem to be working, am I doing something wrong? I am not getting an error message, it looks like it is still running though I have left it going for ages.

I have tried typing:
pyradiomics mri.nrrd mri.nrrd --mode voxel
and this works (using the original image as the mask), but I want to use the mask I created. 

Any help would be appreciated.

I am using Python 3.7.4

**Comment by jvanlunenburg** [comment]
You are mistaken in thinking "--mode voxel" means 3D features. For 3D features all you need is a 3D mask.

**Comment by rcuocolo** [comment]
If you do not have much programming experience, it could be easier to start by using the 3D Slicer extension as long as you work on single cases. After gaining some familiarity and optimizing the extraction for you use case the extraction parameters can be fairly easily brought over for batch extraction.

**Comment by AT3432984** [comment]
Thank you
