### ISSUE TITLE
Error with ruing pyradiomics

### ISSUE THREAD

**Issue by Saleh600** [Radiomics/pyradiomics#612]
Hi 
I have downloaded pyradiomics package, but I faced problem when when tried to run helloRadiomics from examples and I got the error as (ModuleNotFoundError: No module named 'imageoperations'). I tried that by using Spyder.

For installation 
I did as 
1- python -m pip install pyradiomics
2- git clone git://github.com/Radiomics/pyradiomics
3-cd pyradiomics
   python -m pip install -r requirements.txt
  python setup.py install
4- python setup.py build_ext --inplace
please can you help me with this issue.

**Comment by jvanlunenburg** [comment]
You don't need to clone the git repo to install. I think most people just use pip or conda.

If you ran pip you should already be able to import the module and use the functions.

**Comment by Saleh600** [comment]
Hi Jvanlunenburg
Thanks a lot for your message.
I have not tried that way, but I will.

**Comment by Saleh600** [comment]
Thanks a lot, I did, it work
