### ISSUE TITLE
[FEAT EXTRACTION] How does the voxel-based feature extraction deal with discretization bins bounds ? 

### ISSUE THREAD

**Issue by Thibescobar** [Radiomics/pyradiomics#614]
Hello. 

**Question**
I would like to understand how the voxel-based extraction deals with the discretization bins bounds.
I work with fixed bin size (size = 10) on CT images for the moment. 
When we do not apply a resegmentation range, or when the applied resegmentation range bounds is larger than the real continous values range of the image, I can see that the discretization is applied, from 0, so that the minimum and maximum bins of the image correspond to the values that the real minimum and maximum can be putted in. In this case, the discretized bins bounds can be different from an image to another, even if we apply resegmentation. This way, it avoids lots of potential zeros in the GLCM for example. Intuitively I would say that it is good since the goal of the features then extracted is to explore the informative information present in the image. So we want to avoid to introduce "useless" zeros in the GLCM for our analysis. 
But I am not very comfortable about how it is done in voxel-based extraction. Indeed, if we set the verbosity to the maximum, we can see that the discretization is done before the extraction of the multiple GLCM matrices (for each voxel and neighbors). So the GLCM matrices seems to have the same bins bounds for all the voxels in a patient. But we can imagine that in a very local environment in a tumor (voxel and neighbors), lots of bins will be empty and so the GLCM will contain the "useless" zeros previously mentioned ? 
Can you help me understanding this choice in fixing the bins bounds between voxels but not between patients please ? or can you explain if I misunderstand anything ? 
I ask this because I would like to fit a voxel-based machine learning model, so I would like voxels inside a same patient to be comparable but also voxels between patients.

Thank you very much in advance. 

**PyRadiomics configuration**
imageType:
  Original: {}

setting:
  binWidth: 10
  resampledPixelSpacing: [1, 1, 1]
  preCrop: True
  padDistance: 20
  resegmentRange: [-10, 60]
 
featureClass:
    glcm: []

voxelSetting:
  kernelRadius: 4
  maskedKernel: True
  initValue: 0
  voxelBatch: 30000

**PyRadiomics log file with no resegmentation range**
[Log_no_reseg.txt](https://github.com/Radiomics/pyradiomics/files/4981922/Log_no_reseg.txt)

**PyRadiomics log file with large resegmentation range**
[Log_large_range_reseg.txt](https://github.com/Radiomics/pyradiomics/files/4981923/Log_large_range_reseg.txt)

**PyRadiomics log file with thin resegmentation range**
[Log_thin_range_reseg.txt](https://github.com/Radiomics/pyradiomics/files/4981927/Log_thin_range_reseg.txt)

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: Python 3.6.10 :: Anaconda, Inc.
 - PyRadiomics version: pyradiomics v3.0

**Comment by jvanlunenburg** [comment]
You imply that a sparse GLCM is a bad thing ("useless zeros"). Can you explain why? It is in theory possible to do per-neighborhood binning, but I'm not sure what the benefit would be. Most neighborhood aren't very large, so you'd still end up with a sparse GLCM unless you discretize with a very low bincount.

> I would like voxels inside a same patient to be comparable but also voxels between patients

Then using the same bins for each voxel, as it currently does, is appropriate.

If you are worried about different interpatient CT ranges causing binning variation, then just normalize the CTs? Assuming they're all in HU you could do simple linear normalization.

Alternatively, using binwidth instead of bincount might mitigate radiomic variance, but then some patients will have more bins than others.

**Comment by Thibescobar** [comment]
Hello, thank you very much for your answer. 

> You imply that a sparse GLCM is a bad thing ("useless zeros"). Can you explain why?

I didn't mean to say it's a bad thing, I misspoke sorry (I am french). To explain myself, let's place ourselves in a context of global / whole tumor extraction of features (not voxel-wise), with a fixed bin size to study heterogeneity at the same contrast scale:

I have observed that the binning is done in such a way that the minimum and the maximum after binning correspond to nonempty bins, regardless of the range of resegmentation values ​​chosen. So if the range of values ​​of an image is included in the chosen resegmentation range, the minimum bin and the maximum bin of the image **after bining** do not correspond to the chosen resegmentation value range, but rather the minimum and maximum of the "binned" version of the image. This means that from one image to another in the cohort, the GLCMs do not have the same dimensions (number of bins).

Intuitively, I would say that the zeros that are present in the GLCMs in that way are therefore informative since they mean "the two values ​​are not adjacent (for d = 1) although they are present in the image", which is an goal of the GLCM. 

If all GLCMs had been "forced" to have the same dimensions, a "new type" of zeros would be present in many of them, since the large number of empty bins would obviously have resulted in the fact that the probability of find a absent value in the image, adjacent to some other value, is obviously zero. Hence my term in quotes : "useless", not meaning that a sparse GLCM is a bad thing.  

These facts make me think it is not necessary to have GLCMs of the same dimensions between images to compare them / their features. But maybe I misunderstand something ...


Now if we come back in the voxel-wise context : 

In voxel-based extraction, the previously mentioned "patient-level" binning is done first and so all patients do not have the same number of bins. Then, the GLCMs are calculated with the same dimensions for all voxels neighborhood in the image, so as you said, using the same bins for each voxel in a given image. 


My question was to understand why at the patient level the GLCMs do not have necessarily the same dimensions but at the voxel level they do ? 
Another thing, looking at the formulas of some GLCM features, since the majority of them seems to deal with non-empty bins, maybe all of this has no effects on the features and I ask myself useless questions ? 

> If you are worried about different interpatient CT ranges causing binning variation, then just normalize the CTs? Assuming they're all in HU you could do simple linear normalization.

I prefer not because it will erase the absolute variations between patients. 

Thank you again.

**Comment by Thibescobar** [comment]
> You imply that a sparse GLCM is a bad thing ("useless zeros"). Can you explain why? It is in theory possible to do per-neighborhood binning, but I'm not sure what the benefit would be. Most neighborhood aren't very large, so you'd still end up with a sparse GLCM unless you discretize with a very low bincount.
> 
> > I would like voxels inside a same patient to be comparable but also voxels between patients
> 
> Then using the same bins for each voxel, as it currently does, is appropriate.
> 
> If you are worried about different interpatient CT ranges causing binning variation, then just normalize the CTs? Assuming they're all in HU you could do simple linear normalization.
> 
> Alternatively, using binwidth instead of bincount might mitigate radiomic variance, but then some patients will have more bins than others.

**Comment by jvanlunenburg** [comment]
I haven't looked at the code for voxel-based extraction, but I imagine each nhood glcm is the same size as the whole-image glcm for that patient. Or are you saying neighborhood glcms _between_ patients are the same size? 

Assuming the former case, you want to know why this is done as opposed to re-binning per-nhood? In the case of **bin-width**, I think they are equivalent, trailing/leading zeros in the texture matrix would be cropped but the radiomic features probably aren't affected by that.

**Comment by Thibescobar** [comment]
> I haven't looked at the code for voxel-based extraction, but I imagine each nhood glcm is the same size as the whole-image glcm for that patient. Or are you saying neighborhood glcms between patients are the same size?

Yes, between patients, dimensions are different, and between voxels in a patients, they are the same no matter the values present in the nhood. 

> Assuming the former case, you want to know why this is done as opposed to re-binning per-nhood? 

Yes that was my question. 

> In the case of bin-width, I think they are equivalent, trailing/leading zeros in the texture matrix would be cropped but the radiomic features probably aren't affected by that.

I am using bin-width so you answered my question. It is true that if we look at the features formulas, the zeros seems to have no effects. 


Thank you very much for your help.

**Comment by JoostJM** [comment]
Sparisty in the GLCM matrices has absolutely no effect on the feature values themselves, it only adds more computation time. Indeed as a performance measure, "empty gray values" are removed after matrix calculation but before feature calculation.

In most GLCM features the offset of the bin values (i.e. whether or not there are leading bins) does not matter (as they are often dealing with some form of describing variation and look at the difference of `i` and `j` and not really the value of `i` and `j` themselves). However, for some features there is an influence of the absolute value of `i` / `j` (most obvious being JointAverage and Autocorrelation). Still, in these latter cases it is only the number of leading bins that is of any influence and it does present us with a certain problem of defining how to arange the bins. The main constraints are that `i` is not allowed to be negative, so simply orienting them around 0 does not work. 

Even using the resegmentation lowerbound would only work for the original image, as filters can alter the intensities in such a way that they fall outside the resegmentation range. You could re-apply resegmentation but 1) that's not what resegmentation is for (it's to exclude outlier/invalid values in the original data) and 2) would require you to specify custom resegmentation range for every filter (and subfilter, e.g. LHL in Wavelet). 

Therefore, in PyRadiomics we opted for a sort of compromise. Bins defined using a fixed bin width / size are aranged so, that the first bin will contain the minimum value in the image (be it the original or a filtered one), with additional alignment to 0 (i.e. the lower edge is always divisable by the binwitdh. This ensures that gray values are always perfectly aligned, even between patients, though the actual value of `i` associated with that bin may differ.
This approach means that texture features in PyRadiomics will only contain information about the contrast between gray values, and not their absolute magnitude (which would require some constant value to determine where to start the bin range). IMHO, the ignoring of the absolute magnitude is actually not a weakness of the features but more a strength, as with texture we're most interested in spatial contrast, and not so much the magnitude. If the absolute magnitude is important for the model we want to build using the radiomics features, that information is encoded in the first order features and can be incorporated in the model that way.

**Comment by Thibescobar** [comment]
Thank you very much for your perfectly clear and complete answers. It is very more clear for me now.
