### ISSUE TITLE
Different size of cropped image for different kernel radius in voxel-wise extraction [FEAT EXTRACTION]

### ISSUE THREAD

**Issue by kingaber** [Radiomics/pyradiomics#616]
**Describe the bug**
I am extracting texture feature maps using the voxel setting of PyRadiomics for a single lesion in a single CT image.
I use two configuration files, differing the kernel Radius. The resulting texture feature maps (here e.g. ngtdm_Busyness) have different size, in my case: (67,88,132) and (69,90,134) for kernel radius 1 and 2. In order to match size of the output features I have to extend the outputs by adding a padding of Nan values around, with the extension equal the maximum difference in evaluated kernels. E.g. if Radius 1 then we have 3x3x3 kernel and for radius=2 the kernel is 5x5x5, so the extension needed is the difference beween 5-3 = 2. In my case I would then match all outputs to (69,90,134) size. Is that correct? Or is there a better way?

**Comment by JoostJM** [comment]
The resultant feature maps contain geometric information the ensure correct alignment. If you view them in e.g. 3d Slicer, the will align correctly (even with the original image).
If you want to compare the values, the easiest way to achieve this is to resample the larger one to the geometry of the smaller one using sitkNearestNeighbor (this does not alter the values, and the voxels are already aligned, just with additional padding).

```
import SimpleITK as sitk

t1 = sitk.ReadImage('texturemap_large.nrrd')
t2 = sitk.ReadImage('texturemap_small.nrrd')

rif = sitk.ResampleImageFilter()
rif.SetInterpolator(sitk.sitkNearestNeighbor)
rif.SetReferenceImage(t2)

t_new = rif.Execute(t1)
# t_new is the larger texture map values, in the geometric space of the smaller image
# t_new and t2 arrays can be compared directly.
```

**Comment by JoostJM** [comment]
This approach works even when you want to compare to your original image. It also works the other way around, with the additional voxels receiving a value of '0'.

Most importantly, it does not require you to think about alignment, origins, directions, but uses the information already stored in the texture maps' geometric metadata, thereby preventing misalignment errors.

**Comment by kingaber** [comment]
Good idea!
Thanks for your help and prompt reply.
