### ISSUE TITLE
arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by Yonhoo** [Radiomics/pyradiomics#618]
I adjust my origin data and mask data with same data type 32-bit signed integer;but still have error :IndexError: arrays used as indices must be of integer (or boolean) type;i don't konw how to fix it ;or there have some request in data type

**Comment by JoostJM** [comment]
This is a duplicate issue of #592, which is fixed in #594. However, though part of the current master, it is not yet part of the official release.

**Comment by Yonhoo** [comment]
i think it is not work when i add discretizedParameterMatrix.astype('int')

**Comment by JoostJM** [comment]
@Yonhoo, that is correct, the fix has to be applied elsewhere. Apply the changes in #594 to fix this.

**Comment by wrrogers** [comment]
I've encountered the same problem in version 3.0.  Is there some kind of workaround for the time being?

**Comment by JoostJM** [comment]
@wrrogers, I've just made a new release, version 3.0.1. There were some issues with CI, but I managed windows, mac and linux for python 3.6 and 3.7. Python 3.5 version currently only for linux. Is your version in there?
