### ISSUE TITLE
run time too long ；beyond 4 hours and not finish when compute features

### ISSUE THREAD

**Issue by Yonhoo** [Radiomics/pyradiomics#620]
when i put my origin data .nii and mask .nii into feature compute function;it runing too long time and not finished ; i found out this array self.P_glcm  size is 174240000 which that function is _calculateCoefficients in glcm.py  ; it appears that too big ;so computing unfriendly  when i debug this；so Is there anything wrong here？

**Comment by JoostJM** [comment]
The size of the GLCM is dependent on the largest zone size, the number of (discretized) gray values in your image and, if you compute voxel-based, the number of voxels in one batch (by default, all voxels, equal to the number of segemented voxels in your mask).

To reduce size, decrease the number of bins (increas bin width) or decrease the number of voxels calculated in one batch.

Be aware that with large images, voxel-based radiomics is inherently slow (many computations). There already have been some efforts in improving this (calculating matrices for multiple voxels simulatneously is one of them), but it is an ongoing process.
