### ISSUE TITLE
[FEAT EXTRACTION] Quick question about how to extract GLCM matrices directly but not the GLCM features

### ISSUE THREAD

**Issue by Haoxin22** [Radiomics/pyradiomics#621]
**Version (please complete the following information):**
 - OS: Linux 16.04
 - Python version: 3.6
 - PyRadiomics version v3.0.post9+g51639ec'

**Additional context**

Hi,

Hope you are doing well. 

Normally, we can use FeatureExtractor.execute() to extract GLCM features. But I'd like to ask how to extract the **GLCM matrices** in Pyradiomics directly but not the GLCM features? Thank you so much.

Best,
Haoxin

**Comment by JoostJM** [comment]
That is not directly possible in PyRadiomics, though you could get them if you feel comfortable diving into the source code itself.
The easiest way to achieve your goal would be to create a custom feature returning the GLCM matrices and i vector (indicating the gray values associated with the i/j index of the matrix). In the developer section of the documentation you can read how to add your own feature.

This way, you can preserve the entire PyRadiomics pipeline and abstractions. The matrices will then be returned in the dictionary containing the calculated results.

Be aware that the matrices returned have shape (Nvox, Ng, Ng, Na); voxels (=1 if calculating segment-based), number of discretized gray values and number of directions (usually 13 in case of 3D extraction)

If you need any help, please let us know.

**Comment by Haoxin22** [comment]
Thank you so much! I'll try.
Please take a look at my other question regarding the normalization and discretization if you have time :)

Really appreciated
