### ISSUE TITLE
[FEAT EXTRACTION] Discretization after z-score normalization

### ISSUE THREAD

**Issue by Haoxin22** [Radiomics/pyradiomics#622]
**Version (please complete the following information):**
OS: Linux 16.04
Python version: 3.6
PyRadiomics version v3.0.post9+g51639ec

**Additional context**
Hi,

I have a question regarding the pre-preprocessing part referring the link below:

https://discourse.slicer.org/t/image-processing-steps-order-when-using-the-settings-in-the-parameter-file/11228

Question: If I do normalization using default z-score methods, which means scale = 1:
![image](https://user-images.githubusercontent.com/35722428/89238919-86bf5a00-d5ac-11ea-97f5-4408d05cac40.png)

Then how would the **fixed binwidth** discretization (which is the default discretization method) be implemented after the normalization?

Since the gray-level value after the normalization are kind of majorly allocated between value -1~1, if now I set the BinWidth = 15, what would happen? Is there only one bin there? Does that mean if I want to set the BinWdith to 15, I need to somewhat set the scale parameter in normalization to be sth. higher than 15 so that it could be multiple bins?

Thanks! 
Haoxin

**Comment by Haoxin22** [comment]
Additionally, If after the normalization with scale 100, how would the binWidth-based discretization treat the negative value? 

Thanks

**Comment by JoostJM** [comment]
The majority of normalized values will be in range (-3, 3), and a bin width of 15 will mean most likely only 2 bins (one with negative values and one with positive values). You could indeed increase the scale to get more bins, or simply reduce the bin width (it's a float value, so it can be fractional and < 1). 

I've found that a scale of 100 usually works well with a bin width of 5 (and therefore BW 0.5 ~ scale 10, BW 0.05 ~ scale 1). However, best is to check using e.g. firstorder range feature with normalization switches one. The aim is to have about 10 to 100 bins for most of your cases.

**Comment by JoostJM** [comment]
Negative values are no problem, it just means that the binned range starts somewhere negative (first value smaller than the minimum value and equally spaced from 0).

**Comment by Haoxin22** [comment]
Thank you so much. One more question, is the implementation of separating the bins done by setting the boundary when mod(x)==0? 

Thanks!

**Comment by JoostJM** [comment]
@Haoxin22. Yes, though I'm currently not entirely sure which specific implementation I use, just that negative values are handled correctly.
