### ISSUE TITLE
brain1_image.nrrd    brain1_label.nrrd

### ISSUE THREAD

**Issue by PP-YE** [Radiomics/pyradiomics#623]
brain1_image.nrrd， brain1_label.nrrd,  this is two type files in  test data, what do they represent and what is the difference between them, how can I get them from medical imaging

**Comment by JoostJM** [comment]
You can visualize the data in brain ik image and label using e.g. slicer.

Image is the image, I.e. the stack of MRI slices converted from DICOM into format PyRadiomics can use. Label or mask is an image which identifies the region of interst in the image by setting the corresponding pixels to some value, e.g. "1", with "0" being the background.

If this is very new to you, my advise would be to start with PyRadiomics using the SlicerRadiomics extension in 3D Slicer, as you can directly visualize the image and label/mask that is used to extract features. Once you get a better feel for how it works, you can use the standalone version to easily extract features for a batch of cases.

**Comment by PP-YE** [comment]
@JoostJM thank you for your replies.
