### ISSUE TITLE
A different number of features were extracted with the same code! Is Pyradiomics reproducible? 

### ISSUE THREAD

**Issue by hmoradmand** [Radiomics/pyradiomics#624]
Hello,
I used pyradiomics last year and it worked fine, however, this time when I used it again, I encountered two problems.

1.  `settings = {}
settings['binWidth'] = 25
settings['resampledPixelSpacing'] = None  # [3,3,3] is an example for defining resampling (voxels with size 3x3x3mm)

extractor = featureextractor.RadiomicsFeaturesExtractor(**settings)
#extractor.enableAllImageTypes()
extractor.enableImageTypes(Original={}, LoG={'sigma' : [1.0,2.0]}, Wavelet={},LBP2D={},
                           LBP3D= {},Square= {}, SquareRoot= {})

print('Enabled features:\n\t', extractor._enabledFeatures)
print('Enabled Images:\n\t',extractor._enabledImagetypes)`

The above code I 've employed last year and worked fine but as I run it again (I have changed RadiomicsFeaturesExtractor(**settings)  to RadiomicsFeatureExtractor(**settings)) I faced this Error !!!
AttributeError                            Traceback (most recent call last)
<ipython-input-5-8f19ffecdabc> in <module>
     14                            LBP3D= {},Square= {}, SquareRoot= {})
     15 
---> 16 print('Enabled features:\n\t', extractor._enabledFeatures)
     17 print('Enabled Images:\n\t',extractor._enabledImagetypes)

AttributeError: 'RadiomicsFeatureExtractor' object has no attribute '_enabledFeatures'

2-The main problem is that the number of features I had extracted last year (1461 features) is different from the number I able to extract now (about 1319 features).

I really appreciate it if you could let me know the cause of these differences.
Thank you in advance for your help.

**Comment by JoostJM** [comment]
Checkout the release notes on the online documentation, which details the changes made in each new release. The errors you encounter are part of this and should be listed there.

**Comment by JoostJM** [comment]
These also include new features, as well as any changes that affect the calculated outcome. PyRadiomics is compared to a fixed baseline upon each and every change made to the code.

**Comment by hmoradmand** [comment]
Thank you very much for your help.
I realized that this difference was occurred due to LBP 3D and their related packages.
