### ISSUE TITLE
Don't understand 'diagnostic-minimum' values for PyRadiomics applied to PET

### ISSUE THREAD

**Issue by tyusufaly** [Radiomics/pyradiomics#626]
I am using PyRadiomics latest version on PET DICOMs, and if I just look at the 'Diagnostics' features, specifically the minimum, I get one of two things:

1) Minimum is 0.
2) Minimum is around -30000.

This dichotomy holds whether I use the original image, or resample it, or bin it, whatever. Can someone please explain what this minimum feature and why it is sometimes 0 and sometimes negative?

Thank you.

**Comment by JoostJM** [comment]
That feature returns the minimum value in the entire image (not just the region identified by the mask). This means that somewhere in your image, there is at least 1 pixel with that value. Why this is the case, I don't know. Most likely it is somewhere outside the body, but you'd have to investigate that if you want to be sure.
