### ISSUE TITLE
Specifications were found to be incompatible with your CUDA driver

### ISSUE THREAD

**Issue by TheNewestNewbie** [Radiomics/pyradiomics#627]
Hi,

When I try to install the package through conda, using the commands in the documentation, I am getting the following error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyradiomics -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked
 for.
When python appears to the right, that indicates that the thing on the left is s
omehow
not available for the python version you are constrained to. Note that conda wil
l not
change your python version to a different minor version unless you explicitly sp
ecify
that.

The following specifications were found to be incompatible with your CUDA driver
:

  - feature:/win-64::__cuda==9.1=0
  - feature:|@/win-64::__cuda==9.1=0


Your installed CUDA driver is: 9.1
```
Has this occurred before? I could not find any known solutions in the previous questions posted.

Many thanks

**Comment by JoostJM** [comment]
Duplicate to #603 
CUDA is not used by PyRadiomics, I don't know why it is showing up in your error message (the error is above, pyradiomics is not available as a Conda package for the python version you are trying to install it for).

Currently, PyRadiomics Conda distribution is experiencing errors. However, it is still available for many distributions (up to python 3.7) on PyPi (i.e. `pip` installable).
