### ISSUE TITLE
Wavelet Image output

### ISSUE THREAD

**Issue by cxue21** [Radiomics/pyradiomics#630]
Is there any way I could output the wavelet image generated by pyradiomics?

**Comment by JoostJM** [comment]
Not as part of the current workflow, no. The wavelet is calculated by the `imageoperations.getWaveletImage()` function, which takes  a SimpleITK image and mask (though the mask is not used and just returned), in addition to `**kwargs`, which contain the settings for the wavelet filter (e.g. `level`, `wavelet`), which revert to default if omitted.

This function returns a generator (so put the result in a loop). On each iteration, you get a tuple with image (as SimpleITK.Image), image name and kwargs dict.

**Comment by cxue21** [comment]
got it. Thank you very much!
