### ISSUE TITLE
Question for NGTDM documents

### ISSUE THREAD

**Issue by LiJiaqi96** [Radiomics/pyradiomics#632]
Hello, thanks for your documents of pyradiomics package. It really helps!

While reading the NGTDM part (https://pyradiomics.readthedocs.io/en/latest/features.html#module-radiomics.ngtdm), I have a question about the example. For calculation of s_2 (gray level 2), the document shows:

s2=|2−15/5|+|2−15/5|=2

But I think the second element should be |2-9/3| as the neighbors for the 2nd pixel with gray level 2 are: 1,3,5. Their sum is 9 and the count is 3.

Could you please tell me whether I am right? Thanks.

**Comment by JoostJM** [comment]
@LiJiaqi96, That is correct, I'll update the documentation.

Thanks for the catch.
