### ISSUE TITLE
How to extract 3D dosimetry features using pyradiomics?

### ISSUE THREAD

**Issue by zhangji1234** [Radiomics/pyradiomics#633]
In the course of research, I found some researchers can extract of 3D dosimetry features in radiotherapeutics by using pyradiomics.
What I'm asking is, I'd like to ask how pyradiomics can be used to extract 3D dosimetry features.
Thanks!

**Comment by JoostJM** [comment]
Dosimetry in DICOM can be converted to gray scal images readable by SimpleITK (and hence, usable in PyRadiomics). You can treat them as you would any other gray scale image, i.e. segment the region of interest and extract the features.
