### ISSUE TITLE
[BUG] ValueError: mask has too few dimensions (number of dimensions 1, minimum required 2)

### ISSUE THREAD

**Issue by LAUBENicolas** [Radiomics/pyradiomics#640]
**Description of the bug**

Hello,
I'm trying to extract firstorder and GLCM features from numpy arrays (corresponding to 2d images of CT scans whose shape is 512*512).
However I get this error:
`raise ValueError('mask has too few dimensions (number of dimensions %d, minimum required %d)' % (ndims, minDims))
ValueError: mask has too few dimensions (number of dimensions 1, minimum required 2)`
For some images, everything works fine.

I checked the dimension of the sitk_image given as input and it is equal to 2.

**PyRadiomics configuration**
No paremeters file was used.

**To Reproduce**

Here is what I am doing:
`features = ["original_glcm_Correlation", "original_glcm_Contrast", "original_glcm_JointEnergy", "original_glcm_Id"]`

`model = featureextractor.RadiomicsFeatureExtractor()`

`model.disableAllFeatures()`

`model.enableFeatureClassByName("glcm")`

`model.enableFeatureClassByName("firstorder")`

`sitk_image = sitk.GetImageFromArray(image)`

`sitk_mask = sitk.GetImageFromArray(mask)`

`extracted_features = model.execute(sitk_image, sitk_mask)`

**Version (please complete the following information):**
 - OS: Win10
 - Python version: 3.7
 - PyRadiomics version: 3.0

**Comment by JoostJM** [comment]
@LAUBENicolas, this is not a bug, but rather a problem of your segmentation.

The number of dimensions the error refers to is not the dimensions of the image, but rather the ROI you indicated in your mask file. As shown by the error, it has only one dimension, meaning your ROI consists of several voxels in a single line (often just 2 voxels), which generally indicates the ROI is simply too small to extract meaningful texture features.

These checks can be customized via the [PyRadiomics settings](https://pyradiomics.readthedocs.io/en/latest/customization.html#feature-extractor-level), see section on mask validation.

Finally, be aware that these checks are applied AFTER any resampling. So even if you have valid masks in the original spacing, it is possible they are no longer valid if resampling to a too-large pixel spacing causes the mask to contain too few voxels.

**Comment by LAUBENicolas** [comment]
Thank you very much for your answer

**Comment by AnkushJamthikar** [comment]
Thank you for your answer. But I still did not get this. In my case, I have an 8 by 8 image and the corresponding mask. My mask looks like as follows

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0 255 255 255 255]
 [  0   0   0   0 255 255 255 255]
 [  0   0   0   0 255 255 255 255]
 [  0   0   0   0 255 255 255 255]
 [  0   0   0   0 255 255 255 255]
 [  0   0   0   0 255 255 255 255]
 [  0 255 255 255 255 255 255 255]]

following are my settings 
 binWidth: 1
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [0.5, 0.5]
  weightingNorm: 'manhattan'
  resegmentRange: [15.0]
  resegmentMode: 'absolute'

why I am getting the following error

`Resegmentation excluded too many voxels with label 255 (retained 0 voxel(s))! Cannot extract features`


Can you please help me to understand this issue?
