### ISSUE TITLE
error in installing PY-RADIOMICS 

### ISSUE THREAD

**Issue by adamxr** [Radiomics/pyradiomics#641]
I'm installing Py Radiomics from the source on my desktop, 
Python and Git latest version installed and when I'm running the command 
`python -m pip install -r requirements.txt`
I'm getting an error 
`$ python -m pip install -r requirements.txt
bash: /c/Users/HANY/AppData/Local/Microsoft/WindowsApps/python: Permission denied
`

**Comment by JoostJM** [comment]
The error you are describing is an access problem. The python process apparantly has no access to the folder where it is attempting to install the requirements. Have you tried installing any other python packages?

Where is your python installed and do you have access to that folder? A potential solution may be to add `--user` to the pip installation, causing it to be installed in your user folder (though it sort-of already seems that way...)
