### ISSUE TITLE
[BUG]ImportError: cannot import name 'getFeatureClasses' from 'radiomics' (unknown location)

### ISSUE THREAD

**Issue by ctwangtz** [Radiomics/pyradiomics#647]
**Describe the bug**
A clear and concise description of what the bug is. Please check [FAQ section](https://pyradiomics.readthedocs.io/en/latest/faq.html), PyRadiomics issues and [PyRadiomics Slicer Discourse](https://discourse.slicer.org/c/community/radiomics/23) to check if your bug has been encountered before. If so, but you still require additional help, please reference related issues.

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log showing your error. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Expected behavior**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**

**Comment by JoostJM** [comment]
Can you add some additional information (preferably the stack trace that ended with this error)

Can you import `featureextractor` from `radiomics`? It is possible you have a second package `radiomics` installed, which does not have these attributes. If that is so, please uninstall that package to allow Python to discover the correct pyradiomics package via `import radiomics`

**Comment by ctwangtz** [comment]
> e additional information (preferably the stack trace that ended with this error)
> 
> Can you import `featureextractor` from `radiomics`? It is possible you have a second package
That problem had been solved.

What do the following warnings mean? How to solved it?
Calculating Local Binary Pattern in 2D, but extracting features in 3D. Use with caution!
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

**Comment by ctwangtz** [comment]
> Can you add some additional information (preferably the stack trace that ended with this error)
> 
> Can you import `featureextractor` from `radiomics`? It is possible you have a second package `radiomics` installed, which does not have these attributes. If that is so, please uninstall that package to allow Python to discover the correct pyradiomics package via `import radiomics`

That problem had been solved.

What do the following warnings mean? Are there some influences to results? How to solved it? 
Calculating Local Binary Pattern in 2D, but extracting features in 3D. Use with caution!
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

**Comment by JoostJM** [comment]
Both are warnings and not errors. 

> Calculating Local Binary Pattern in 2D, but extracting features in 3D. Use with caution!

This reflects your settings. PyRadiomics contains both the 'regular' local binary pattern, which is only defined in 2D, and local binary pattern 3D, which uses spherical harmonics. This warning is shown when using LBP in 2D, but extracting features in 3D.

> GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

When using a symmetrical GLCM, the value of GLCM_SumAverage is mathmatically equal to 2 * GLCM_JointAverage. Therefore only one of those features is needed as the other does not add any information (and will even have identical values after normalization of feature values)

**Comment by ctwangtz** [comment]
> Both are warnings and not errors.
> 
> > Calculating Local Binary Pattern in 2D, but extracting features in 3D. Use with caution!
> 
> This reflects your settings. PyRadiomics contains both the 'regular' local binary pattern, which is only defined in 2D, and local binary pattern 3D, which uses spherical harmonics. This warning is shown when using LBP in 2D, but extracting features in 3D.
> 
> > GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
> 
> When using a symmetrical GLCM, the value of GLCM_SumAverage is mathmatically equal to 2 * GLCM_JointAverage. Therefore only one of those features is needed as the other does not add any information (and will even have identical values after normalization of feature values)

Can first problem influence the results?  How to avoid the warning?

**Comment by JoostJM** [comment]
The warnings don't affect the results. Currently it is not possible to disable these warning, but I'll see if I can update the code to emit the warning only once and add an option to disable entirely.

**Comment by gechenyang2** [comment]
I also encountered this problem and couldn't solve it.

**Comment by monteir03** [comment]
> > Can you add some additional information (preferably the stack trace that ended with this error)
> > Can you import `featureextractor` from `radiomics`? It is possible you have a second package `radiomics` installed, which does not have these attributes. If that is so, please uninstall that package to allow Python to discover the correct pyradiomics package via `import radiomics`
> 
> That problem had been solved.
> 
> What do the following warnings mean? Are there some influences to results? How to solved it? Calculating Local Binary Pattern in 2D, but extracting features in 3D. Use with caution! GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated

how did you solve it?
