### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wrrogers** [Radiomics/pyradiomics#651]
There was a issue reported June 24th, issue 596 (https://github.com/Radiomics/pyradiomics/issues/596).  Someone reported that a value error is raised if you pass a mask object that doesn't contain a mask, an error is recieved.  It was changed from a bug to a question.  The thing is, in my opion this is absolutely a bug.  The developers are assuming there are no use cases where a mask is not needed, but there are.  I personally am using phantom data where the preprocessing has already been done outside of pyradiomics.  All I have are images of preprocessed squares that don't require a mask.  I understand that it's to prevent users from accidentally not using a mask, but wouldn't be logical to just provide a warning message?

**Comment by jvanlunenburg** [comment]
in your case wouldn't it make more sense to just supply a unit mask (covering the whole image)

**Comment by wrrogers** [comment]
I thought I did that, embarrassing.  I must have made a mistake with my code.  That makes perfect sense then.  Thanks!
