### ISSUE TITLE
[FEAT EXTRACTION]How to increase the types of features 

### ISSUE THREAD

**Issue by Emmett-S** [Radiomics/pyradiomics#655]
The total numbers of these feature types in the file(csv) is about 102. If I want more, what can i do? Or has anyone expanded the feature types?

**Comment by jvanlunenburg** [comment]
Every software is free to define it's own featureset. If you want more, try using a different software or implementing your own. I believe the IBSI document defines ~170 features.

Other strategies include:
1. exploring different feature parameters (e.g. bin count 64 vs 128)
2. preprocessing images with filters (e.g. LoG or wavelets)
3. Subdividing a mask or extending it to peripheral regions

The first and second are availale as settings parameters in Pyradiomics.
