### ISSUE TITLE
Calculation conditions such as the angle of Radiomic features

### ISSUE THREAD

**Issue by Uchaaan** [Radiomics/pyradiomics#657]
Hello.

I use Pyradiomics to calculate GLCM, GLRLM, GLSZM and GLDM.
I am calculating them under the default conditions.

In which program can I check the conditions?
The conditions are the angle (θ) and pixel distance (d) of GLCM, the angle (θ) and pixel distance (d) of GLRLM, and the angle (θ) and pixel distance (d) of GLDM.

Please let me know if you know them.
Thank you for your help.

**Comment by jvanlunenburg** [comment]
"By default, the value of a feature is calculated on the GLCM for each angle separately, after which the mean of these values is returned." 

Also the function signature says: `distances [[1]]`. Which I think means it will try to get the `distances` argument, or otherwise default to 1.

https://pyradiomics.readthedocs.io/

**Comment by Uchaaan** [comment]
Thanks for telling me.

I checked the distance[1] that you told me about.

The documentation said this.
""""
distances, List of integers, default [1]. This specifies the distances between the center voxel and the neighbor, for which angles should be generated.
(https://pyradiomics.readthedocs.io/en/latest/changes.html?highlight=angles#id176)
""""
How is angle specified, if you can figure out how, please let me know?

Is GLCM or GLRLM calculated with distance = 1 and angel = 0?


Translated with www.DeepL.com/Translator (free version)

**Comment by jvanlunenburg** [comment]
The excerpt I quoted said it averages multiple angles. Usually the angle is 0 + multiples of 45° in every rotation axis. So total 8 angles in 2D and 13 in 3D.

**Comment by JoostJM** [comment]
For GLRLM, the distance is forced to 1, as it should count the consecutive voxels, which may fail if voxels (with potentially different gray values).

As to angles for GLCM, these are computed automatically. For distance 1 these are indeed 45 degrees, though at distance 2 the 22.5 degrees are also used. In essence, it computes offsets for all possible neighbors at that distance (defined by the maximum of the offsets across dimensions). In addition, enabling force2D removes those angles that define an offset moving in the 2d dimension (usually the z dimension)

**Comment by JoostJM** [comment]
Angle calculation is done inside the C extension, an function is provided to just calculate angles, and they are parted of the returned values for calculating GLCM and GLRLM.

**Comment by Uchaaan** [comment]
Thank you for making it so easy to understand.
I understand that it is the average of the values calculated at a multiple of 45 degrees (0,45,90,135...).
It was very helpful.
