### ISSUE TITLE
GLDM matrix calculation

### ISSUE THREAD

**Issue by gayathri199612** [Radiomics/pyradiomics#663]
How gldm matrix is calculated for the different angles for the given image. The output shown for this calculation is given as single matrix without specifying at which angle it is calculated. Can you please clarify the scope of calculating features in different angles and how it is implemented in this package?

**Comment by JoostJM** [comment]
All angles are used to build 1 GLDM matrix. This is similar to how NGTDM and GLSZM are calculated. This is [explained in detail](https://pyradiomics.readthedocs.io/en/latest/features.html#module-radiomics.gldm) in the online documentation.
